/* A separate quiet bath. Camera navigation never moves residents. */
(()=>{'use strict';const V=(x,y,z)=>new THREE.Vector3(x,y,z),$=s=>document.querySelector(s),areas=['home','cafe','bath'];
const lines=[['いい湯でやんす～♪','気持ち良かったでやんす♪'],['いい湯でありますね～♪','気持ち良かったであります♪'],['いい湯だニョロ～♪','気持ち良かったニョロ♪']];
window.ChillBath=class{
 constructor(cafe){this.cafe=cafe;this.c=cafe.c;this.group=new THREE.Group();this.c.scene.add(this.group);this.slots=[V(26.8,.55,-1.35),V(29.2,.55,-1.35),V(26.8,.55,1.25),V(29.2,.55,1.25)];this.reservations=[null,null,null,null];this.gate=null;this.build();this.ui();}
 build(){let r=this.c.room,b=(...a)=>r.box(this.group,...a);b(28,-.18,0,9,.36,8.5,'#d9ddce');b(28,.15,-3.7,8,.3,.45,'#a5b299');b(28,.15,-.05,5.4,.3,4.2,'#879c91');for(let x of [25.35,30.65])b(x,.44,-.05,.3,.5,4.5,'#b5b2a4');for(let z of [-2.2,2.1])b(28,.44,z,5.5,.5,.3,'#b5b2a4');b(28,.53,-.05,5.05,.09,4.0,'#b5ddd8');b(28,.13,3.05,1.5,.26,.7,'#c4c4b4');b(21.5,-.1,5.3,14.3,.16,1,'#cbbda3');this.group.visible=false;}
 ui(){let old=$('#roomSwitch'),bar=old.cloneNode(false);old.replaceWith(bar);bar.innerHTML='<button data-room="home">家</button><button data-room="cafe">カフェ</button><button data-room="bath">温泉</button><button id="bathInvite" aria-label="温泉へのお誘い">♨</button>';bar.querySelectorAll('[data-room]').forEach(b=>b.onclick=()=>this.cafe.setView(b.dataset.room));$('#bathInvite').onclick=()=>this.menu();let start=null,suppress=false;bar.addEventListener('pointerdown',e=>{suppress=false;start={id:e.pointerId,x:e.clientX,y:e.clientY};if(!e.target.closest('button'))bar.setPointerCapture(e.pointerId);});bar.addEventListener('pointerup',e=>{if(start?.id===e.pointerId){let dx=e.clientX-start.x,dy=e.clientY-start.y;if(Math.abs(dx)>45&&Math.abs(dx)>Math.abs(dy)*1.6){suppress=true;let i=areas.indexOf(this.cafe.view);this.cafe.setView(areas[Math.max(0,Math.min(2,i+(dx<0?1:-1)))]);}else if(Math.hypot(dx,dy)<8){let button=e.target.closest('button');if(button){e.preventDefault();button.click();suppress=true;}}}start=null;});bar.addEventListener('click',e=>{if(suppress&&e.detail>0){e.stopImmediatePropagation();e.preventDefault();}},true);bar.addEventListener('pointercancel',()=>start=null);}
 menu(){this.cafe.closeActivity();this.c.modal('小さな温泉','<p>ゆっくりひと休み。カフェでお仕事中のときは、落ち着いてから。</p><div class="bath-controls">'+this.c.actors.map(a=>'<button data-bath="'+a.id+'" '+(!a.bathMode&&(!a.bathReady||!this.eligible(a))?'disabled':'')+'>'+a.name+'：'+(a.bathMode==='entryWait'?'温泉から戻る':a.bathMode==='soak'?'お湯から出る':a.bathMode?'移動中':a.bathReady?'温泉へ行く':'入浴素材を準備中')+'</button>').join('')+'</div><p id="bathStatus" role="status"></p>');document.querySelectorAll('[data-bath]').forEach(b=>b.onclick=()=>{let a=this.c.actors[+b.dataset.bath],ok=['soak','entryWait'].includes(a.bathMode)?this.exit(a):this.visit(a);if(ok)$('#modal').close();else $('#bathStatus').textContent='今の用事が終わってからお誘いください。';});}
 eligible(a){if(a.bathMode||this.c.editing()||this.c.room.mobileEditor)return false;if(a.id===3)return !this.cafe.service&&!this.cafe.cleaning&&!a.cafePath?.length&&!this.cafe.seats.some(id=>id!==null);return a.room==='home'&&a.state==='idle'&&!a.phase&&!a.cafeMode||a.room==='cafe'&&a.cafeMode==='waiting'&&!a.cafePath?.length;}
 visit(a){if(!a.bathReady||!this.eligible(a)||this.reservations[a.id]!==null)return false;let home=a.room==='home',path=home?this.c.route(a.pos,this.cafe.homeDoor):[V(a.pos.x,0,2.7),this.cafe.entry.clone()];if(!path)return false;let old={room:a.room,cafeMode:a.cafeMode};this.reservations[a.id]=a.id;a.bathOrigin=old.room;a.bathMode='travel';a.bathTime=0;a.cafeMode=null;a.phase=null;a.path=[];a.cafePath=[...path,V(home?1.9:14,0,5.3),V(28,0,5.3),V(28,0,3.3)];if(!this.c.save()){a.cafePath=[];a.bathMode=null;a.room=old.room;a.cafeMode=old.cafeMode;this.reservations[a.id]=null;return false;}return true;}
 approach(a){let side=a.id%2===0?25:31,s=this.slots[a.id];a.cafePath=[V(side,0,3.3),V(side,0,s.z),V(side===25?25.65:30.35,.3,s.z),s.clone()];a.bathMode='enter';this.gate=a.id;}
 exit(a){if(a.bathMode==='entryWait'){this.reservations[a.id]=null;a.bathMode='exit';a.cafePath=[V(28,0,3.3)];return true;}if(a.bathMode!=='soak')return false;a.bathMode='exitWait';return true;}
 update(a,dt){if(!a.bathMode)return false;a.speech=Math.max(0,a.speech-dt);a.bathTime=(a.bathTime||0)+dt;let mode=a.bathMode;if(['travel','enter','exit','return'].includes(mode)){let prev=a.pos.clone();if(this.cafe.move(a,dt)){if(mode==='travel'){a.room='bath';a.bathMode='entryWait';}else if(mode==='enter'){a.bathMode='soak';a.bathTime=0;this.gate=null;if(lines[a.id])this.c.speak(a,lines[a.id][0],5,true);this.c.save();}else if(mode==='exit'){if(this.gate===a.id)this.gate=null;this.reservations[a.id]=null;a.bathMode='return';let home=a.bathOrigin==='home';a.cafePath=[V(28,0,5.3),V(home?1.9:14,0,5.3),home?this.cafe.homeDoor.clone():this.cafe.entry.clone()];if(a.id===3)a.cafePath.push(V(10.7,0,2.7),V(10.7,0,-1.85),this.cafe.counter.clone());if(lines[a.id])this.c.speak(a,lines[a.id][1],5,true);this.c.save();}else{a.room=a.bathOrigin||'home';a.bathMode=null;a.cafeMode=a.room==='cafe'&&a.id!==3?'waiting':null;a.cafeTimer=0;a.state='idle';a.timer=2;a.cafeWait=45;this.c.save();}}return true;}if(mode==='entryWait'&&this.gate===null&&a.bathReady)this.approach(a);else if(mode==='soak'&&a.bathTime>24)this.exit(a);else if(mode==='exitWait'&&this.gate===null){this.gate=a.id;let side=a.id%2===0?25:31,s=this.slots[a.id];a.bathMode='exit';a.cafePath=[V(side===25?25.65:30.35,.3,s.z),V(side,0,s.z),V(side,0,3.3),V(28,0,3.3)];}return true;}
 pose(a,time){if(!a.bathMode)return null;if(['soak','exitWait'].includes(a.bathMode))return 'bath_'+Math.floor(time/.42)%4;return a.id<2?'walk_front_'+(Math.floor(time/.18)%2+1):'walk_'+String(Math.floor(time/.18)%4).padStart(2,'0');}
 render(){this.group.visible=this.cafe.view==='bath';this.cafe.group.visible=this.cafe.view==='cafe';this.cafe.doors[1].visible=this.cafe.view==='cafe';for(let a of this.c.actors){if(a.bathMode){$('#state'+a.id).textContent=['soak','exitWait'].includes(a.bathMode)?'入浴中':'温泉への行き帰り';if(a.mealHands)a.mealHands.visible=false;a.effect.style.opacity=0;}let zone=a.pos.x>22?'bath':a.pos.x<6&&a.pos.z<4.6?'home':'cafe';if(zone!==this.cafe.view){a.bubble.style.opacity=0;a.effect.style.opacity=0;}let sleeping=a.sleepGroup.visible;a.sleepGroup.visible=sleeping&&zone===this.cafe.view;a.sprite.visible=zone===this.cafe.view&&!sleeping;a.shadow.visible=zone===this.cafe.view&&!['soak','exitWait'].includes(a.bathMode);}}
 serialize(){return this.c.actors.filter(a=>a.bathMode).map(a=>({id:a.id,origin:a.bathOrigin,mode:a.bathMode}));}
 restore(records){this.gate=null;this.reservations=[null,null,null,null];for(let a of this.c.actors){a.bathMode=null;a.bathTime=0;}for(let r of Array.isArray(records)?records:[]){let a=this.c.actors[r.id];if(!a||!['home','cafe'].includes(r.origin)||a.bathMode)continue;a.bathOrigin=r.origin;a.room='bath';a.bathMode='entryWait';a.pos.set(27.4+a.id*.4,0,3.3);a.cafeMode=null;a.cafePath=[];this.reservations[a.id]=a.id;}}
};
const Base=ChillCafe;window.ChillCafe=class extends Base{
 constructor(c){super(c);this.bath=new ChillBath(this);}
 setView(v){if(!areas.includes(v)||$('#modal').open||this.c.editing()||this.c.room.mobileEditor)return false;this.view=v;document.querySelectorAll('[data-room]').forEach(b=>b.classList.toggle('active',b.dataset.room===v));this.closeActivity();this.c.layout();return true;}
 update(a,dt){if(this.bath?.update(a,dt))return true;return super.update(a,dt);}
 serialize(){return{...super.serialize(),bath:this.bath?.serialize()||[]};}
 restore(s){super.restore(s);this.bath?.restore(s?.bath);}
};
})();
