/* One audio element, game-clock selection, fade-out before switching; independent of save inventory. */
(()=>{'use strict';const key='mob-chill-audio-v1',clamp=(v)=>Math.max(0,Math.min(1,v));let saved={};try{saved=JSON.parse(localStorage.getItem(key)||'{}');}catch{}
class ChillBGM{
 constructor(){this.volume=Number.isFinite(saved.volume)?clamp(saved.volume):.25;this.muted=!!saved.muted;this.unlocked=false;this.current=null;this.level=0;this.error='';this.audio=new Audio();this.audio.loop=true;this.audio.preload='metadata';this.audio.volume=0;this.playPending=false;this.audio.addEventListener('error',()=>{this.error='音源を読み込めませんでした。';});this.button=document.createElement('button');this.button.id='bgmSettings';this.button.textContent='BGM設定';this.button.style.minHeight='44px';document.querySelector('#extraControls').appendChild(this.button);this.button.onclick=()=>this.menu();for(const event of ['pointerdown','keydown'])document.addEventListener(event,()=>this.unlock(),{passive:true});document.addEventListener('visibilitychange',()=>{if(document.hidden)this.stop();});document.addEventListener('freeze',()=>this.stop());let last=performance.now();const tick=now=>{this.update(Math.min(.1,(now-last)/1000));last=now;requestAnimationFrame(tick);};requestAnimationFrame(tick);}
 wanted(){const c=CHILL.cafe,h=(c.clock14%CHILL_WORLD_CONFIG.daySeconds)/CHILL_WORLD_CONFIG.daySeconds*24;return c.view==='arcade'?'arcade':h<5||h>=19?'night':'day';}
 blocked(){return !this.unlocked||this.muted||this.volume===0||document.hidden||CHILL.state.paused||CHILL.cafe.worldFrozen14;}
 unlock(){if(this.unlocked){if(this.context?.state==='suspended')this.context.resume().catch(()=>{});return;}this.unlocked=true;try{const AC=window.AudioContext||window.webkitAudioContext;if(AC){this.context=new AC();this.source=this.context.createMediaElementSource(this.audio);this.gain=this.context.createGain();this.gain.gain.value=0;this.source.connect(this.gain).connect(this.context.destination);this.audio.volume=1;this.context.resume().catch(()=>{});}}catch{this.context=null;this.gain=null;}this.update(0);}
 gainTo(value){this.level=clamp(value);if(this.gain)this.gain.gain.value=this.level;else this.audio.volume=this.level;}
 stop(){this.gainTo(0);this.audio.pause();}
 play(){if(!this.audio.paused||this.playPending)return;this.playPending=true;let promise=this.audio.play();Promise.resolve(promise).then(()=>{this.error='';if(this.blocked())this.stop();}).catch(e=>{if(e?.name==='AbortError')return;this.error='画面をタップして音を再開してください。';if(e?.name==='NotAllowedError')this.unlocked=false;}).finally(()=>this.playPending=false);}
 update(dt){if(this.blocked()){this.stop();return;}const wanted=this.wanted();if(this.current!==wanted){if(this.level>.001){this.gainTo(Math.max(0,this.level-dt*Math.max(this.volume,.1)/.4));return;}this.audio.pause();this.audio.src=CHILL_BGM_ASSETS[wanted];this.current=wanted;this.gainTo(0);this.audio.load();}this.play();this.gainTo(Math.min(this.volume,this.level+dt*Math.max(this.volume,.1)/.6));}
 persist(){try{localStorage.setItem(key,JSON.stringify({volume:this.volume,muted:this.muted}));}catch{this.error='音の設定を保存できませんでした。';}}
 menu(){CHILL.cafe.c.modal('BGM設定','<p>朝・昼と夜で曲が変わります。ゲームセンターでは専用曲が流れます。</p><button id="bgmMute" style="min-height:44px"></button><label style="display:block;margin:16px 0">音量 <output id="bgmPercent"></output><input id="bgmVolume" aria-label="BGM音量" type="range" min="0" max="100" step="1" style="display:block;width:100%;min-height:44px"></label><p id="bgmStatus" role="status"></p>');const mute=document.querySelector('#bgmMute'),slider=document.querySelector('#bgmVolume'),render=()=>{mute.textContent=this.muted?'BGMをオンにする':'BGMをミュート';mute.setAttribute('aria-pressed',String(this.muted));slider.value=Math.round(this.volume*100);document.querySelector('#bgmPercent').textContent=slider.value+'%';document.querySelector('#bgmStatus').textContent=this.error||'ゲームの一時停止・画面を閉じている間は音も止まります。';};mute.onclick=()=>{this.muted=!this.muted;this.persist();this.unlock();this.update(0);render();};slider.oninput=()=>{this.volume=+slider.value/100;this.persist();if(this.level>this.volume)this.gainTo(this.volume);this.update(0);render();};render();}
}
window.CHILL_BGM=new ChillBGM();})();
