/* Three personal tables and unhurried service. Food ownership survives every phase. */
(()=>{'use strict';
const V=(x,y,z)=>new THREE.Vector3(x,y,z),$=s=>document.querySelector(s),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),smooth=t=>t*t*(3-2*t);
const DIALOGUE={open:['今日も、ゆっくり過ごせる一日にしたいですね。','カップもお席も、準備できました。','小さなカフェ、開店です。'],welcome:['いらっしゃいませ。お好きなお席へどうぞ。','お越しくださって、うれしいです。','どうぞ、ひと休みしていってくださいね。','あら、お待ちしていました。'],deposit:['大切にお預かりしますね。','ありがとうございます。お席まで丁寧にお運びします。','みなさんに召し上がっていただきますね。','お預かりしました。準備しておきますね。'],empty:['ただいまお料理を待っています。','お料理のご用意ができたら、お持ちしますね。','今日は何が届くでしょう。楽しみです。'],wait:['お席でゆっくりお待ちくださいね。','順番にお持ちします。もう少しだけ。','もうすぐ、お席へ伺いますね。'],carry:['お料理をお持ちしますね。','温かいうちに、お届けします。','足元に気をつけて、お運びしますね。'],serve:['こちらに、そっと置きますね。','お待たせしました。どうぞ。','ふふっ、ゆっくり召し上がってください。','お皿、こちらでよろしいですか。'],after:['お口に合いましたか。','ほっとしたお顔が見られて、うれしいです。','楽しいひとときになりましたか。','ゆっくり味わってくださって、ありがとうございます。'],tidy:['お席を整えておきますね。','次の方も気持ちよく過ごせるように。','小さなお片付けも、大切なお仕事です。'],goodbye:['ありがとうございました。またどうぞ。','またお話ししましょうね。','お気をつけてお帰りください。','いつでも、ひと休みにいらしてください。'],idle:['窓辺の光が、やわらかいですね。','ここでの時間は、少しゆっくりですね。','ひと息つく場所があるって、いいですね。','次はどんなお話が聞けるでしょう。']};
window.CHILL_CAFE_DIALOGUE=DIALOGUE;
const Base=window.ChillCafe;
window.ChillCafe=class extends Base{
 constructor(c){super(c);this.dialogueCursor={};this.lastLine='';this.activity=[];this.idleTime=0;this.installActivity();this.needsWelcome=true;}
 build(){let r=this.c.room,b=(g,...a)=>r.box(g,...a),g=this.group;this.tables=[];this.seats=[null,null,null];
 b(g,14,-.18,0,9,.36,8.5,'#efe5d1');b(g,14,1.4,-4.1,9,2.8,.14,'#e5dbca');b(g,9.5,1.4,0,.14,2.8,8.3,'#e4ddcc');b(g,10.7,1.05,-3.65,1.65,2.1,.5,'#bd9771');for(let y of [.45,1.15,1.9])b(g,10.7,y,-3.3,1.7,.08,.72,'#f3e8d0');b(g,14,.5,-2.65,3.3,1,.7,'#b4bea3');b(g,14,1.05,-2.65,3.6,.13,.9,'#dbb58d');
 for(let x of [12,14,16]){let set=new THREE.Group();g.add(set);b(set,x,.75,0,1.08,.12,.95,'#dab184');for(let dx of [-.4,.4])for(let z of [-.32,.32])b(set,x+dx,.35,z,.08,.7,.08,'#b18a61');b(set,x,.42,-1.03,.65,.12,.65,'#a5b593');b(set,x,.75,-1.32,.65,.6,.09,'#a5b593');for(let dx of [-.24,.24])for(let z of [-.79,-1.26])b(set,x+dx,.2,z,.07,.4,.07,'#b18a61');this.tables.push({group:set,x,top:.84,seat:V(x,.48,-1.03),approach:V(x-.85,0,-1.9),serve:V(x-.89,0,-.25),plate:V(x-.32,.84,-.12)});}
 this.tray=new THREE.Group();b(this.tray,0,-.085,0,.53,.028,.34,'#987049');for(let x of [-.24,.24])r.cyl(this.tray,x,-.075,.02,.055,.055,.07,'#faf3df',12);this.c.scene.add(this.tray);this.tray.visible=false;this.doors=[];for(let x of [1.9,14]){let d=new THREE.Group();d.position.set(x,0,4.05);this.c.scene.add(d);for(let dx of [-.61,.61])b(d,dx,1.1,0,.10,2.2,.14,'#a18162');b(d,0,2.2,0,1.32,.12,.14,'#a18162');let leaf=new THREE.Group();leaf.position.x=-.55;d.add(leaf);b(leaf,.55,1.05,0,1.1,2.1,.08,'#c7b697');b(leaf,.95,1,.08,.09,.09,.06,'#796a4e');leaf.rotation.y=-1.25;this.doors.push(d);}b(g,7.5,-.1,5.3,14.3,.16,1,'#cbbda3');this.dishes=this.tables.map(()=>{let d=this.c.snack.clone(true);this.c.scene.add(d);d.visible=false;return d;});}
 installActivity(){let panel=document.createElement('aside');panel.id='activityPanel';panel.hidden=true;panel.innerHTML='<div class="activity-heading"><strong>住民と小さなできごと</strong><button id="closeActivity" aria-label="住民と履歴を閉じる">×</button></div><div id="activityList"></div>';document.body.appendChild(panel);panel.insertBefore($('.residents'),$('#activityList'));let toggle=document.createElement('button');toggle.id='activityToggle';toggle.textContent='住民・履歴';toggle.setAttribute('aria-expanded','false');$('footer').prepend(toggle);toggle.onclick=()=>{panel.hidden=!panel.hidden;toggle.setAttribute('aria-expanded',String(!panel.hidden));this.renderActivity();};$('#closeActivity').onclick=()=>this.closeActivity();panel.addEventListener('click',e=>{if(e.target.closest('[data-actor]'))this.closeActivity();});}
 closeActivity(){if($('#activityPanel'))$('#activityPanel').hidden=true;$('#activityToggle')?.setAttribute('aria-expanded','false');}
 record(a,text){if(!this.activity)return;this.activity.unshift({name:a.name,text});this.activity=this.activity.slice(0,30);if($('#activityPanel')&&!$('#activityPanel').hidden)this.renderActivity();}
 renderActivity(){let list=$('#activityList');if(!list)return;list.replaceChildren();for(let item of this.activity.slice(0,12)){let p=document.createElement('p'),b=document.createElement('b');b.textContent=item.name;p.append(b,document.createTextNode(item.text));list.appendChild(p);}}
 setView(v){let result=super.setView(v);if(result)this.closeActivity();return result;}
 pick(event){let list=DIALOGUE[event]||DIALOGUE.idle,n=this.dialogueCursor[event]||0,line=list[n%list.length];if(line===this.lastLine){n++;line=list[n%list.length];}this.dialogueCursor[event]=n+1;this.lastLine=line;return line;}
 staff(event){let line=this.pick(event);this.c.speak(this.c.actors[3],line,4);return line;}
 say(a,index){if(a.id===3)return this.pick(['welcome','wait','carry','serve','after','goodbye'][index%6]);if(a.id===2)return ['ここは落ち着くニョロ～','ひと休みするニョロ','カフェへ行くニョロ！','のんびり待つニョロ～','おいしいニョロ～！','また来るニョロ！'][index%6];return super.say(a,index);}
 menu(a){this.closeActivity();super.menu(a);}
 foodIcon(k){let art=k==='dorayaki'?'<ellipse cx="32" cy="39" rx="23" ry="10" fill="#985b31"/><ellipse cx="32" cy="34" rx="23" ry="10" fill="#663f2d"/><ellipse cx="32" cy="29" rx="23" ry="11" fill="#e2aa55"/><path d="M19 27q12-8 23 0" fill="none" stroke="#f8ce85" stroke-width="3"/>':k==='omelet'?'<path d="M10 44h44l-4 7H14z" fill="#eae4cf"/>'+[0,1,2].map(i=>'<rect x="'+(12+i*13)+'" y="23" width="14" height="22" rx="4" fill="'+(i%2?'#efc456':'#f5d375')+'" stroke="#c99b43" stroke-width="2"/>').join(''):'<path d="M10 29h44q-2 23-22 23T10 29" fill="#d19a6b"/><ellipse cx="32" cy="29" rx="22" ry="8" fill="#f1d779" stroke="#f7e9ca" stroke-width="4"/><path d="M24 19q-5-5 0-10m14 10q-5-5 0-10" fill="none" stroke="#c0b59d" stroke-width="3" stroke-linecap="round"/>';return '<svg viewBox="0 0 64 64" aria-hidden="true">'+art+'</svg>';}
 depositMenu(){this.closeActivity();let amounts={dorayaki:0,omelet:0,soup:0};this.c.modal('料理をあずける','<section class="meal-deposit"><div class="deposit-intro"><span class="keeper-seal">I</span><div><b>イルカエルのカフェ</b><p>お席まで、ひと皿ずつお届けします。</p></div></div><div class="meal-cards">'+Object.entries(CHILL_RECIPES).map(([k,r])=>'<article class="meal-card" data-meal="'+k+'"><div class="meal-art">'+this.foodIcon(k)+'</div><div class="meal-info"><h3>'+r.name+'</h3><p>もちもの <b data-owned="'+k+'">'+this.c.kitchen.inventory[k]+'</b><span>お預かり <b data-cafe-stock="'+k+'">'+this.ledger.stock[k]+'</b></span></p></div><div class="quantity-stepper"><button data-less="'+k+'" aria-label="'+r.name+'を1個減らす">−</button><output data-amount="'+k+'" aria-label="'+r.name+'の選択数">0</output><button data-more="'+k+'" aria-label="'+r.name+'を1個増やす">＋</button></div></article>').join('')+'</div><p id="depositStatus" role="status">料理を選んで、個数を決めてください。</p><div class="deposit-confirm"><button id="depositBack">戻る</button><button id="confirmDeposit" class="primary" disabled>料理を選んでください</button></div></section>');const render=()=>{let total=Object.values(amounts).reduce((a,b)=>a+b,0);for(let k of Object.keys(amounts)){$('[data-amount="'+k+'"]').textContent=amounts[k];$('[data-less="'+k+'"]').disabled=amounts[k]===0;$('[data-more="'+k+'"]').disabled=amounts[k]>=this.c.kitchen.inventory[k];$('[data-meal="'+k+'"]').classList.toggle('chosen',amounts[k]>0);$('[data-owned="'+k+'"]').textContent=this.c.kitchen.inventory[k];$('[data-cafe-stock="'+k+'"]').textContent=this.ledger.stock[k];}$('#confirmDeposit').disabled=total===0;$('#confirmDeposit').textContent=total?total+'個をあずける':'料理を選んでください';};for(let k of Object.keys(amounts)){$('[data-less="'+k+'"]').onclick=()=>{amounts[k]=Math.max(0,amounts[k]-1);render();};$('[data-more="'+k+'"]').onclick=()=>{amounts[k]=Math.min(this.c.kitchen.inventory[k],amounts[k]+1);render();};}$('#depositBack').onclick=()=>$('#modal').close();$('#confirmDeposit').onclick=()=>{let total=Object.values(amounts).reduce((a,b)=>a+b,0);if(this.ledger.depositMany(this.c.kitchen.inventory,amounts,this.c.save)){for(let k of Object.keys(amounts))amounts[k]=0;$('#depositStatus').textContent=total+'個お預かりしました。'+this.staff('deposit');render();}else $('#depositStatus').textContent='保存できませんでした。料理はもちものへ戻しています。';};render();}
 furnitureMenu(){this.closeActivity();this.c.modal('カフェのお席','<p>小テーブルと椅子を、1組ずつ出し入れします。</p>'+this.tables.map((t,i)=>'<div class="cafe-furniture-row"><b>お席 '+(i+1)+'</b><span>'+(this.seats[i]!==null?'ご利用中':t.group.visible?'空席':'収納中')+'</span><button data-table-storage="'+i+'">'+(t.group.visible?'収納する':'配置する')+'</button></div>').join('')+'<p id="cafeFurnitureStatus" role="status"></p>');document.querySelectorAll('[data-table-storage]').forEach(b=>b.onclick=()=>{let i=+b.dataset.tableStorage;if(!this.setTableVisible(i,!this.tables[i].group.visible))$('#cafeFurnitureStatus').textContent='着席・移動・配膳中のお席は片付けられません。';else this.furnitureMenu();});}
 setTableVisible(i,visible){if(!this.tables[i]||this.seats[i]!==null||this.ledger.orders[i]||this.service?.seat===i)return false;let t=this.tables[i],old=t.group.visible;t.group.visible=visible;if(this.c.save())return true;t.group.visible=old;return false;}
 serialize(){return{...this.ledger.serialize(),tableCount:3,tableVisibility:this.tables.map(t=>t.group.visible),dialogueCursor:{...this.dialogueCursor},lastLine:this.lastLine,residents:this.c.actors.map(a=>({room:a.room,umbrella:!!a.umbrella}))};}
 restore(s){super.restore(s);this.seats=[null,null,null];this.service=null;this.retry=0;this.tables.forEach((t,i)=>t.group.visible=s?.tableCount===3?s.tableVisibility?.[i]!==false:true);this.dialogueCursor={};for(let k of Object.keys(DIALOGUE))if(Number.isSafeInteger(s?.dialogueCursor?.[k])&&s.dialogueCursor[k]>=0)this.dialogueCursor[k]=s.dialogueCursor[k];this.lastLine=typeof s?.lastLine==='string'?s.lastLine:'';for(let a of this.c.actors){a.cafePath=[];a.cafeSeat=null;a.mealKind=null;a.cafeTimer=0;}if(this.needsWelcome){this.needsWelcome=false;this.staff('open');}}
 returnToCounter(){let a=this.c.actors[3];a.cafePath=[V(a.pos.x,0,-1.45),this.counter.clone()];}
 leave(a){if(a.room!=='cafe'||a.id===3||a.cafeMode==='toHome')return false;let i=this.seats.indexOf(a.id);if(i>=0){if(!this.ledger.release(i,this.c.save))return false;this.seats[i]=null;if(this.service?.seat===i){this.service=null;this.returnToCounter();}this.staff('tidy');}a.cafeMode='toHome';a.cafePath=[V(a.pos.x-.85,0,a.pos.z),V(a.pos.x-.85,0,2.2),this.entry.clone(),V(14,0,5.3),V(1.9,0,5.3),V(1.9,0,4.5),this.homeDoor.clone()];this.c.speak(a,this.say(a,5));this.staff('goodbye');return true;}
 update(a,dt){if(a.id===3){this.waiter(dt);return true;}if(!a.cafeMode&&a.room==='home'){a.cafeWait-=dt;if(a.cafeWait<=0&&this.visit(a))return true;return false;}a.speech=Math.max(0,a.speech-dt);if(a.cafeMode==='toCafe'||a.cafeMode==='toHome'){let going=a.cafeMode==='toCafe';if(this.move(a,dt)){if(going){a.room='cafe';a.cafeMode='waiting';a.cafeTimer=0;this.staff('welcome');}else{a.room='home';a.cafeMode=null;a.cafeWait=45+a.id*8;a.state='idle';a.timer=2;}this.c.save();}return true;}if(a.cafeMode==='seating'){if(this.move(a,dt)){a.pos.y=.48;a.cafeMode='seated';a.cafeTimer=0;this.c.speak(a,this.say(a,1));}return true;}a.cafeTimer=(a.cafeTimer||0)+dt;if(a.cafeMode==='waiting'){let i=this.seats.findIndex((s,i)=>s===null&&!this.dirty?.[i]&&this.tables[i].group.visible);if(i>=0){this.seats[i]=a.id;a.cafeSeat=i;a.cafeMode='seating';let t=this.tables[i];a.cafePath=[V(t.x-.85,0,2.1),V(t.x-.85,0,t.seat.z),t.seat.clone()];}else if(a.cafeTimer>12)this.leave(a);}else if(a.cafeMode==='seated'&&a.cafeTimer>60&&!this.ledger.orders[a.cafeSeat])this.leave(a);else if(a.cafeMode==='eating'&&a.cafeTimer>32){a.cafeMode='satisfied';a.cafeTimer=0;this.completeMeal(a);this.staff('after');}else if(a.cafeMode==='satisfied'&&a.cafeTimer>6)this.leave(a);return true;}
 waiter(dt){let a=this.c.actors[3];a.speech=Math.max(0,a.speech-dt);let s=this.service;if(s&&(this.seats[s.seat]!==s.actor||this.c.actors[s.actor].cafeMode!=='seated'||!this.ledger.orders[s.seat])){if(!this.ledger.release(s.seat,this.c.save))return;this.service=null;this.returnToCounter();s=null;}if(a.cafePath?.length){this.move(a,dt);return;}if(s){let guest=this.c.actors[s.actor],order=this.ledger.orders[s.seat];if(s.stage==='carry'){s.stage='settle';s.time=0;this.staff('serve');return;}s.time+=dt;if(s.stage==='settle'&&s.time>=.65){s.stage='lower';s.time=0;}else if(s.stage==='lower'&&s.time>=1.1){if(!this.ledger.land(s.seat,s.actor,this.c.save)){s.time=1.1;return;}s.stage='land';s.time=0;}else if(s.stage==='land'&&s.time>=.45){s.stage='retract';s.time=0;}else if(s.stage==='retract'&&s.time>=.85){let kind=order.kind;if(!this.ledger.consume(s.seat,s.actor,this.c.save))return;guest.mealKind=kind;guest.mealRewardId=this.ledger.eaten;this.c.speak(guest,ChillLife.mealLine(guest,false),5,true);guest.cafeMode='eating';guest.cafeTimer=0;this.service=null;this.returnToCounter();}return;}this.retry-=dt;this.idleTime+=dt;if(this.retry>0)return;this.retry=1;for(let i=0;i<3;i++){let id=this.seats[i],guest=this.c.actors[id];if(id!==null&&guest?.cafeMode==='seated'&&this.ledger.reserve(i,id,this.c.save)){this.service={seat:i,actor:id,stage:'carry',time:0};let t=this.tables[i];a.cafePath=[V(t.serve.x,0,-1.45),t.serve.clone()];this.staff('carry');this.idleTime=0;return;}}if(this.idleTime>24){this.staff(this.seats.some(id=>id!==null&&this.c.actors[id].cafeMode==='seated')?(Object.values(this.ledger.stock).some(n=>n>0)?'wait':'empty'):'idle');this.idleTime=0;}}
 pose(a,time){if(a.id!==3)return super.pose(a,time);let s=this.service,action=a.cafePath?.length?'walk':s&&['lower','land','retract'].includes(s.stage)?'greet_bow':a.speech>0?'chat':'idle',n=Math.floor(time/(action==='walk'?.18:.24))%4;if(action==='greet_bow')n=s.stage==='lower'?Math.min(2,Math.floor(s.time/1.1*3)):s.stage==='land'?2:3;return action+'_'+String(n).padStart(2,'0');}
 handPoint(){let p=this.c.spriteAnchorWorld(this.c.actors[3],[.57,.65],.04),ray=p.clone().sub(this.c.camera.position);return p.addScaledVector(ray,(1.06-p.y)/ray.y);}
 platePoint(i,kind){let p=this.tables[i].plate.clone();p.y=.81+({dorayaki:.066,omelet:.017,soup:.013}[kind]||.066);return p;}
 render(){let c=this.c;this.tray.visible=false;for(let a of c.actors){let home=a.pos.x<6&&a.pos.z<4.6,visible=this.view===(home?'home':'cafe');if(!visible){a.bubble.style.opacity=0;a.effect.style.opacity=0;}if(a.cafeMode||a.id===3){$('#state'+a.id).textContent=a.cafePath?.length?'移動中':a.cafeMode==='eating'?'食事中':a.cafeMode==='seated'?'席 '+(a.cafeSeat+1)+' でひと休み':a.id===3?'カフェの看板娘':'カフェ';a.effect.textContent=a.cafeMode==='satisfied'?'♡':'';}}for(let i=0;i<3;i++){let dish=this.dishes[i],guest=c.actors[this.seats[i]],o=this.ledger.orders[i],eating=guest?.cafeMode==='eating',s=this.service?.seat===i?this.service:null,t=this.tables[i];dish.visible=!!o||eating;if(!dish.visible)continue;let kind=o?.kind||guest.mealKind;ChillLiving.meal(dish,{kind},null);dish.scale.setScalar(.85);if(s){let hand=this.handPoint(),target=this.platePoint(i,kind);if(s.stage==='carry'||s.stage==='settle'){dish.position.copy(hand);this.tray.position.copy(hand);}else if(s.stage==='lower'){let u=smooth(clamp(s.time/1.1,0,1));dish.position.copy(hand).lerp(target,u);this.tray.position.copy(dish.position);}else{dish.position.copy(target);let u=s.stage==='retract'?smooth(clamp(s.time/.85,0,1)):0;this.tray.position.copy(target).lerp(hand,u);}this.tray.position.y+=.101-({dorayaki:.066,omelet:.017,soup:.013}[kind]);this.tray.visible=this.view==='cafe';this.tray.rotation.y=0;}else{dish.position.copy(this.platePoint(i,kind));if(eating&&kind!=='soup')dish.scale.setScalar(.85*Math.max(.18,1-guest.cafeTimer/36));}}}
};
})();
