/* Atomic ownership for bags, prizes and paid/free sessions. No rendering dependencies. */
(function(root){'use strict';
const copy=x=>JSON.parse(JSON.stringify(x)),valid=n=>Number.isSafeInteger(n)&&n>=0,norm=n=>valid(n)?n:0,owners=['player','0','1','2','3','4','5','6'];
class CollectionState {
 constructor(config,catalog,hooks){this.config=config;this.catalog=catalog;this.hooks=hooks;this.busy=false;this.restore(null);}
 restore(raw){const s=raw?.v===1?raw:{};this.state={v:1,serial:norm(s.serial),bags:{},collection:{},gachaStock:{},ufoStock:{},sessions:{},mood:{},history:Array.isArray(s.history)?s.history.slice(-50):[]};
 const allowed=new Set([...this.catalog.map(a=>a.id),...Array.from({length:10},(_,i)=>'P-'+String(i+1).padStart(2,'0')),'wheat','corn','beans','egg','milk','dorayaki','omelet','soup','seed:wheat','seed:corn','seed:beans']);for(const id of owners){let b=s.bags?.[id],base=id==='player'?this.config.playerSlots:this.config.residentSlots,max=id==='player'?this.config.playerMaxSlots:this.config.residentMaxSlots;this.state.bags[id]={slots:Math.min(max,Math.max(base,norm(b?.slots))),items:{}};for(const [k,n]of Object.entries(b?.items||{}))if(allowed.has(k)&&valid(n)&&n>0)this.state.bags[id].items[k]=n;}
 for(const item of this.catalog){this.state.gachaStock[item.id]=valid(s.gachaStock?.[item.id])?s.gachaStock[item.id]:1;if(s.collection?.[item.id])this.state.collection[item.id]=true;}
 for(let i=1;i<=10;i++){let id='P-'+String(i).padStart(2,'0');this.state.ufoStock[id]=valid(s.ufoStock?.[id])?s.ufoStock[id]:1;if(s.collection?.[id])this.state.collection[id]=true;}
 for(let i=0;i<7;i++)this.state.mood[i]=Math.min(5,Math.max(1,norm(s.mood?.[i])||3));
 // Reload cancels unfinished physical sessions and restores each reserved prize/payment once.
 for(const session of Object.values(s.sessions||{})){if(session?.status!=='active')continue;if(session.kind==='gacha'&&Object.hasOwn(this.state.gachaStock,session.prize))this.state.gachaStock[session.prize]++;if(session.owner==='player'&&[3,5].includes(session.paid))this.hooks.wallet().balance+=session.paid;this.state.history.push({id:session.id,kind:session.kind,status:'cancelled-on-reload'});}
 this.state.history=this.state.history.slice(-50);
 }
 serialize(){return copy(this.state);}
 items(owner){owner=String(owner);const b=this.state.bags[owner];if(!b)return {};return owner==='player'?{...b.items,...this.hooks.pantry(),...this.hooks.seeds()}:copy(b.items);}
 used(owner,items=this.items(owner)){return Object.values(items).reduce((n,v)=>n+Math.ceil(norm(v)/this.config.stackSize),0);}
 canAdd(owner,key,n=1){owner=String(owner);const b=this.state.bags[owner];if(!b||!valid(n)||!n)return false;const items=this.items(owner);items[key]=norm(items[key])+n;if(!valid(items[key]))return false;let pending=Object.values(this.state.sessions).filter(s=>s.owner===owner&&s.status==='active'&&s.kind!=='race');for(let s of pending){if(s.prize)items[s.prize]=norm(items[s.prize])+1;else items['reserved:'+s.id]=1;}return this.used(owner,items)<=b.slots;}
 change(owner,key,delta){owner=String(owner);let bag=this.state.bags[owner];if(!bag)throw Error('owner');let target=bag.items;if(owner==='player'&&Object.hasOwn(this.hooks.pantry(),key))target=this.hooks.pantry();if(owner==='player'&&key.startsWith('seed:')){this.hooks.changeSeed(key.slice(5),delta);return;}let n=norm(target[key])+delta;if(!valid(n))throw Error('invalid-count');target[key]=n;}
 transaction(fn){if(this.busy)return {ok:false,reason:'busy'};const before=this.serialize(),external=this.hooks.snapshot();this.busy=true;try{const result=fn();if(result?.ok===false){this.state=before;this.hooks.rollback(external);return result;}if(this.hooks.save()!==true)throw Error('save-failed');return {ok:true,...result};}catch(e){this.state=before;this.hooks.rollback(external);return {ok:false,reason:e.message};}finally{this.busy=false;}}
 transfer(from,to,key,n=1){return this.transaction(()=>{from=String(from);to=String(to);if(from===to||!owners.includes(from)||!owners.includes(to)||!valid(n)||!n||norm(this.items(from)[key])<n)return {ok:false,reason:'not-owned'};if(!this.canAdd(to,key,n))return {ok:false,reason:'full'};if(this.locked(from,key))return {ok:false,reason:'in-use'};this.change(from,key,-n);this.change(to,key,n);if(to!=='player')this.state.mood[to]=Math.min(5,this.state.mood[to]+1);return {};});}
 locked(owner,key){return !!this.hooks.itemLocked?.(String(owner),key);}
 consume(owner,key){return this.transaction(()=>{if(!['dorayaki','omelet','soup'].includes(key)||norm(this.items(owner)[key])<1)return {ok:false,reason:'not-food'};this.change(owner,key,-1);if(String(owner)!=='player')this.state.mood[owner]=Math.min(5,this.state.mood[owner]+1);return {};});}
 expand(owner){return this.transaction(()=>{owner=String(owner);let b=this.state.bags[owner],max=owner==='player'?this.config.playerMaxSlots:this.config.residentMaxSlots,price=this.config.bagExpansionPrice;if(!b||b.slots>=max||this.hooks.wallet().balance<price)return {ok:false,reason:'cannot-expand'};this.hooks.wallet().balance-=price;b.slots++;return {};});}
 busyDevice(device){return Object.values(this.state.sessions).some(s=>s.device===device&&s.status==='active');}
 busyOwner(owner){return Object.values(this.state.sessions).some(s=>s.status==='active'&&(s.owner===String(owner)||s.participants?.includes(String(owner))));}
 chooseGacha(random){const weights=this.config.arcade.gachaWeights,available=this.catalog.filter(a=>this.state.gachaStock[a.id]>0),rarities=Object.keys(weights).filter(r=>available.some(a=>a.rarity===r)),total=rarities.reduce((s,r)=>s+weights[r],0);if(!total)return null;let v=random()*total,rarity=rarities.at(-1);for(let r of rarities){v-=weights[r];if(v<0){rarity=r;break;}}const items=available.filter(a=>a.rarity===rarity);return items[Math.min(items.length-1,Math.floor(random()*items.length))]?.id;}
 begin(kind,owner,device,participants=[],random=Math.random){return this.transaction(()=>{owner=String(owner);if(!owners.includes(owner)||!['gacha','ufo','race'].includes(kind)||!device.startsWith(kind)||this.busyDevice(device)||this.busyOwner(owner))return {ok:false,reason:'busy'};if(kind!=='race'&&this.used(owner)>=this.state.bags[owner].slots)return {ok:false,reason:'full'};let prize=null;if(kind==='gacha'){prize=this.chooseGacha(random);if(!prize)return {ok:false,reason:'empty'};if(!this.canAdd(owner,prize))return {ok:false,reason:'full'};}if(kind==='ufo'&&!Object.values(this.state.ufoStock).some(n=>n>0))return {ok:false,reason:'empty'};participants=participants.map(String);if(kind==='race'&&(!(owner==='player'&&participants.length===0)&&participants.length!==2||new Set(participants).size!==participants.length||participants.some(id=>!['0','1','2','3','4','5','6'].includes(id)||this.busyOwner(id))))return {ok:false,reason:'two-residents-required'};
 const paid=owner==='player'?this.config.arcade.playerPrices[kind]:0;if(this.hooks.wallet().balance<paid)return {ok:false,reason:'hearts'};this.hooks.wallet().balance-=paid;if(prize)this.state.gachaStock[prize]--;const id=++this.state.serial;this.state.sessions[id]={id,kind,owner,device,participants,paid,prize,status:'active'};return {id,prize,paid};});}
 finish(id,outcome={}){return this.transaction(()=>{const s=this.state.sessions[id];if(!s||s.status!=='active')return {ok:false,reason:'already-finished'};let prize=s.kind==='gacha'?s.prize:s.kind==='ufo'&&outcome.caught?outcome.prize:null;
 // Exclude this session's own capacity reservation while validating its final item.
 delete this.state.sessions[id];if(prize){if(s.kind==='ufo'&&!(this.state.ufoStock[prize]>0))return {ok:false,reason:'empty'};if(!this.canAdd(s.owner,prize))return {ok:false,reason:'full'};if(s.kind==='ufo')this.state.ufoStock[prize]--;this.change(s.owner,prize,1);this.state.collection[prize]=true;}
 const won=!!prize||s.kind==='race'&&s.participants.includes(String(outcome.winner));for(let a of s.kind==='race'?s.participants:s.owner==='player'?[]:[s.owner])this.state.mood[a]=Math.max(1,Math.min(5,this.state.mood[a]+(s.kind==='race'?(String(outcome.winner)===a?1:-1):won?1:-1)));this.state.history.push({id,kind:s.kind,owner:s.owner,paid:s.paid,status:'complete',prize,winner:s.kind==='race'?String(outcome.winner):null});this.state.history=this.state.history.slice(-50);return {prize,owner:s.owner,kind:s.kind,winner:outcome.winner};});}
 cancel(id){return this.transaction(()=>{const s=this.state.sessions[id];if(!s)return {ok:false,reason:'already-finished'};if(s.prize)this.state.gachaStock[s.prize]++;if(s.owner==='player')this.hooks.wallet().balance+=s.paid;delete this.state.sessions[id];this.state.history.push({id,status:'cancelled'});this.state.history=this.state.history.slice(-50);return {};});}
 restock(kind,id,n=1){return this.transaction(()=>{let stock=kind==='gacha'?this.state.gachaStock:kind==='ufo'?this.state.ufoStock:null;if(!stock||!Object.hasOwn(stock,id)||!Number.isSafeInteger(n)||n<1||n>99)return {ok:false,reason:'invalid-item'};let cost=this.config.arcade.restockPrices[kind]*n;if(this.hooks.wallet().balance<cost)return {ok:false,reason:'hearts'};if(kind==='ufo'&&stock[id]+n>1)return {ok:false,reason:'display-full'};if(!valid(stock[id]+n))return {ok:false,reason:'overflow'};this.hooks.wallet().balance-=cost;stock[id]+=n;return {};});}
 disappoint(owner){return this.transaction(()=>{owner=String(owner);if(!Object.hasOwn(this.state.mood,owner))return {ok:false};this.state.mood[owner]=Math.max(1,this.state.mood[owner]-1);return {};});}
}
root.ChillCollectionState=CollectionState;if(typeof module!=='undefined')module.exports=CollectionState;
})(typeof window==='undefined'?globalThis:window);
