/* Game-clock routines. No wall-clock catch-up, invented meals, or cancellation of an active job. */
(()=>{'use strict';const D=CHILL_ROUTINE_DATA,T=THREE,V=(x=0,y=0,z=0)=>new T.Vector3(x,y,z),copy=o=>JSON.parse(JSON.stringify(o));
class DailyRoutine{
 constructor(cafe){this.cafe=cafe;this.c=cafe.c;this.state={v:1,days:{},meta:{},ownerMeal:null};this.manual=new Map();this.lastPlan=-1;this.ownerDish=new T.Group();this.c.scene.add(this.ownerDish);this.ownerDish.visible=false;}
 get now(){return this.cafe.clock14||0;}get day(){return Math.floor(this.now/CHILL_WORLD_CONFIG.daySeconds);}get hour(){return this.now%CHILL_WORLD_CONFIG.daySeconds/CHILL_WORLD_CONFIG.daySeconds*24;}
 meta(a){return this.state.meta[a.key]||(this.state.meta[a.key]={lastMealAt:-1e6,meals:0,mealDay:this.day,line:0,rest:false});}
 window(a){return D.windows.find(w=>{const h=w.type==='sleep'&&this.hour<6?this.hour+24:this.hour;return h>=w.from+a.id*D.staggerHours&&h<w.to;});}
 record(a,w,create=true){const day=w.type==='sleep'&&this.hour<6?Math.max(0,this.day-1):this.day,key=day+':'+a.key+':'+w.id;if(!this.state.days[key]&&create)this.state.days[key]={day,actor:a.key,slot:w.id,type:w.type,phase:'queued',created:this.now,next:0};return this.state.days[key];}
 active(a){return Object.values(this.state.days).find(r=>r.actor===a.key&&r.type==='meal'&&r.phase==='started');}
 canEat(a){const m=this.meta(a);return this.manual.get(a.key)>this.now||this.now-m.lastMealAt>=D.minimumMealGapHours*CHILL_WORLD_CONFIG.daySeconds/24&&(m.mealDay!==this.day||m.meals<D.maxMealsPerDay);}
 mayReserve(a){return !!a&&this.canEat(a)&&(this.manual.get(a.key)>this.now||this.window(a)?.type==='meal'||!!this.active(a));}
 say(a,scene){const lines=D.dialogue[a.key]?.[scene];if(!lines)return;const m=this.meta(a);this.c.speak(a,lines[m.line++%lines.length],6,true);}
 idle(a){if(document.querySelector('#modal').open||this.c.editing()||this.c.room.mobileEditor||a.bathMode||a.arcadeMode||a.bagAnimation||a.phase||a.state!=='idle'||a.path?.length||a.cafePath?.length||a.npcOutdoor)return false;if(a.id===3)return this.cafe.staffMealAvailable();return !a.cafeMode||a.cafeMode==='waiting';}
 transition(r,phase){const old=copy(r);r.phase=phase;r.next=this.now+D.retrySeconds;if(this.c.save())return true;Object.assign(r,old);return false;}
 credit(a){const before=copy(this.state),m=this.meta(a);if(m.mealDay!==this.day){m.mealDay=this.day;m.meals=0;}m.meals++;m.lastMealAt=this.now;let r=this.active(a),w=this.window(a);if(!r&&w?.type==='meal')r=this.record(a,w);if(r){r.phase='done';r.finished=this.now;}this.manual.delete(a.key);return()=>{this.state=before;};}
 ate(a){this.credit(a);this.c.save();}
 plan(){if(this.lastPlan===Math.floor(this.now))return;this.lastPlan=Math.floor(this.now);for(const [key,r]of Object.entries(this.state.days))if(r.day<this.day-2)delete this.state.days[key];for(const a of this.c.actors){const m=this.meta(a);if((m.rest||m.bed)&&this.hour>=6&&this.hour<22){m.rest=false;m.bed=false;a.routineNight=false;if(a.phase?.pose==='sleep')a.phaseTime=a.phase.duration;a.routineRest=false;if(a.phase?.routineRest)a.phase=null;if(a.addedResident)a.npcPose='idle';this.say(a,'wake');this.c.save();}const w=this.window(a);for(const r of Object.values(this.state.days))if(r.actor===a.key&&['queued','waiting'].includes(r.phase)&&(!w||w.id!==r.slot||r.day!==this.day&&r.type!=='sleep')){r.phase='missed';this.c.save();}if(!w)continue;const r=this.record(a,w);if(['done','missed','resting'].includes(r.phase)||this.now<r.next)continue;if(r.phase==='started'){if(r.type==='meal'&&!a.cafeMode&&!a.phase&&!this.state.ownerMeal&&this.now-r.created>120){r.phase='missed';this.c.save();}continue;}r.next=this.now+D.retrySeconds;if(!this.idle(a))continue;if(r.type==='meal'){if(!this.canEat(a)){this.transition(r,'done');continue;}this.meal(a,r);}else if(r.type==='bath')this.bath(a,r);else this.sleep(a,r);}}
 meal(a,r){const pantry=this.c.kitchen.inventory,stock=this.cafe.ledger.stock,kinds=['dorayaki','omelet','soup'],kind=kinds.find(k=>stock[k]>0)||kinds.find(k=>pantry[k]>0);if(!kind){if(!r.explained){r.explained=true;this.say(a,'hungry');this.c.save();}return;}if(!this.transition(r,'started'))return;this.say(a,r.slot);
 if(a.key==='nekokoo'){const ownKind=kinds.find(k=>pantry[k]>0);if(!ownKind){r.phase='queued';this.say(a,'wait');return;}const old=copy(this.state);pantry[ownKind]--;this.state.ownerMeal={kind:ownKind,time:0,consumed:false};if(!this.c.save()){pantry[ownKind]++;this.state=old;r.phase='queued';}return;}
 if(a.id===3){const staffKind=kinds.find(k=>pantry[k]>0);if(!staffKind||!this.cafe.startStaffMeal(staffKind)){r.phase='queued';this.say(a,'wait');}return;}
 if(a.id<2&&a.room==='home'&&window.CHILL?.state.food?.state==='placed'){if(window.CHILL.start(a,'eat'))return;}
 const pending=Object.values(this.state.days).filter(x=>x.type==='meal'&&x.phase==='started'&&!['irukaeru','nekokoo'].includes(x.actor)&&!Object.values(this.cafe.ledger.orders).some(o=>this.c.actors[o.actor]?.key===x.actor)).length;if(Object.values(stock).reduce((n,v)=>n+v,0)<pending){const k=kinds.find(k=>pantry[k]>0);if(k&&!this.cafe.ledger.deposit(pantry,k,1,this.c.save)){r.phase='queued';return;}}
 if(a.room==='cafe'&&a.cafeMode==='waiting')return;if(a.room==='home'&&this.cafe.visit(a))return;r.phase='queued';this.say(a,'wait');this.c.save();
 }
 bath(a,r){if(!this.transition(r,'started'))return;this.say(a,'bathBefore');if(a.key==='nekokoo'){r.phase='done';this.c.save();return;}if(!a.bathReady){r.phase='done';this.say(a,'fallback');if(a.key==='tetsu')a.npcPose='meditate';this.c.save();return;}if(this.cafe.bath.visit(a)){r.phase='done';this.meta(a).bathActive=true;this.c.save();}else{r.phase='queued';this.say(a,'wait');}}
 sleep(a,r){if(!this.transition(r,'done'))return;this.say(a,'bed');const m=this.meta(a);if(a.id<2&&a.room==='home'&&window.CHILL?.start(a,'nap')){m.bed=true;a.routineNight=true;this.c.save();return;}m.rest=true;a.routineRest=true;if(a.key==='tetsu'){a.npcPose='sleepSeat';a.path=[];}else if(!a.addedResident){a.phase={name:'夜の休息',pose:'sit',duration:1e9,routineRest:true};a.phaseTime=0;}this.c.save();}
 update(a,dt){if(a.id===0)this.plan();const m=this.meta(a);if(m.bathActive&&!a.bathMode){m.bathActive=false;this.say(a,'bathAfter');this.c.save();}if(a.key==='nekokoo'&&this.state.ownerMeal){const meal=this.state.ownerMeal;a.speech=Math.max(0,a.speech-dt);meal.time+=dt;if(!meal.consumed&&meal.time>=.7){const before=copy(this.state);meal.consumed=true;this.credit(a);if(!this.c.save()){this.state=before;return true;}this.c.speak(a,ChillLife.mealLine(a,false),5,true);}if(meal.time>=32){this.state.ownerMeal=null;if(!this.c.save()){this.state.ownerMeal=meal;return true;}this.c.speak(a,ChillLife.mealLine(a,true),5,true);this.cafe.reward('owner-meal:'+this.day+':'+m.meals,a,'meal');}return true;}
 if(m.bed&&a.routineNight&&a.phase?.pose==='sleep'){if(!this.c.editing()&&!this.c.room.mobileEditor){a.speech=Math.max(0,a.speech-dt);return true;}m.bed=false;a.routineNight=false;}if(m.rest){if(this.c.editing()||this.c.room.mobileEditor){m.rest=false;a.routineRest=false;if(a.phase?.routineRest)a.phase=null;return false;}a.routineRest=true;a.speech=Math.max(0,a.speech-dt);return true;}return false;}
 render(){const a=this.c.actors.find(a=>a.key==='nekokoo'),meal=this.state.ownerMeal;this.ownerDish.visible=!!meal&&this.cafe.view==='bath';if(this.ownerDish.visible){ChillLiving.meal(this.ownerDish,{kind:meal.kind},null);ChillLife.bite(this.ownerDish,a,meal.time,32,this.c);this.ownerDish.scale.multiplyScalar(.3);}else if(a?.mealHands&&!a.cafeMode)a.mealHands.visible=false;for(const a of this.c.actors)if(a.routineRest){if(a.key==='nekokoo'&&a.hasAsset)a.sprite.material.map=a.textures[1];if(a.speech<=0){a.effect.hidden=false;a.effect.textContent='z z Z';const p=a.pos.clone().add(V(0,1.5,0)).project(this.c.camera);a.effect.style.left=(p.x*.5+.5)*innerWidth+'px';a.effect.style.top=(-p.y*.5+.5)*innerHeight+'px';a.effect.style.opacity=a.room===this.cafe.view?1:0;}}}
 restore(raw){this.state={v:1,days:{},meta:{},ownerMeal:null};if(raw?.v===1){for(const [k,r]of Object.entries(raw.days||{}))if(r&&Number.isSafeInteger(r.day)&&r.day>=0&&this.c.actors.some(a=>a.key===r.actor)&&D.windows.some(w=>w.id===r.slot)&&['queued','waiting','started','done','missed','resting'].includes(r.phase))this.state.days[k]={...r,next:0};for(const a of this.c.actors){const m=raw.meta?.[a.key];if(m)this.state.meta[a.key]={lastMealAt:Number.isFinite(m.lastMealAt)?m.lastMealAt:-1e6,mealDay:Number.isSafeInteger(m.mealDay)?m.mealDay:this.day,meals:Number.isSafeInteger(m.meals)?Math.max(0,m.meals):0,line:Number.isSafeInteger(m.line)?m.line:0,rest:!!m.rest||!!m.bed};}if(raw.ownerMeal&&CHILL_RECIPES[raw.ownerMeal.kind]){if(raw.ownerMeal.consumed)this.state.ownerMeal={kind:raw.ownerMeal.kind,time:Math.max(0,Math.min(31,Number(raw.ownerMeal.time)||0)),consumed:true};else this.c.kitchen.inventory[raw.ownerMeal.kind]++;}}
 this.lastPlan=-1;for(const a of this.c.actors){a.routineRest=false;const m=this.meta(a);if(m.rest&&!(this.hour>=6&&this.hour<22)){a.routineRest=true;if(a.key==='tetsu')a.npcPose='sleepSeat';else if(!a.addedResident)a.phase={name:'夜の休息',pose:'sit',duration:1e9,routineRest:true};}else m.rest=false;for(const r of Object.values(this.state.days))if(r.actor===a.key&&r.phase==='started'&&r.type==='meal'&&!this.state.ownerMeal)r.phase=m.lastMealAt>=r.created?'done':'queued';}}
}
const Base=ChillCafe;window.ChillCafe=class extends Base{
 constructor(c){super(c);this.routine=new DailyRoutine(this);const reserve=this.ledger.reserve,consume=this.ledger.consume;this.ledger.reserve=(seat,id,save)=>this.routine.mayReserve(c.actors[id])&&reserve.call(this.ledger,seat,id,save);this.ledger.consume=(seat,id,save)=>{if(!c.actors[id])return false;const rollback=this.routine.credit(c.actors[id]);const ok=consume.call(this.ledger,seat,id,save);if(!ok)rollback();return ok;};document.addEventListener('click',e=>{if(e.target.closest('#visitCafe,#npcVisitCafe,[data-staff-meal]'))for(const a of c.actors)this.routine.manual.set(a.key,this.clock14+90);},true);}
 serialize(){return{...super.serialize(),routine17:this.routine?copy(this.routine.state):null};}
 restore(s){super.restore(s);if(this.routine){this.routine.restore(s?.routine17);if(s?.staffMeal?.consumed){const a=this.c.actors[3],old=Object.entries(s.routine17?.days||{}).find(([,r])=>r.actor===a.key&&r.type==='meal'&&r.phase==='started');if(old){const r=this.routine.state.days[old[0]],m=this.routine.meta(a);if(r){if(m.lastMealAt<r.created){if(m.mealDay!==this.routine.day){m.mealDay=this.routine.day;m.meals=0;}m.meals++;m.lastMealAt=this.clock14;}r.phase='done';}}}}}
 update(a,dt){if(this.routine?.update(a,dt))return true;const before=a.id===3?!!this.staffMeal?.consumed:false,result=super.update(a,dt);if(a.id===3&&!before&&this.staffMeal?.consumed)this.routine.ate(a);return result;}
 pose(a,time){if(a.routineRest)return a.textures.sit_00?'sit_00':a.textures.idle_00?'idle_00':'idle';return super.pose(a,time);}
 afterRender(){super.afterRender();this.routine?.render();}
};
})();
