/* V21: additional floors, a resident shopkeeper, physical shopping and leisure. */
(()=>{'use strict';const T=THREE,V=(x=0,y=0,z=0)=>new T.Vector3(x,y,z),$=s=>document.querySelector(s),newRooms=['home2','shop','shop2'],centers={home:0,cafe:14,bath:28,farm:42,arcade:56,home2:112,shop:128,shop2:144},doors={home:V(1.9,0,3.45),cafe:V(14,0,3.45),bath:V(28,0,3.3),farm:V(42,0,3.45),arcade:V(56,0,3.45),shop:V(128,0,4.2)},esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const Base=ChillCafe;window.ChillCafe=class extends Base{
 constructor(c){super(c);this.v21={v:1,records:{},sales:0};this.claims21=new Map();this.nextLeisure21=18;this.cart21=null;this.shopWalk21=null;this.spaces21=new ChillSpaces21(c);this.spaces21.town(this);this.installProducts21();this.installRoutes21();this.installMita21();this.installUI21();const idle=this.routine.idle.bind(this.routine);this.routine.idle=a=>a.key!=='mita'&&!a.activity21&&idle(a);const places=this.sleep20.places.bind(this.sleep20);this.sleep20.places=()=>[...places(),...this.spaces21.beds];const freeBed=this.sleep20.free.bind(this.sleep20);this.sleep20.free=(place,a)=>!(place.id==='shop2:bed0'&&a.key!=='mita')&&freeBed(place,a);const routeWindow=this.routine.window.bind(this.routine);this.routine.window=a=>a.key==='mita'?null:routeWindow(a);}
 say(a,index){const lines=ChillVoice21.greetings[a.key];return lines?lines[index%lines.length]:super.say(a,index);}
 installRoutes21(){const r=this.routes20,rects=r.rects.bind(r),inside=r.inside.bind(r),travel=r.travel.bind(r);r.rects=room=>{const x=centers[room];if(room==='home2')return[{id:'beds',minX:x-5,maxX:x-.95,minZ:-4.1,maxZ:-.85},{id:'desk',minX:x+.35,maxX:x+5,minZ:-4,maxZ:-2.25},{id:'tv',minX:x+2.05,maxX:x+5.15,minZ:1.8,maxZ:2.98}];if(room==='shop')return[{id:'shelves',minX:x-5.3,maxX:x+2.4,minZ:-3.3,maxZ:-2.05},{id:'counter',minX:x+.8,maxX:x+4.5,minZ:.65,maxZ:2.15},{id:'stairs',minX:x+4.3,maxX:x+5.8,minZ:-.5,maxZ:3.3}];if(room==='shop2')return[{id:'beds',minX:x-5,maxX:x-.9,minZ:-4.1,maxZ:-.85},{id:'books',minX:x+.5,maxX:x+4.1,minZ:-4.8,maxZ:-4},{id:'table',minX:x+.8,maxX:x+3.2,minZ:-.7,maxZ:1.7}];return rects(room);};r.inside=(p,room)=>newRooms.includes(room)?Math.abs(p.x-centers[room])<5.85&&p.z> -4.8&&p.z<4.8:inside(p,room);
 r.travel=(a,to,target)=>{if(!newRooms.includes(a.room)&&!newRooms.includes(to))return travel(a,to,target);return this.route21(a.room,a.pos,to,target);};}
 roomPoints21(room,enter){const x=centers[room];if(room==='home2'){const points=[V(5.6,0,3.05),...Array.from({length:12},(_,i)=>V(5.6,(i+1)*.24,2.9-i*.28)),V(107.3,0,3.8),V(108.7,0,3.8)];return enter?points:points.slice().reverse();}if(room==='shop2'){const points=[V(133,0,3.65),...Array.from({length:12},(_,i)=>V(133,(i+1)*.24,3-i*.28)),V(139.2,0,3.7),V(140.5,0,3.7)];return enter?points:points.slice().reverse();}return[doors[room]?.clone()||V(x,0,4.2)];}
 route21(from,pos,to,target){const r=this.routes20;if(from===to)return r.route(to,pos,target);let out=[],at=pos.clone(),groundFrom=from==='home2'?'home':from==='shop2'?'shop':from,groundTo=to==='home2'?'home':to==='shop2'?'shop':to;
  if(from==='home2'||from==='shop2'){const stairs=this.roomPoints21(from,false),first=r.route(from,at,stairs[0]);if(!first)return null;out.push(...first,...stairs.slice(1));at=stairs.at(-1).clone();out.push(V(at.x,0,4.65),V(doors[groundFrom].x,0,4.65),doors[groundFrom].clone());at=doors[groundFrom].clone();}
  if(groundFrom!==groundTo){const first=r.route(groundFrom,at,doors[groundFrom]);if(!first)return null;out.push(...first,V(doors[groundFrom].x,0,5.3),V(doors[groundTo].x,0,5.3),doors[groundTo].clone());at=doors[groundTo].clone();}
  if(to==='home2'||to==='shop2'){const stairs=this.roomPoints21(to,true);if(groundFrom===groundTo&&from===groundFrom){const first=r.route(from,at,doors[from]);if(!first)return null;out.push(...first);at=doors[from].clone();}out.push(V(at.x,0,4.65),V(stairs[0].x,0,4.65),...stairs);at=stairs.at(-1).clone();}
  const last=r.route(to,at,target);if(!last)return null;out.push(...last);for(let i=1;i<out.length;i++)if(out[i].distanceTo(out[i-1])>4&&(out[i].y>2||out[i-1].y>2))out[i].portal21=true;return out;
 }
 follow20(a,path,dt){if(path[0]?.portal21){a.pos.copy(path.shift());return !path.length;}const speed=a.speed;if(a.pos.z>4.4&&path[0]?.z>4.4)a.speed*=4;const done=super.follow20(a,path,dt);a.speed=speed;return done;}
 installMita21(){const c=this.c,a={id:6,key:'mita',name:'モブミータ',addedResident:true,pos:V(130.7,0,-.25),room:'shop',speed:1.2,state:'idle',action:'walk',timer:12,path:[],cafePath:[],cafeMode:null,cafeWait:90,done:{},cooldowns:{},speech:0,textures:{},scale:1.65,anchor:[.5,.94],hasAsset:false,npcPose:'idle',npcTime:0,phase:null,phases:[],phaseIndex:0,mita21:true};a.sprite=new T.Sprite(new T.SpriteMaterial({transparent:true,alphaTest:.04,depthWrite:false}));a.sprite.center.set(.5,.06);a.sprite.scale.set(1.65,1.65,1);a.sprite.visible=false;c.scene.add(a.sprite);a.sleepGroup=new T.Group();c.scene.add(a.sleepGroup);a.shadow=new T.Mesh(new T.CircleGeometry(.25,20),new T.MeshBasicMaterial({color:'#42644b',transparent:true,opacity:.17,depthWrite:false}));a.shadow.rotation.x=-Math.PI/2;c.scene.add(a.shadow);a.bubble=document.createElement('div');a.bubble.className='bubble';$('#labels').appendChild(a.bubble);a.effect=document.createElement('div');a.effect.className='bubble effect';a.effect.hidden=true;$('#labels').appendChild(a.effect);ChillContactDepth.install(a);c.actors.push(a);const b=document.createElement('button');b.dataset.actor='6';b.innerHTML='<span class="badge">M</span><span><b>モブミータ</b><small id="state6">お店の準備</small></span>';$('.residents').appendChild(b);b.onclick=()=>this.menu(a);const proxy=new T.Sprite(a.sprite.material.clone());proxy.center.set(.5,.06);proxy.scale.setScalar(1.25);this.town14.group.add(proxy);this.town14.residentProxies.push({a,sprite:proxy,last:a.pos.clone(),journey:null});
  const image=new Image();image.onload=()=>{a.mitaFrames=[];const rects=CHILL_MITA21.rects,walk=rects.slice(2,10),walkScale=Math.min(216/Math.max(...walk.map(r=>r[2])),228/Math.max(...walk.map(r=>r[3])));for(let i=0;i<16;i++){const cv=document.createElement('canvas');cv.width=cv.height=512;const cx=cv.getContext('2d');cx.scale(2,2);cx.imageSmoothingQuality='high';const rect=rects[i],w=rect[2],h=rect[3],s=i>=2&&i<=9?walkScale:Math.min(220/w,228/h);cx.drawImage(image,...rect,128-w*s/2,242-h*s,w*s,h*s);const tx=new T.CanvasTexture(cv);tx.magFilter=tx.minFilter=T.LinearFilter;tx.generateMipmaps=false;tx.colorSpace=T.SRGBColorSpace;a.mitaFrames.push(tx);a.textures[i]=tx;}a.textures.idle=a.mitaFrames[0];a.textures.sit=a.mitaFrames[12];a.hasAsset=true;a.lifeReady20=true;a.motion18Ready=false;a.sprite.material.map=a.mitaFrames[0];a.life20={sleepLie:[a.mitaFrames[14],a.mitaFrames[14]],sleepSeat:[a.mitaFrames[15],a.mitaFrames[15]]};proxy.material.map=a.mitaFrames[0];if(c.actors.every(a=>a.hasAsset))$('#dev').hidden=true;};image.src=CHILL_MITA21.url;}

 installUI21(){const b=document.createElement('button');b.dataset.room='shop';b.textContent='ショップ';b.onclick=()=>this.setView('shop');$('#roomSwitch').appendChild(b);this.toolbar21=document.createElement('aside');this.toolbar21.className='v21-toolbar';this.toolbar21.hidden=true;document.body.appendChild(this.toolbar21);this.targets21=this.spaces21.targets.map(t=>{const el=document.createElement('button');el.className='v21-target';el.textContent=t.label;el.hidden=true;el.onclick=()=>this.action21(t.action);document.body.appendChild(el);return{...t,el};});const f=this.spaces21.townShop,el=document.createElement('button');el.className='town-label';el.textContent='MOB SHOP';el.hidden=true;el.onclick=()=>this.townNavigation.confirm(f);document.body.appendChild(el);this.townLabels14.push({f,el});$('#modal').addEventListener('close',()=>{if(this.pcTimeout21)clearTimeout(this.pcTimeout21);});}
 setView(v){if(newRooms.includes(v)){if($('#modal').open||this.c.editing()||this.c.room.mobileEditor)return false;this.view=v;this.closeActivity();$('#farmToolbar').hidden=$('#arcadeToolbar').hidden=true;document.querySelectorAll('[data-room]').forEach(b=>b.classList.toggle('active',b.dataset.room===(v==='shop2'?'shop':v==='home2'?'home':v)));this.c.layout();return true;}return super.setView(v);}
 action21(action){if(['home','home2','shop','shop2'].includes(action)){this.setView(action);return;}if(action==='skate')return this.openPlay21('skate');if(action.startsWith('pc'))return this.pcMenu21(+action.slice(2));if(action.startsWith('product'))return this.product21(+action.slice(7));if(action==='checkout')return this.checkout21();if(action==='invite')return this.leisureMenu21();if(action==='browse')return this.shopMenu21();}
 menu(a){if(a.key==='mita'){this.c.speak(a,this.say(a,(this.mitaGreeting21=(this.mitaGreeting21||0)+1)%6),6,true);this.c.modal(a.name,'<p>いらっしゃいませ！ MOB SHOPの2階に住んでいます。たくさん見て行ってくださいね♪</p><div class="v21-checkout"><button data-mita-shop>お店へ</button><button data-mita-bag>バッグ・贈り物</button><button data-mita-room>2階のお部屋へ</button></div>');$('[data-mita-shop]').onclick=()=>{$('#modal').close();this.setView('shop');};$('[data-mita-bag]').onclick=()=>this.bagMenu(6);$('[data-mita-room]').onclick=()=>{$('#modal').close();this.setView('shop2');};return;}return super.menu(a);}
 eligibleArcade(a){return a.key!=='mita'&&!a.activity21&&super.eligibleArcade(a);}
 eligibleBag(a){return !a.activity21&&super.eligibleBag(a);}
 visit(a){if(a.activity21||newRooms.includes(a.room))return false;return super.visit(a);}
 leisureAvailable21(a){return a.key!=='mita'&&a.id!==3&&!a.activity21&&!a.rest20&&!a.transit20&&!a.townAction19&&!a.phase&&!a.path?.length&&!a.cafePath?.length&&!a.cafeMode&&!a.bathMode&&!a.arcadeMode&&!a.bagAnimation&&a.state==='idle'&&this.routine.window(a)?.type!=='sleep';}
 startLeisure21(a,slot){if(!this.leisureAvailable21(a)||this.claims21.has(slot))return false;const x=slot==='pc0'?113.55:slot==='pc1'?115.7:114.9,target=slot.startsWith('pc')?V(x,0,-1.6):V(x,0,3.6),path=this.route21(a.room,a.pos,'home2',target);if(!path)return false;this.claims21.set(slot,a.id);a.activity21={slot,kind:slot.startsWith('pc')?['search','tube','game'][(a.done.pc21||0)%3]:'console',path,phase:'walk',origin:a.room,time:0,room:'home2',target};a.path=[];a.cafePath=[];a.state='idle';this.c.speak(a,a.key==='nekokoo'?'オラも2階で遊ぶんだぞ！':this.say(a,1),5,true);return true;}
 leisureMenu21(){this.c.modal('2階で一緒に過ごす','<p>空いているPCやMOB PLAYを、住民に自由に使ってもらえます。</p>'+this.c.actors.filter(a=>a.key!=='mita'&&a.id!==3).map(a=>'<button data-leisure-id="'+a.id+'" '+(!this.leisureAvailable21(a)?'disabled':'')+'>'+esc(a.name)+'を誘う</button>').join('')+'<p data-leisure-status></p>');document.querySelectorAll('[data-leisure-id]').forEach(b=>b.onclick=()=>{const slot=['pc0','pc1','console'].find(s=>!this.claims21.has(s));if(slot&&this.startLeisure21(this.c.actors[+b.dataset.leisureId],slot))$('#modal').close();else $('[data-leisure-status]').textContent='いまは席か通り道が空いていません。';});}
 pcMenu21(index){const screen=this.spaces21.screens[index];this.c.modal('MOB DESK '+(index+1),'<div class="v21-pc"><h3>きょう、何して遊ぶ？</h3><button data-pc-mode="search">検索</button><button data-pc-mode="tube">MOB TUBE</button><button data-pc-mode="game">ゲーム</button><div data-pc-content></div></div>');const show=mode=>{screen.mode=mode;const body=$('[data-pc-content]');if(mode==='search'){body.innerHTML='<label>箱庭の中を検索<input data-pc-query placeholder="ダンス・お店・ゲーム"></label><button data-pc-search>検索</button><p data-pc-results></p>';$('[data-pc-search]').onclick=()=>{$('[data-pc-results]').textContent='検索結果：MOB TUBEのダンス教室 ／ MOB SHOPの新しい小物 ／ GO GO モブくん！';};}else if(mode==='tube'){body.innerHTML='<h3>MOB TUBE · 今日のダンス</h3><canvas data-tube21 width="480" height="280" style="width:100%;background:#89a69d;border-radius:12px"></canvas><p>ステップ、ジャンプ、くるり！住民たちも一緒に楽しんでいます。</p>';const a=this.c.actors.find(a=>this.claims21.get('pc'+index)===a.id);if(a)this.c.speak(a,this.say(a,4),5,true);}else{body.innerHTML='<p>MOB PLAYのゲームで遊ぼう。</p><button data-pc-play>GO GO モブくん！</button>';$('[data-pc-play]').onclick=()=>this.openPlay21('skate');}};document.querySelectorAll('[data-pc-mode]').forEach(b=>b.onclick=()=>show(b.dataset.pcMode));show(screen.mode);}
 installProducts21(){this.products21().forEach((item,i)=>{const t=this.spaces21.targets.find(t=>t.action==='product'+i);if(!t)return;t.model.clear();new T.TextureLoader().load(item.url,tx=>{tx.colorSpace=T.SRGBColorSpace;const sprite=new T.Sprite(new T.SpriteMaterial({map:tx,transparent:true,depthWrite:false}));sprite.scale.set(.85,.85,1);sprite.position.y=.42;t.model.add(sprite);});});}
 products21(){return CHILL_KEYCHAINS.slice(0,6);}
 price21(item){return({R:4,SR:8,SSR:16,UR:28})[item.rarity]||4;}
 shopMenu21(){this.c.modal('MOB SHOP','<p>棚から商品を1つ手に取り、レジへ進んでお会計。ガチャのコレクションも、選んで買えます。</p><div class="v21-shop-grid">'+this.products21().map((p,i)=>'<article class="v21-product">'+this.itemIcon(p.id)+'<b>'+esc(p.name||p.id)+'</b><p>♥ '+this.price21(p)+'</p><button data-product21="'+i+'">棚へ行く</button></article>').join('')+'</div>');document.querySelectorAll('[data-product21]').forEach(b=>b.onclick=()=>{const i=+b.dataset.product21;$('#modal').close();this.product21(i);});}
 product21(index){if(this.shopWalk21)return;const item=this.products21()[index];if(!item)return;this.c.modal(item.name||item.id,'<div class="v21-product">'+this.itemIcon(item.id)+'<p>♥ '+this.price21(item)+'</p></div><p>この商品を棚から手に取りますか？ お会計まではハートを使いません。</p><button data-take21>商品を取る</button>');$('[data-take21]').onclick=()=>{$('#modal').close();const target=this.spaces21.targets.find(t=>t.action==='product'+index);this.cart21={id:item.id,index,price:this.price21(item),stage:'shelf'};this.startShopWalk21(target.approach?.clone()||V(target.point.x,0,-1.2),'take');};}
 avatar21(){if(this.shopAvatar21)return this.shopAvatar21;const g=new T.Group();g.name='shop-player-v21';this.c.scene.add(g);const body=new T.Mesh(new T.CylinderGeometry(.25,.28,.65,12),new T.MeshStandardMaterial({color:'#415e66'}));body.position.y=.55;g.add(body);const head=new T.Mesh(new T.SphereGeometry(.28,16,12),new T.MeshStandardMaterial({color:'#202a30'}));head.position.y=1.05;g.add(head);for(const x of [-.14,.14]){const glass=new T.Mesh(new T.TorusGeometry(.11,.022,6,16),new T.MeshBasicMaterial({color:'#fff6d4'}));glass.position.set(x,1.08,.25);g.add(glass);}const parcel=new T.Mesh(new T.BoxGeometry(.42,.4,.28),new T.MeshStandardMaterial({color:'#dbb15e'}));parcel.position.set(0,.65,.35);parcel.visible=false;g.add(parcel);g.userData.parcel=parcel;g.position.set(128,0,4.2);this.shopAvatar21=g;return g;}
 startShopWalk21(target,phase){const avatar=this.avatar21(),path=this.routes20.route('shop',avatar.position,target);if(!path){this.c.cafe?.c?.toast?.('通り道を確認してください。');return false;}this.shopWalk21={path,phase,time:0};return true;}
 checkout21(){if(!this.cart21){this.shopMenu21();return;}if(this.shopWalk21)return;if(this.cart21.stage!=='held'&&this.cart21.stage!=='register')return;if(this.cart21.stage==='register'){this.checkoutMenu21();return;}this.startShopWalk21(V(129.8,0,2.9),'checkout');}
 checkoutMenu21(){const cart=this.cart21;if(!cart)return;const item=this.products21().find(p=>p.id===cart.id);this.c.speak(this.c.actors[6],'ありがとうございます♪ お会計はこちらです。',5,true);this.c.modal('MOB SHOP · お会計',this.itemIcon(cart.id)+'<p>'+esc(item.name||item.id)+'　♥ '+cart.price+'</p><p>所持ハート：'+this.wallet.balance+'</p><div class="v21-checkout"><button data-buy21>購入してバッグに入れる</button><button data-return21>棚へ戻す</button></div><p data-buy-status role="status"></p>');$('[data-buy21]').onclick=()=>{const result=this.buy21();if(result.ok){$('[data-buy-status]').textContent='購入しました。バッグに入りました！';$('[data-buy21]').disabled=true;$('[data-return21]').disabled=true;this.c.speak(this.c.actors[6],'ありがとうございます♪ また来てくださいね♪',6,true);}else $('[data-buy-status]').textContent=result.reason==='hearts'?'ハートが足りません。':result.reason==='full'?'バッグに空きがありません。':'保存できません。商品とハートは変更していません。';};$('[data-return21]').onclick=()=>{this.cart21=null;this.avatar21().userData.parcel.visible=false;$('#modal').close();};}
 buy21(){const cart=this.cart21;if(!cart||cart.stage!=='register')return{ok:false,reason:'no-item'};const oldSales=this.v21.sales;const result=this.collections.transaction(()=>{const item=this.products21().find(p=>p.id===cart.id);if(!item||cart.price!==this.price21(item))return{ok:false,reason:'invalid-item'};if(this.wallet.balance<cart.price)return{ok:false,reason:'hearts'};if(!this.collections.canAdd('player',cart.id))return{ok:false,reason:'full'};this.wallet.balance-=cart.price;this.collections.change('player',cart.id,1);this.collections.state.collection[cart.id]=true;this.v21.sales++;return{};});if(!result.ok)this.v21.sales=oldSales;else{this.cart21=null;this.avatar21().userData.parcel.visible=false;}return result;}
 raceMenu(){this.c.modal('MOB KART · リーフサーキット','<p>起伏のあるS字コースを2周！ 左右操作でラインを選び、ドリフトを離して加速。アイテムはダッシュ・シールド・スロー波。</p><p>1回 ♥ '+CHILL_EXPANSION_CONFIG.arcade.playerPrices.race+'</p><button data-kart21>プレイヤーとして遊ぶ</button>'+(this.raceRun||this.raceInvitation?'<button data-watch21>住民のレースを見る</button>':'')+'<p data-kart-status></p>');if($('[data-watch21]'))$('[data-watch21]').onclick=()=>super.raceView();$('[data-kart21]').onclick=()=>{const r=this.collections.begin('race','player','race21',[]);if(!r.ok){$('[data-kart-status]').textContent=this.arcadeError(r.reason);return;}this.openPlay21('kart',r.id);};}
 openPlay21(mode,session=null){if(this.play21)return;this.play21=new ChillPlay21(this,mode,session);}
 update(a,dt){if(a.id===0){this.tick21(dt);if(a.activity21){this.routine?.plan();this.arcadeTick(dt);}}if(a.key==='mita'){this.updateMita21(a,dt);return true;}if(a.activity21){this.updateLeisure21(a,dt);return true;}return super.update(a,dt);}
 tick21(dt){if(!this.spaces21)return;this.nextLeisure21-=dt;if(this.nextLeisure21<=0&&!$('#modal').open){this.nextLeisure21=35;const available=this.c.actors.filter(a=>this.leisureAvailable21(a));const slot=['pc0','pc1','console'].find(s=>!this.claims21.has(s));if(available.length&&slot)this.startLeisure21(available[Math.floor(this.clock14)%available.length],slot);}const walk=this.shopWalk21;if(walk){const avatar=this.avatar21(),target=walk.path[0];if(target){const d=avatar.position.distanceTo(target);avatar.position.lerp(target,Math.min(1,dt*3/(d||1)));if(d<.05)walk.path.shift();}else{walk.time+=dt;if(walk.time<.55){avatar.userData.parcel.visible=walk.phase==='take';avatar.userData.parcel.position.y=.65+Math.sin(walk.time/.55*Math.PI)*.2;}else{avatar.userData.parcel.position.y=.65;this.shopWalk21=null;if(this.cart21){this.cart21.stage=walk.phase==='take'?'held':'register';if(walk.phase==='checkout'&&this.view==='shop'&&!$('#modal').open)this.checkoutMenu21();}}}}}
 updateLeisure21(a,dt){const s=a.activity21;a.speech=Math.max(0,a.speech-dt);if(s.phase==='walk'||s.phase==='return'){if(this.follow20(a,s.path,dt)){if(s.phase==='return'){a.room=s.origin;delete a.activity21;a.timer=8;a.pos.y=0;return;}a.room=s.room;s.phase='use';s.time=0;a.pos.y=.57;this.c.speak(a,a.key==='nekokoo'?'オラ、これが楽しいんだぞ！':this.say(a,4),5,true);a.done.pc21=(a.done.pc21||0)+1;}return;}s.time+=dt;if(s.slot.startsWith('pc'))this.spaces21.screens[+s.slot.slice(2)].mode=s.kind;if(s.time>24||this.routine.hour>=22||this.routine.hour<6){this.claims21.delete(s.slot);a.pos.y=0;const landing=this.routes20.landing(s.origin,a)||doors[s.origin],path=this.route21(a.room,a.pos,s.origin,landing);if(path){s.phase='return';s.path=path;}else{s.time=23;}this.c.save();}}
 updateMita21(a,dt){a.speech=Math.max(0,a.speech-dt);if(!a.hasAsset)return;const night=this.routine.hour>=22||this.routine.hour<6;let s=a.mitaState21;if(!s){a.mitaState21={phase:'idle',time:8};s=a.mitaState21;}if(s.path?.length){this.follow20(a,s.path,dt);if(!s.path.length){a.room=s.room;s.phase=s.next||'idle';s.time=0;if(s.phase==='sleep')a.pos.copy(this.spaces21.beds.find(b=>b.id===s.bed).point);}return;}if(s.phase==='sleep'){if(!night){const bed=this.spaces21.beds.find(b=>b.id===s.bed);if(this.sleep20.claims.get(s.bed)===a.id)this.sleep20.claims.delete(s.bed);a.pos.copy(bed?.entry||V(140,0,-.6));s.phase='reading';s.time=0;}return;}s.time+=dt;if(night){const bed=this.spaces21.beds.find(b=>b.room==='shop2'&&(!this.sleep20.claims.has(b.id)||this.sleep20.claims.get(b.id)===a.id));if(!bed)return;const path=this.route21(a.room,a.pos,'shop2',bed.entry);if(path){this.sleep20.claims.set(bed.id,a.id);a.mitaState21={phase:'walk',path,room:'shop2',next:'sleep',bed:bed.id,time:0};}return;}if(!night&&a.room==='shop2'&&s.time>18){const path=this.route21('shop2',a.pos,'shop',V(130.7,0,-.25));if(path)a.mitaState21={phase:'walk',path,room:'shop',next:'idle',time:0};return;}if(s.time>15&&a.room==='shop'){s.time=0;const n=(this.mitaWalk21=(this.mitaWalk21||0)+1),target=n%2?V(125.5,0,-1.25):V(130.7,0,-.25),path=this.routes20.route('shop',a.pos,target);if(path)a.mitaState21={phase:'walk',path,room:'shop',next:n%2?'shelf':'idle',time:0};if(this.view==='shop')this.c.speak(a,this.say(a,n%6),5,true);}}
 renderExtraActor(a){if(a.key==='mita'){a.sprite.visible=false;return;}return super.renderExtraActor(a);}
 walkingTexture20(a,h,d){if(a.key==='mita'&&a.mitaFrames){const right=V().setFromMatrixColumn(this.c.camera.matrixWorld,0),front=V().setFromMatrixColumn(this.c.camera.matrixWorld,2);right.y=front.y=0;right.normalize();front.normalize();const heading=h.clone();heading.y=0;heading.normalize();const x=heading.dot(right),z=heading.dot(front);let direction=Math.abs(x)>Math.abs(z)?x<0?'left':'right':z<0?'back':'front';if(Math.abs(Math.abs(x)-Math.abs(z))<.12&&a.walkDirection22)direction=a.walkDirection22;a.walkDirection22=direction;const base={front:2,left:4,right:6,back:8}[direction];return a.mitaFrames[base+Math.floor(d/.32)%2];}return super.walkingTexture20(a,h,d);}

 visualRoom21(a){if(a.pos.x>138)return 'shop2';if(a.pos.x>121&&a.pos.z<4.8)return 'shop';if(a.pos.x>104&&a.pos.z<4.8)return 'home2';if(a.pos.x>4.2&&a.pos.x<6.5&&a.pos.z<4.8)return'home';return a.room;}
 renderNewActor21(a){const room=this.visualRoom21(a),visible=this.view===room&&a.pos.z<4.8;a.sprite.visible=visible;a.shadow.visible=visible&&a.pos.y<.1;a.shadow.position.set(a.pos.x,.07,a.pos.z);a.sprite.position.copy(a.pos);a.sprite.scale.setScalar(a.key==='tetsu'?1.32:a.scale||1.65);a.sprite.center.set(.5,.06);const path=a.activity21?.path||a.shopVisit22?.path||a.mitaState21?.path;const moving=!!path?.length;if(a.key==='mita'&&a.mitaFrames){let frame=moving?null:a.mitaState21?.phase==='sleep'?14:a.mitaState21?.phase==='shelf'?10:a.mitaState21?.phase==='reading'?12:a.speech>0?1:0;a.sprite.material.map=frame===null?this.walkingTexture20(a,a.heading||V(1,0,0),a.walkDistance18||0):a.mitaFrames[frame];if(frame===14){a.sprite.position.y=.85;a.sprite.scale.set(2,2,1);}}else if(moving){const tx=this.walkingTexture20(a,a.heading||V(1,0,0),a.walkDistance18||0);if(tx)a.sprite.material.map=tx;}else if(a.activity21?.phase==='use'){a.sprite.material.map=a.motion18?.frames[13]||a.textures.sit||a.textures.sit_00||a.sprite.material.map;}const p=a.pos.clone().add(V(0,1.8,0)).project(this.c.camera);a.bubble.style.left=(p.x*.5+.5)*innerWidth+'px';a.bubble.style.top=(-p.y*.5+.5)*innerHeight+'px';a.bubble.style.opacity=visible&&a.speech>0?1:0;a.effect.style.opacity=0;$('#state'+a.id).textContent=a.key==='mita'?(a.mitaState21?.phase==='sleep'?'2階でおやすみ':moving?'お店を見回り':'MOB SHOPの店主'):moving?'階段・お部屋へ移動':a.activity21?.kind==='tube'?'MOB TUBEのダンス':a.activity21?.kind==='search'?'PCで調べもの':'ゲームを楽しむ';}
 afterRender(){super.afterRender();if(!this.spaces21)return;this.spaces21.update(this.clock14,this);const tube=document.querySelector('[data-tube21]');if(tube){const ctx=tube.getContext('2d'),frame=this.c.actors[0].textures['turnDance_'+String(Math.floor(performance.now()/110)%16).padStart(2,'0')];ctx.fillStyle='#91b6a3';ctx.fillRect(0,0,480,280);ctx.fillStyle='#efe1b2';ctx.fillRect(0,224,480,56);if(frame?.image)ctx.drawImage(frame.image,110,5,256,256);ctx.fillStyle='#fff8da';ctx.font='bold 22px sans-serif';ctx.fillText('MOB TUBE  /  DANCE',18,30);}for(const a of this.c.actors){if(a.activity21||a.key==='mita')this.renderNewActor21(a);if(a.rest20&&newRooms.includes(a.rest20.place.room)&&a.rest20.phase==='sleep'){a.sprite.visible=false;if(a.restPlane20)a.restPlane20.visible=this.view===a.rest20.place.room;if(a.restSprite20)a.restSprite20.visible=this.view===a.rest20.place.room&&a.rest20.place.kind==='seat';}const proxy=this.town14.residentProxies.find(p=>p.a===a);if(proxy&&a.activity21)proxy.sprite.visible=false;if(proxy&&a.key==='mita')proxy.sprite.visible=false;}
  if(this.shopAvatar21)this.shopAvatar21.visible=this.view==='shop'&&!!(this.cart21||this.shopWalk21);const active=['home','home2','shop','shop2'].includes(this.view)&&!$('#modal').open;this.toolbar21.hidden=!active;const layout=this.view+'|'+(this.cart21?.stage||'')+'|'+!!this.shopWalk21;if(active&&layout!==this.toolbarMode21){this.toolbarMode21=layout;const buttons=this.view==='home'?[['home2','階段で2階へ']]:this.view==='home2'?[['home','1階へ'],['invite','住民を誘う'],['skate','MOB PLAY']]:this.view==='shop'?[['browse','商品を見る'],['checkout',this.shopWalk21?'移動中…':this.cart21?'商品を持ってレジへ':'レジ'],['shop2','2階へ']]:[['shop','お店へ戻る']];this.toolbar21.innerHTML=buttons.map(([a,t])=>'<button data-v21-action="'+a+'">'+t+'</button>').join('');this.toolbar21.querySelectorAll('button').forEach(b=>b.onclick=()=>this.action21(b.dataset.v21Action));}
  for(const t of this.targets21){if(t.action.startsWith('product')){t.el.hidden=true;continue;}t.el.hidden=this.view!==t.room||$('#modal').open||(innerWidth<600&&t.action.startsWith('product')&&Number(t.action.slice(7))%2===1);if(t.el.hidden)continue;const p=t.point.clone().project(this.c.camera);t.el.hidden=Math.abs(p.x)>.95||Math.abs(p.y)>.9||p.z>1;if(!t.el.hidden){t.el.style.left=Math.max(58,Math.min(innerWidth-58,(p.x*.5+.5)*innerWidth))+'px';t.el.style.top=(-p.y*.5+.5)*innerHeight+'px';}}
 }
 serialize(){return{...super.serialize(),expansion21:this.v21?structuredClone(this.v21):{v:1,records:{},sales:0}};}
 restore(raw){super.restore(raw);if(!this.spaces21)return;const s=raw?.expansion21;this.v21={v:1,records:{},sales:Number.isSafeInteger(s?.sales)?Math.max(0,s.sales):0};for(const mode of ['skate','kart'])if(Number.isFinite(s?.records?.[mode]?.time)&&s.records[mode].time>0)this.v21.records[mode]={...s.records[mode]};this.claims21.clear();this.cart21=this.shopWalk21=null;for(const a of this.c.actors){delete a.activity21;if(a.key==='mita'){a.room='shop';a.pos.set(130.7,0,-.25);a.mitaState21={phase:'idle',time:0};}else if(newRooms.includes(a.room)){a.room='home';a.pos.copy(this.routes20.landing('home',a)||V(0,0,2));}}}
};
})();
