(()=>{'use strict';
const $=s=>document.querySelector(s),clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),v3=(x,y,z)=>new THREE.Vector3(x,y,z),ease=t=>t*t*(3-2*t),lerp=(a,b,t)=>a.clone().lerp(b,t);
const scene=new THREE.Scene();scene.background=new THREE.Color('#ece7dc');let renderer;try{renderer=new THREE.WebGLRenderer({antialias:true})}catch{$('#dev').textContent='WebGL対応ブラウザで開いてください。';return}renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;$('#world').appendChild(renderer.domElement);
let viewportWidth=innerWidth,viewportHeight=innerHeight;const camera=new THREE.PerspectiveCamera(36,1,.1,100);let az=.7,el=.79,zoom=1,view=0;scene.add(new THREE.HemisphereLight(0xfff8de,0x8d9c95,2.15));const sun=new THREE.DirectionalLight(0xffead0,2.6);sun.position.set(-3,9,5);sun.castShadow=true;sun.shadow.mapSize.set(1536,1536);Object.assign(sun.shadow.camera,{left:-9,right:9,top:9,bottom:-9,near:.1,far:30});sun.shadow.bias=-.001;scene.add(sun);const lamp=new THREE.PointLight(0xffc381,8,10,2);lamp.position.set(-4.5,1.7,2.85);scene.add(lamp);
const room=new ChillRoom(scene);const actions={
 oven:{name:'焼き加減をみる',icon:'♨',resource:'oven'},walk:{name:'おさんぽ',icon:'↝',pose:'walk'},sit:{name:'ソファでひと休み',icon:'♧',resource:'sofa'},nap:{name:'ベッドでおひるね',icon:'☾',resource:'bed'},eat:{name:'どら焼きを食べる',icon:'◒',resource:'table'},read:{name:'本を読んで戻す',icon:'▤',resource:'shelf'},window:{name:'窓をながめる',icon:'☀'},clean:{name:'おそうじ',icon:'✧'},plant:{name:'植物に水やり',icon:'♧',resource:'plant'},dance:{name:'音楽とダンス',icon:'♫'},chat:{name:'ふたりでお話',icon:'♡',resource:'chat'},dj:{name:'ターンテーブル',icon:'◎',resource:'deck'},joy:{name:'よろこぶ',icon:'✿'}
};
const lines={oven:['いい香りでやんす～。','こんがり焼くであります！'],walk:['いい日でやんす。','探検であります！'],sit:['ふかふかやんす～。','僕もひと息であります。'],nap:['おやすみでやんす…。','少し休むであります。'],eat:['どら焼き、おいしいやんす！','僕、どら焼きが大好きであります！'],read:['続きが気になるでやんす。','なるほどであります！'],window:['きれいな空やんす～。','いい景色であります！'],clean:['ぴかぴかでやんす！','僕にお任せであります！'],plant:['元気に育つでやんす。','お水の時間であります！'],dance:['踊るでやんす！','ノリノリであります！'],chat:['いっしょだと楽しいやんす。','僕も楽しいであります！'],dj:['いい音でやんす～。','僕の選曲であります！'],joy:['ほぅ～！','うれしいであります！']};
let kitchen;let elapsed=0,paused=false,speed=1,sound=false,history=[],food=null,foodSerial=0,placedCount=0,consumedCount=0,pendingLayout=null,mode='observe',selected=0,draftLayout=0,toastTime=0,saveElapsed=0,lastBeat=-1;
const reservations=new Map();const actors=[{id:0,key:'denden',name:'モブデンデン',pos:v3(-.8,0,1.4),speed:1.15},{id:1,key:'pink',name:'モブピンク',pos:v3(.8,0,1.4),speed:1.32}];
function devTexture(id){let c=document.createElement('canvas');c.width=32;c.height=40;let ctx=c.getContext('2d');ctx.fillStyle=id?'#eaa6bc':'#ddc282';ctx.fillRect(7,7,18,23);ctx.fillRect(4,16,4,12);ctx.fillRect(24,16,4,12);ctx.fillRect(8,29,6,9);ctx.fillRect(19,29,6,9);ctx.fillStyle='#526459';ctx.fillRect(9,13,5,5);ctx.fillRect(18,13,5,5);ctx.fillStyle='#fff';ctx.font='6px monospace';ctx.fillText('DEV',10,26);let t=new THREE.CanvasTexture(c);t.magFilter=t.minFilter=THREE.NearestFilter;t.generateMipmaps=false;t.colorSpace=THREE.SRGBColorSpace;return t;}
actors.forEach(a=>{Object.assign(a,{state:'idle',action:'walk',timer:2+a.id*2,path:[],queue:null,phases:[],phaseIndex:0,done:{},cooldowns:{},lastAction:null,speech:0,textures:{},scale:1.4,anchor:[.5,0],hasAsset:false});a.sprite=new THREE.Sprite(new THREE.SpriteMaterial({map:devTexture(a.id),alphaTest:.06,transparent:true,depthWrite:false}));a.sprite.scale.set(1.12,1.4,1);a.sprite.center.set(.5,0);scene.add(a.sprite);a.sleepGroup=new THREE.Group();a.sleepPlane=new THREE.Mesh(new THREE.PlaneGeometry(1,1),new THREE.MeshBasicMaterial({transparent:true,alphaTest:.06,depthWrite:false,side:THREE.DoubleSide}));a.sleepPlane.rotation.x=-Math.PI/2;a.sleepGroup.add(a.sleepPlane);scene.add(a.sleepGroup);a.sleepGroup.visible=false;a.shadow=new THREE.Mesh(new THREE.CircleGeometry(.25,24),new THREE.MeshBasicMaterial({color:0x54694b,opacity:.18,transparent:true,depthWrite:false}));a.shadow.rotation.x=-Math.PI/2;scene.add(a.shadow);a.bubble=document.createElement('div');a.bubble.className='bubble';$('#labels').appendChild(a.bubble);a.effect=document.createElement('div');a.effect.className='bubble effect';$('#labels').appendChild(a.effect);loadCharacter(a);});
function loadCharacter(a){const packet=window.CHARACTER_ASSETS?.[a.key];if(!packet)return;const poses=typeof packet==='string'?{idle:packet}:packet.poses||packet;a.meta=packet.meta||{};const aliases={bed_mount:'climb',book_reach:'reach',book_hold:'hold',book_read:'read',book_return:'book_return',dorayaki_take:'food_take',dorayaki_eat:'eat',cheer_cheeks:'joy',cheer_hop:'hop'};for(let [pose,url]of Object.entries(poses)){if(typeof url!=='string')continue;new THREE.TextureLoader().load(url,t=>{t.magFilter=t.minFilter=THREE.NearestFilter;t.generateMipmaps=false;t.colorSpace=THREE.SRGBColorSpace;a.textures[pose]=t;if(aliases[pose])a.textures[aliases[pose]]=t;if(pose==='idle'){a.hasAsset=true;a.anchor=a.meta.footAnchor||[.5,.921875];let height=.65*t.image.height;try{let c=document.createElement('canvas');c.width=t.image.width;c.height=t.image.height;let cx=c.getContext('2d');cx.drawImage(t.image,0,0);let data=cx.getImageData(0,0,c.width,c.height).data,lo=c.height,hi=0;for(let y=0;y<c.height;y++)for(let x=0;x<c.width;x++)if(data[(y*c.width+x)*4+3]>32){lo=Math.min(lo,y);hi=Math.max(hi,y)}if(hi>lo)height=hi-lo+1}catch{}a.scale=1.35*t.image.height/height;}if(actors.every(a=>a.hasAsset))$('#dev').hidden=true;},undefined,()=>toast('一部の画像を読み込めませんでした。'));}}
const book=new THREE.Group();room.box(book,0,0,0,.38,.055,.28,'#72958a');room.box(book,0,.037,0,.34,.035,.255,'#f7efd9');scene.add(book);
const snack=new THREE.Group();room.cyl(snack,0,0,0,.155,.155,.07,'#7e4931');room.cyl(snack,0,.05,0,.17,.15,.065,'#c89046');room.cyl(snack,0,-.05,0,.15,.17,.055,'#d4a356');scene.add(snack);snack.visible=false;
const broom=new THREE.Group();room.box(broom,0,.45,0,.025,.85,.025,'#ae8c5f');room.box(broom,0,.06,0,.25,.13,.08,'#ccbc91');scene.add(broom);broom.visible=false;
const can=new THREE.Group();room.cyl(can,0,0,0,.11,.11,.21,'#91b6ac');let spout=room.box(can,-.26,0,0,.36,.045,.055,'#91b6ac');spout.rotation.z=-.3;scene.add(can);can.visible=false;
const drops=[];for(let i=0;i<7;i++){let d=new THREE.Mesh(new THREE.SphereGeometry(.02,6,6),new THREE.MeshBasicMaterial({color:'#95ccd1',transparent:true,opacity:.7}));scene.add(d);drops.push(d);d.visible=false;}
function speak(a,text,d=4){a.speech=d;a.bubble.replaceChildren();const name=document.createElement('small');name.textContent=a.name;a.bubble.append(name,document.createTextNode(text));}
function log(a,text){history.unshift({n:Math.floor(elapsed/60),text:(a?a.name+' · ':'')+text});history=history.slice(0,60);}
function toast(text){$('#toast').textContent=text;$('#toast').style.opacity=1;toastTime=4;}
// Snapped endpoints avoid the previous off-grid wandering failure. Search is 4-connected.
const grid=.2;function cell(x,z){return[Math.round((x+4.6)/grid),Math.round((z+3.6)/grid)]}function point(i,j){return v3(i*grid-4.6,0,j*grid-3.6)}
function nearest(p){let base=cell(p.x,p.z),best=null,dist=Infinity;for(let r=0;r<5;r++){for(let dx=-r;dx<=r;dx++)for(let dz=-r;dz<=r;dz++){let q=point(base[0]+dx,base[1]+dz);if(room.valid(q.x,q.z)&&q.distanceToSquared(p)<dist){best=q;dist=q.distanceToSquared(p)}}if(best)return best}return null;}
function route(from,to){let target=nearest(to);if(!target)return null;let st=cell(from.x,from.z),en=cell(target.x,target.z),key=p=>p.join(','),open=[st],cost=new Map([[key(st),0]]),came=new Map(),limit=3500;while(open.length&&limit--){open.sort((a,b)=>cost.get(key(a))+Math.abs(a[0]-en[0])+Math.abs(a[1]-en[1])-cost.get(key(b))-Math.abs(b[0]-en[0])-Math.abs(b[1]-en[1]));let cur=open.shift(),ck=key(cur);if(ck===key(en)){let result=[];while(ck!==key(st)){result.unshift(point(...cur));cur=came.get(ck);ck=key(cur)}if(result.length===0&&from.distanceTo(target)>.03)result.push(target);return result;}for(let [dx,dz]of [[1,0],[-1,0],[0,1],[0,-1]]){let n=[cur[0]+dx,cur[1]+dz],p=point(...n),nk=key(n);if(!room.valid(p.x,p.z))continue;let g=cost.get(ck)+1;if(!cost.has(nk)||g<cost.get(nk)){cost.set(nk,g);came.set(nk,cur);if(!open.some(t=>key(t)===nk))open.push(n)}}}return null;}
function targetFor(a,key){if(actions[key].resource&&actions[key].resource!=='chat')return room.socket(actions[key].resource,'entry');if(key==='window')return v3(-2.3,0,-3.12);if(key==='clean')return v3(-1.15,0,1.45);if(key==='dance')return v3(-1.65,0,2.05);if(key==='joy')return v3(-.4,0,.4);if(key==='chat')return v3(a.id?.65:0,0,.25);for(let i=0;i<80;i++){let p=nearest(v3(-4.4+Math.random()*8.8,0,-3.2+Math.random()*6.6));if(p&&p.distanceTo(a.pos)>1.3)return p;}return null;}
function canStart(a,key){if(!actions[key]||pendingLayout!==null)return false;let resource=actions[key].resource;if(resource&&reservations.has(resource)&&reservations.get(resource)!==a.id)return false;if(key==='oven'&&!kitchen?.batch)return false;if(key==='eat'&&(!food||food.state!=='placed'))return false;return true;}
function start(a,key,forced=false){if(!canStart(a,key)){if(forced)speak(a,key==='eat'?(a.id?'どら焼きを待つであります。':'どら焼き、待ってるでやんす。'):(a.id?'あとで使うであります！':'あとで使うでやんす。'));return false;}if(a.state!=='idle'){if(forced){a.queue=key;toast('今の行動を終えたら、'+actions[key].name+'。');return true;}return false;}let target=targetFor(a,key);if(!target)return false;let path=route(a.pos,target);if(!path)return false;a.action=key;a.path=path;a.state='moving';a.phaseIndex=0;a.blocked=0;a.lastAction=key;let r=actions[key].resource;if(r)reservations.set(r,a.id);if(key==='eat'){food.state='reserved';food.actor=a.id;}return true;}
function choose(a){let weights=a.id?{oven:1.3,walk:2,sit:1,nap:.7,eat:4,read:2,window:1.3,clean:3,plant:3,dance:2.5,chat:2,dj:2.5,joy:1}:{oven:1.3,walk:2,sit:3,nap:2.5,eat:5,read:3,window:2,clean:1,plant:1.5,dance:2,chat:2.5,dj:1.7,joy:1.3};let choices=Object.keys(actions).filter(k=>canStart(a,k)&&elapsed>=(a.cooldowns[k]||0));if(choices.length>1)choices=choices.filter(k=>k!==a.lastAction);let total=choices.reduce((v,k)=>v+weights[k],0),roll=Math.random()*total;for(let k of choices){roll-=weights[k];if(roll<=0){if(!start(a,k))a.timer=1;return;}}a.timer=1;}
function phase(name,duration,pose,point=null,extra={}){return{name,duration,pose,point,...extra};}
function phasesFor(a){let key=a.action,r=actions[key].resource,entry=r&&r!=='chat'?room.socket(r,'entry'):a.pos.clone(),walkTo=(name,p,d=1)=>phase(name,d,'walk',p);
 if(key==='oven')return[phase('焼き加減を見守る',4,'idle')];
 if(key==='sit')return[walkTo('腰をかける',room.socket('sofa','seat'),1.2),phase('くつろぎ中',9,'sit'),walkTo('ソファから降りる',entry,1.2)];
 if(key==='nap')return[phase('ねむくなって、あくび',1.6,'yawn'),phase('ベッドに乗る',1.1,'climb',room.socket('bed','edge'),{arc:.13}),walkTo('ベッド中央へ',room.socket('bed','center'),1.25),phase('すやすや',12,'sleep'),phase('起きる',.7,'sit'),walkTo('ベッドの端へ',room.socket('bed','edge'),1.2),phase('ベッドから降りる',1.1,'climb',entry,{arc:.12}),phase('起きて、のびのび',1.6,'stretch')];
 if(key==='read'){let reading=nearest(entry.clone().add(v3(-.3,0,.85)))||entry.clone();return[phase('本に手を伸ばす',.65,'reach'),phase('本を手に取る',1,'hold',null,{transfer:'book-in'}),phase('本を持って一歩下がる',.9,'hold',reading,{hold:'book',undock:true}),phase('読書中',9,'read',null,{hold:'book'}),phase('本棚へ戻る',.9,'hold',entry,{hold:'book',redock:true}),phase('本を棚に戻す',1,'book_return',null,{transfer:'book-out'}),phase('手を離す',.45,'idle')];}
 if(key==='eat'){let eating=nearest(entry.clone().add(v3(-.3,0,.85)))||entry.clone();return[phase('どら焼きに手を伸ばす',.65,'food_take'),phase('どら焼きを取る',1,'hold',null,{transfer:'food-in'}),phase('どら焼きを持って一歩下がる',.9,'hold',eating,{hold:'foodCarry'}),phase('どら焼きを食べる',5,'eat',null,{hold:'food'}),phase('ごちそうさま',1.3,'joy')];}
 if(key==='plant')return[phase('じょうろを構える',1,'hold'),phase('水やり中',7,'garden'),phase('じょうろを片付ける',.7,'idle')];
 if(key==='clean')return[phase('ほうきを持つ',.7,'hold'),phase('床をはく',8,'clean'),phase('お片付け',.7,'idle')];
 if(key==='dj')return[phase('盤に手を伸ばす',.8,'dj_a'),phase('選曲とミックス',9,'dj'),phase('音にうなずく',1,'idle')];
 if(key==='chat')return[phase('手を振ってごあいさつ',1.8,'wave'),phase('ふたりでおしゃべり',7.2,'chat')];
 if(key==='joy')return[phase('両手をほっぺに',1.2,'joy'),phase('ほぅ～！',1.1,'joy',null,{hop:Math.random()<.6}),phase('うれしい余韻',2,'joy')];
 return[phase(actions[key].name,key==='walk'?2:key==='dance'?9:8,key==='window'?'windowlook':key==='dance'?'music':'idle')];}
function enterPhase(a){let p=a.phases[a.phaseIndex];if(!p){finish(a);return;}a.phase=p;a.phaseTime=0;a.phaseFrom=a.pos.clone();if(p.name==='ごちそうさま')speak(a,a.id?'ごちそうさまであります！':'ほぅ～！ おいしかったやんす！');if(p.transfer==='book-in')a.transferFrom=room.socket('shelf','book');if(p.transfer==='book-out')a.transferFrom=book.position.clone();if(p.transfer==='food-in'){a.transferFrom=room.socket('table','food');if(food)food.state='held';}if(p.hold==='food')a.bites=0;}
function arrive(a){if(a.state==='staging'){a.state='ready';return;}a.state='acting';a.done[a.action]=(a.done[a.action]||0)+1;a.phases=phasesFor(a);a.phaseIndex=0;enterPhase(a);speak(a,lines[a.action][a.id]);log(a,actions[a.action].name);tone(a.id?660:440);if(a.action==='chat'){let other=actors[1-a.id];if(other.state==='idle'&&pendingLayout===null){let path=route(other.pos,targetFor(other,'chat'));if(path){other.action='chat';other.lastAction='chat';other.path=path;other.state='moving';other.joining=true;}}else speak(other,other.id?'聞いているであります！':'いいねでやんす～。',3);}}
function finish(a){let r=actions[a.action]?.resource;if(r&&reservations.get(r)===a.id)reservations.delete(r);if(a.action==='eat'&&food?.actor===a.id){if(food.state==='held'){consumedCount++;food=null;snack.visible=false;}else if(food)food.state='placed';}if(a.action==='read')book.position.copy(room.socket('shelf','book'));a.cooldowns[a.action]=elapsed+18;a.phase=null;a.state='idle';a.timer=1.1+Math.random()*2;a.joining=false;if(pendingLayout!==null)stageActor(a);else if(a.queue){let next=a.queue;a.queue=null;start(a,next,true);}}
function stageActor(a){if(a.state!=='idle')return;let target=v3(a.id?.7:0,0,1.45),path=route(a.pos,target);if(path){a.path=path;a.state='staging';}else{toast('配置変更の動線を確認できませんでした。');pendingLayout=null;room.clearPreview();}}
function updateActor(a,dt){a.speech=Math.max(0,a.speech-dt);if(a.state==='idle'){if(pendingLayout!==null){stageActor(a);return;}a.timer-=dt;if(a.timer<=0)choose(a);}else if(a.state==='moving'||a.state==='staging'){if(a.path.length){let target=a.path[0],d=a.pos.distanceTo(target);if(d<.03){a.pos.copy(target);a.path.shift();}else{a.heading=target.clone().sub(a.pos).normalize();a.pos.lerp(target,Math.min(1,a.speed*dt/d));}}else arrive(a);}else if(a.state==='acting'){a.phaseTime+=dt;let p=a.phase,u=clamp(a.phaseTime/p.duration,0,1);if(p.point){a.heading=p.point.clone().sub(a.phaseFrom).normalize();a.pos.copy(lerp(a.phaseFrom,p.point,ease(u)));if(p.arc)a.pos.y+=Math.sin(Math.PI*u)*p.arc;}if(p.hold==='food'&&u>=.92&&food?.actor===a.id){consumedCount++;food=null;snack.visible=false;}if(a.phaseTime>=p.duration){if(p.point)a.pos.copy(p.point);if(p.transfer==='book-out')book.position.copy(room.socket('shelf','book'));a.phaseIndex++;enterPhase(a);}}}
// Convert an actual sprite pixel to world space using the same camera-facing axes as THREE.Sprite.
function spriteAnchorWorld(a,anchor,depth=.012){let center=a.sprite.center,p=v3((anchor[0]-center.x)*a.sprite.scale.x,(1-anchor[1]-center.y)*a.sprite.scale.y,depth);if(a.sprite.material.rotation)p.applyAxisAngle(v3(0,0,1),a.sprite.material.rotation);return p.applyQuaternion(camera.quaternion).add(a.sprite.position);}
function hand(a,side=1){let actualPose=(a.drawPose==='clean'||a.drawPose==='garden')&&!a.textures[a.drawPose]?'hold':a.drawPose,anchor=a.meta?.handAnchors?.[actualPose]||a.meta?.handAnchors?.[a.phase?.pose]||a.meta?.handAnchor;if(anchor){let point=side===1?anchor:[a.sprite.center.x+(anchor[0]-a.sprite.center.x)*side,anchor[1]];return spriteAnchorWorld(a,point);}return a.pos.clone().add(v3(.19*side,.78,.12));}
// A sprite has no rigid 3D hand. Align its rendered contact pixel to the station, keeping its feet on the floor.
function groundedDock(a,target,anchor){const origin=a.sprite.position.clone(),offset=spriteAnchorWorld(a,anchor,0).sub(origin),ray=target.clone().sub(camera.position);let depth=(origin.y+offset.y-target.y)/ray.y;return target.clone().addScaledVector(ray,depth).sub(offset);}
function dockContact(a){a.contact=null;if(a.state!=='acting'||!a.hasAsset)return;let target,anchor,weight=1;
 if(a.action==='read'){if(a.phase?.hold==='book'&&!a.phase?.undock&&!a.phase?.redock)return;target=room.socket('shelf','book');anchor=a.meta?.handAnchors?.[a.phase?.pose==='book_return'?'book_return':'reach'];if(a.phase?.pose==='reach'||a.phase?.redock)weight=ease(clamp(a.phaseTime/a.phase.duration,0,1));if(a.phase?.pose==='idle'||a.phase?.undock)weight=1-ease(clamp(a.phaseTime/a.phase.duration,0,1));}
 if(a.action==='dj'){target=room.socket('deck',a.id?'hands_pink':'hands_denden');anchor=a.meta?.handAnchors?.[a.drawPose]||a.meta?.handAnchors?.dj_a;if(a.phaseIndex===0)weight=ease(clamp(a.phaseTime/a.phase.duration,0,1));if(a.phase?.pose==='idle')weight=1-ease(clamp(a.phaseTime/a.phase.duration,0,1));}
 if(!anchor||!target)return;let desired=groundedDock(a,target,anchor);if(!room.contactFloorValid(desired.x,desired.z,a.action==='dj'?'deck':'shelf')){a.contact={safe:false,target:target.toArray(),desiredFoot:desired.toArray()};return;}a.sprite.position.lerp(desired,weight);let actual=spriteAnchorWorld(a,anchor,0),ap=actual.clone().project(camera),tp=target.clone().project(camera);a.contact={safe:true,target:target.toArray(),actual:actual.toArray(),projectedErrorPx:Math.hypot((ap.x-tp.x)*innerWidth/2,(ap.y-tp.y)*innerHeight/2),depthDifference:actual.distanceTo(target),footY:a.sprite.position.y,weight};}
// Phase-local clocks pause/resume with the simulation; gestures never interrupt held props.
const lifeMotions={yawn:{frames:['yawn_1','yawn_2'],loop:false},stretch:{frames:['stretch_1','stretch_2'],loop:false},wave:{frames:['wave_1','wave_2'],fps:3,loop:true},music:{frames:['music_1','music_2'],fps:2,loop:true}};
function renderActor(a){let p=a.phase,moving=a.state==='moving'||a.state==='staging'||p?.pose==='walk',pose=p?.pose||'idle',flip=1;let frame=Math.floor(elapsed*7)%2+1;
 if(moving){let dir=a.heading||v3(0,0,1),right=dir.x*Math.cos(az)-dir.z*Math.sin(az),front=dir.x*Math.sin(az)+dir.z*Math.cos(az);let facing=Math.abs(right)>Math.abs(front)*.9?'side':front>=0?'front':'back';pose='walk_'+facing+'_'+frame;if(facing==='side'&&right<0)flip=-1;}else if(pose==='dj')pose=Math.floor(elapsed*3)%2?'dj_a':'dj_b';else if(lifeMotions[pose]){let m=lifeMotions[pose],n=m.loop?Math.floor(a.phaseTime*m.fps)%m.frames.length:Math.min(m.frames.length-1,Math.floor(clamp(a.phaseTime/p.duration,0,1)*m.frames.length));pose=m.frames[n];}else if(p?.hop&&a.textures.hop)pose='hop';
 let fallback=moving?(a.textures[frame===1?'walk':'walk2']||a.textures.walk):pose==='dj_a'||pose==='dj_b'?a.textures.dj||a.textures.hold:pose==='garden'||pose==='clean'?a.textures.hold:pose==='food_take'?a.textures.reach:pose==='dance'?a.textures.hop||a.textures.joy:pose==='windowlook'?a.textures.walk_back_1:null;let tex=a.textures[pose]||fallback||a.textures.idle;a.drawPose=pose;
 if(tex){a.sprite.material.map=tex;a.sprite.scale.set(flip*a.scale*tex.image.width/tex.image.height,a.scale,1);}let bob=moving||(p?.hold==='book'||p?.hold==='foodCarry')&&p?.point?Math.abs(Math.sin(elapsed*10))*.035:0;let hop=p?.hop?Math.sin(Math.PI*clamp(a.phaseTime/p.duration,0,1))*.35:0;if(pose==='dance')bob=Math.abs(Math.sin(elapsed*8))*.1;a.sprite.position.copy(a.pos);a.sprite.position.y+=(pose==='sit'||a.pos.y>.15?.005:.035)+bob+hop;
 const realSleep=pose==='sleep'&&!!a.textures.sleep;a.sprite.visible=!realSleep;a.sleepGroup.visible=realSleep;if(realSleep){let anchor=a.meta?.sleepAnchor||[.5,.5],w=a.scale*tex.image.width/tex.image.height,h=a.scale;a.sleepGroup.position.copy(a.pos);a.sleepGroup.position.y+=.006;a.sleepGroup.rotation.y=room.furniture.bed.group.rotation.y+Math.PI/2;a.sleepPlane.material.map=tex;a.sleepPlane.scale.set(w,h,1);a.sleepPlane.position.set((.5-anchor[0])*w,0,(.5-anchor[1])*h);}
 if(pose==='sleep'){a.sprite.center.set(.5,.35);a.sprite.material.rotation=.8;}else{let standing=a.hasAsset?a.anchor:[.5,1],seat=pose==='sit'&&a.hasAsset?(a.meta?.sitAnchor||[.5,.65]):standing;a.sprite.center.set(seat[0],1-seat[1]);a.sprite.material.rotation=pose==='dance'?Math.sin(elapsed*6)*.09:0;}
 dockContact(a);a.shadow.position.set(a.sprite.position.x,.067,a.sprite.position.z);a.shadow.visible=a.pos.y<.15;let projection=a.sprite.position.clone().add(v3(0,pose==='sleep'?.65:1.48,0)).project(camera),px=(projection.x*.5+.5)*viewportWidth,py=(-projection.y*.5+.5)*viewportHeight;const bw=a.bubble.offsetWidth,bh=a.bubble.offsetHeight,footerTop=document.querySelector('footer').getBoundingClientRect().top-document.body.getBoundingClientRect().top;a.bubble.style.left=clamp(px,bw/2+8,viewportWidth-bw/2-8)+'px';a.bubble.style.top=clamp(py,bh+8,Math.max(bh+8,footerTop-8))+'px';a.bubble.style.opacity=a.speech>0?1:0;a.effect.style.left=px+'px';a.effect.style.top=py+'px';a.effect.style.opacity=a.speech>0?0:1;a.effect.textContent=pose==='sleep'?'z z Z':pose==='dance'||pose.startsWith('music_')||pose.startsWith('dj')?'♫':pose==='joy'||pose==='hop'?'✿':pose==='chat'?'♡':'';$('#state'+a.id).textContent=a.state==='moving'?actions[a.action].name+'へ':a.state==='staging'||a.state==='ready'?'模様替えの準備':p?.name||'のんびり';}
 function renderProps(){const reader=actors.find(a=>a.state==='acting'&&a.action==='read');if(reader){let p=reader.phase,u=ease(clamp(reader.phaseTime/p.duration,0,1));if(p.transfer==='book-in')book.position.copy(lerp(reader.transferFrom,hand(reader),u));else if(p.transfer==='book-out')book.position.copy(lerp(reader.transferFrom,room.socket('shelf','book'),u));else if(p.hold==='book')book.position.copy(hand(reader));else book.position.copy(room.socket('shelf','book'));book.rotation.set(0,p.hold==='book'?az:0,p.hold==='book'?-.18:0);}else{book.position.copy(room.socket('shelf','book'));book.rotation.set(0,0,0);}book.visible=true;
 snack.visible=!!food;if(food){let a=food.actor!==undefined?actors[food.actor]:null,p=a?.phase;snack.scale.setScalar(1);if(food.state==='held'&&a&&p){let u=clamp(a.phaseTime/p.duration,0,1);if(p.transfer==='food-in')snack.position.copy(lerp(a.transferFrom,hand(a),ease(u)));else{snack.position.copy(hand(a));if(p.hold==='food')snack.scale.setScalar(Math.max(.05,1-u*.95));}}else snack.position.copy(room.socket('table','food'));}
 let cleaner=actors.find(a=>a.phase?.pose==='clean'),gardener=actors.find(a=>a.phase?.pose==='garden'),dj=actors.find(a=>a.phase?.pose==='dj');broom.visible=!!cleaner;if(cleaner){let grip=hand(cleaner),angle=Math.sin(elapsed*5)*.13;broom.rotation.z=angle;let sy=Math.max(.12,(grip.y-.035)/(.62*Math.cos(angle)));broom.scale.set(1,sy,1);let localGrip=v3(0,.62*sy,0).applyAxisAngle(v3(0,0,1),angle);broom.position.copy(grip).sub(localGrip);}can.visible=!!gardener;for(let d of drops)d.visible=!!gardener;if(gardener){let water=room.socket('plant','water');can.position.copy(hand(gardener));can.rotation.z=-.62;can.updateMatrixWorld(true);let pour=can.localToWorld(v3(-.44,0,0));drops.forEach((d,i)=>{let t=(elapsed*1.6+i/7)%1;d.position.copy(lerp(pour,water,t)).add(v3(.015*Math.sin(i),0,.015*Math.cos(i)));});}
 for(let disc of room.furniture.deck.discs||[])if(dj)disc.rotation.y=elapsed*3;
}
function placeFood(){if(food){toast('どら焼きは、もうテーブルにあります。');return false;}if(!kitchen||kitchen.inventory.dorayaki<1){toast('どら焼きは0個です。オーブンで焼いて受け取りましょう。');return false;}kitchen.inventory.dorayaki--;food={id:++foodSerial,state:'placed'};placedCount++;if(!save()){kitchen.inventory.dorayaki++;food=null;foodSerial--;placedCount--;toast('保存できなかったため、どら焼きを戻しました。');return false;}log(null,'どら焼きをひとつ置いた');toast('どら焼きを置きました。食べたいタイミングを待ちましょう。');return true;}
function requestLayout(index){if(index===room.layout){room.clearPreview();toast('今の配置です。');return;}if(pendingLayout!==null)return;pendingLayout=index;actors.forEach(a=>a.queue=null);toast('ふたりが作業を終えて中央へ移動したら、模様替えします。');actors.filter(a=>a.state==='idle').forEach(stageActor);}
function applyPending(){if(pendingLayout!==null&&actors.every(a=>a.state==='ready')){let next=pendingLayout;room.clearPreview();room.applyLayout(next);pendingLayout=null;reservations.clear();actors.forEach(a=>{a.state='idle';a.timer=1+a.id;a.phase=null;});log(null,'部屋の配置を変更した');save();toast('模様替えができました。');}}
function simulate(dt){if(paused)return;let remain=Math.min(dt,.3)*speed;while(remain>0){let s=Math.min(remain,1/30);elapsed+=s;actors.forEach(a=>updateActor(a,s));applyPending();saveElapsed+=s;remain-=s;}if(saveElapsed>=20){save();saveElapsed=0;}}
function separateBubbles(){const [a,b]=actors;if(a.speech<=0||b.speech<=0)return;const x=a.bubble.getBoundingClientRect(),y=b.bubble.getBoundingClientRect();if(x.left>=y.right+6||y.left>=x.right+6||x.top>=y.bottom+6||y.top>=x.bottom+6)return;const topA=parseFloat(a.bubble.style.top),bottomB=Math.max(y.height+8,topA-x.height-6);b.bubble.style.top=bottomB+'px';if(bottomB>topA-x.height-6)a.bubble.style.top=(bottomB+x.height+6)+'px';}
function tick(dt){simulate(dt);toastTime=Math.max(0,toastTime-dt);if(!toastTime)$('#toast').style.opacity=0;actors.forEach(renderActor);separateBubbles();renderProps();let beat=Math.floor(elapsed*2);if(sound&&beat!==lastBeat&&actors.some(a=>a.phase?.pose==='dj'||a.phase?.pose==='dance'||a.phase?.pose==='music')){lastBeat=beat;tone([220,330,440,330][beat%4]);}kitchen?.render();$('#food').textContent=food?'配膳中':'置く '+(kitchen?.inventory.dorayaki||0);$('#food').disabled=!!food||!kitchen?.inventory.dorayaki;renderer.render(scene,camera);}
function layout(){const vv=window.visualViewport;let w=vv?.width||innerWidth,h=vv?.height||innerHeight;viewportWidth=w;viewportHeight=h;const st=document.body.style;st.setProperty('--viewport-width',w+'px');st.setProperty('--viewport-height',h+'px');st.setProperty('--viewport-left',(vv?.offsetLeft||0)+'px');st.setProperty('--viewport-top',(vv?.offsetTop||0)+'px');renderer.setSize(w,h);camera.aspect=w/h;let dist=(w/h<.8?37/(w/h/.55):20.5)*zoom;camera.position.set(Math.sin(az)*Math.cos(el)*dist,Math.sin(el)*dist,Math.cos(az)*Math.cos(el)*dist);camera.lookAt(0,.55,0);if(w<600&&mode==='edit')camera.setViewOffset(w,h,0,75,w,h);else camera.clearViewOffset();camera.updateProjectionMatrix();}
function tone(f){if(!sound)return;try{let ctx=window.chillAudio||(window.chillAudio=new(window.AudioContext||window.webkitAudioContext)());let o=ctx.createOscillator(),g=ctx.createGain();o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(.017,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.2);o.connect(g).connect(ctx.destination);o.start();o.stop(ctx.currentTime+.22);}catch{}}
function save(){try{localStorage.setItem('mob-chill-life-v2',JSON.stringify({v:2,kitchen:kitchen?.serialize(),layout:room.layout,theme:room.theme,elapsed,history,food:food?.state==='held'?null:food?{id:food.id,state:'placed'}:null,placedCount,consumedCount:consumedCount+(food?.state==='held'?1:0),foodSerial,actors:actors.map(a=>({done:a.done,lastAction:a.lastAction}))}));return true;}catch{return false;}}
function restore(){try{let s=JSON.parse(localStorage.getItem('mob-chill-life-v2'));if(!s||s.v!==2)return;kitchen?.restore(s.kitchen);if(Number.isInteger(s.layout)&&s.layout>=0&&s.layout<3)room.applyLayout(s.layout);if(Number.isInteger(s.theme)&&s.theme>=0&&s.theme<3)room.applyTheme(s.theme);elapsed=Number.isFinite(s.elapsed)?Math.max(0,s.elapsed):0;history=Array.isArray(s.history)?s.history.filter(h=>typeof h.text==='string').slice(0,60):[];food=s.food?.state==='placed'?{id:s.food.id,state:'placed'}:null;foodSerial=Number(s.foodSerial)||0;placedCount=Number(s.placedCount)||0;consumedCount=Number(s.consumedCount)||0;s.actors?.slice(0,2).forEach((a,i)=>{actors[i].done=a.done||{};actors[i].lastAction=a.lastAction||null;});}catch{}}
function reset(){kitchen?.reset();history=[];food=null;placedCount=consumedCount=foodSerial=0;elapsed=0;pendingLayout=null;reservations.clear();room.clearPreview();room.applyLayout(0);room.applyTheme(0);actors.forEach((a,i)=>{Object.assign(a,{state:'idle',action:'walk',timer:2+i,path:[],queue:null,phases:[],phase:null,done:{},cooldowns:{},speech:0});a.pos.set(i?.8:-.8,0,1.4);});save();}
function drawer(title,tag,html){$('#drawer').dataset.mode=tag==='ROOM STUDIO'?'editor':'resident';$('#drawerTitle').textContent=title;$('#drawerTag').textContent=tag;$('#drawerBody').innerHTML=html;$('#drawer').hidden=false;}
function showActor(id){selected=id;drawer(actors[id].name,'RESIDENT','<p class="caption">'+(id?'僕のペースで、きちんと楽しく。':'のんびり暮らすでやんす～。')+'</p><div class="grid">'+Object.entries(actions).map(([key,a])=>'<button data-action="'+key+'">'+a.icon+' '+a.name+'</button>').join('')+'</div><p class="caption" style="margin-top:12px">作業中のお誘いは、今の作業と片付けが終わってから。</p>');}
function edit(){mode='edit';draftLayout=room.layout;$('#edit').classList.add('active');$('#observe').classList.remove('active');showEditor();layout();}
function showEditor(){drawer('部屋を、ちょっと自分らしく。','ROOM STUDIO','<p class="caption">色と家具の配置を選びましょう。配置は床のプレビューで確認できます。</p><div class="section-label">家具の色</div><div class="choices">'+['セージ','ピーチ','ミスト'].map((n,i)=>'<button class="choice '+(room.theme===i?'selected':'')+'" data-theme="'+i+'"><span class="swatch" style="background:'+['#8ea27b','#c7999d','#7d969c'][i]+'"></span>'+n+'</button>').join('')+'</div><div class="section-label">部屋の配置</div><div class="choices">'+['ひだまり','読書の時間','音楽の午後'].map((n,i)=>'<button class="choice '+(draftLayout===i?'selected':'')+'" data-layout="'+i+'"><span class="layout-icon">'+['▥','▦','▤'][i]+'</span>'+n+'</button>').join('')+'</div><button class="primary wide" id="applyLayout">この配置にする</button><p class="caption" style="margin-top:12px">ふたりの作業を終えてから安全に変更します。置いたどら焼きもテーブルと一緒に移ります。</p>');}
function observe(){mode='observe';room.clearPreview();$('#drawer').hidden=true;$('#observe').classList.add('active');$('#edit').classList.remove('active');layout();}
$('#drawerBody').onclick=e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.action){if(start(actors[selected],b.dataset.action,true)){$('#drawer').hidden=true;}}else if(b.dataset.theme!==undefined){room.applyTheme(+b.dataset.theme);save();showEditor();}else if(b.dataset.layout!==undefined){draftLayout=+b.dataset.layout;room.previewLayout(draftLayout);showEditor();}else if(b.id==='applyLayout'){requestLayout(draftLayout);observe();}};
document.querySelectorAll('[data-actor]').forEach(b=>b.onclick=()=>showActor(+b.dataset.actor));$('#closeDrawer').onclick=observe;$('#observe').onclick=observe;$('#edit').onclick=edit;$('#food').onclick=placeFood;$('#pause').onclick=()=>{paused=!paused;$('#pause').textContent=paused?'▶':'Ⅱ';$('#pause').setAttribute('aria-label',paused?'再開':'一時停止');};$('#speed').onclick=()=>{speed=speed===1?2:speed===2?4:1;$('#speed').textContent=speed+'×';};$('#audio').onclick=()=>{sound=!sound;$('#audio').textContent='音 '+(sound?'ON':'OFF');tone(660);};$('#camera').onclick=()=>{view=(view+1)%3;az=[.7,.25,1.08][view];el=[.79,.97,.66][view];zoom=1;layout();};$('#zoomIn').onclick=()=>{zoom=clamp(zoom-.12,.58,1.3);layout();};$('#zoomOut').onclick=()=>{zoom=clamp(zoom+.12,.58,1.3);layout();};
function modal(title,html){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=html;$('#modal').showModal();}$('#modalClose').onclick=()=>$('#modal').close();$('#help').onclick=()=>modal('MOB CHILL LIFE','<p>ふたりは気の向くまま暮らします。名前やキャラをタップして行動に誘えます。</p><p>ドラッグで回転、ピンチ／ホイール／＋−で拡大。視点ボタンでおすすめの眺めに戻れます。</p><p><b>部屋づくり</b>で家具の色と3つの配置を選択。作業中の家具は、ふたりが離れてから模様替えします。</p><p><b>オーブン</b>で小麦・小豆を各1個使い、実時間60秒でどら焼きができます。受取後、所持数からテーブルに1個置けます。ふたりが好きなタイミングで食べます。勝手には補充されません。</p><p>Ⅱは一時停止、1×は1・2・4倍速。音は任意ON。記録は端末内だけに保存されます。</p><p>正式56フレームを組み込みました。V3の実画面確認と実機iPhone／iPad Safariの検証はこれからです。</p>');
$('#more').onclick=()=>{modal('暮らしの記録','<button id="saveNow">いま保存</button><button id="resetSave" class="danger">記録を初期化</button><div class="journal">'+(history.length?history.map(h=>'<p><time>'+h.n+'分目</time>'+escapeText(h.text)+'</p>').join(''):'<p>ふたりの暮らしは、ここから。</p>')+'</div>');$('#saveNow').onclick=()=>toast(save()?'保存しました。':'このブラウザでは保存できません。');$('#resetSave').onclick=()=>{if(confirm('配置・思い出・どら焼きの記録を初期化しますか？')){reset();$('#modal').close();toast('新しい暮らしを始めました。');}};};function escapeText(s){let d=document.createElement('span');d.textContent=s;return d.innerHTML;}
const canvas=renderer.domElement;let pointers=new Map(),down=null,pinch=0;canvas.oncontextmenu=e=>e.preventDefault();canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});down={x:e.clientX,y:e.clientY,moved:false};if(pointers.size===2){let p=[...pointers.values()];pinch=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y);down.moved=true;}});canvas.addEventListener('pointermove',e=>{let p=pointers.get(e.pointerId);if(!p)return;let dx=e.clientX-p.x,dy=e.clientY-p.y;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(down&&Math.hypot(e.clientX-down.x,e.clientY-down.y)>5)down.moved=true;if(pointers.size===2){let ps=[...pointers.values()],d=Math.hypot(ps[0].x-ps[1].x,ps[0].y-ps[1].y);zoom=clamp(zoom*pinch/(d||1),.58,1.3);pinch=d;}else{az=clamp(az-dx*.005,-.12,1.42);el=clamp(el+dy*.004,.45,1.12);}layout();});canvas.addEventListener('pointerup',e=>{pointers.delete(e.pointerId);if(down&&!down.moved){let ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2((e.clientX-canvas.getBoundingClientRect().left)/viewportWidth*2-1,1-(e.clientY-canvas.getBoundingClientRect().top)/viewportHeight*2),camera);let hit=ray.intersectObjects(actors.flatMap(a=>a.sleepGroup.visible?[a.sleepPlane]:[a.sprite]));if(hit.length){let a=actors.find(a=>a.sprite===hit[0].object||a.sleepPlane===hit[0].object);showActor(a.id);speak(a,a.id?'僕を呼んだであります？':'呼んだでやんす？');}else if(ray.intersectObject(room.furniture.oven.group,true).length){kitchen.open();}}if(!pointers.size)down=null;});canvas.addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);down=null;});canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=clamp(zoom+e.deltaY*.001,.58,1.3);layout();},{passive:false});window.addEventListener('resize',layout);window.visualViewport?.addEventListener('resize',layout);window.visualViewport?.addEventListener('scroll',layout);window.addEventListener('pagehide',save);
kitchen=new ChillKitchen(room,{save,toast,tone,modal,started(){const a=actors.find(a=>a.state==='idle');if(a)start(a,'oven',true)}});$('#ovenButton').onclick=()=>kitchen.open();restore();save();layout();let last=performance.now();document.addEventListener('visibilitychange',()=>{last=performance.now();if(document.hidden)save();});function loop(now){tick((now-last)/1000);last=now;requestAnimationFrame(loop);}requestAnimationFrame(loop);
window.CHILL={kitchen,actors,room,actions,reservations,book,snack,broom,can,hand,spriteAnchorWorld,camera,groundedDock,setView(azimuth,elevation){az=azimuth;el=elevation;layout();},start,route,placeFood,requestLayout,save,restore,reset,tick,renderProps,setPaused(v){paused=v;},setSpeed(v){speed=v;},get state(){return{elapsed,paused,speed,food,placedCount,consumedCount,pendingLayout,history,layout:room.layout,theme:room.theme};},advance(seconds,dt=1/30){let was=paused;paused=false;for(let t=0;t<seconds;t+=dt)simulate(Math.min(dt,seconds-t));paused=was;renderProps();},snapshot(){return actors.map(a=>({id:a.id,state:a.state,action:a.action,phase:a.phase?.name,pos:a.pos.toArray(),done:{...a.done},queue:a.queue}));}};
})();
