/* Shared meal gesture, visible dialogue, plate clearing and a persisted small heart economy. */
(()=>{'use strict';
const $=s=>document.querySelector(s),V=(x,y,z)=>new THREE.Vector3(x,y,z),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const CONFIG=window.CHILL_HEART_CONFIG={meal:3,fun:1,funLimit:10,funCooldown:120,prices:{wheat:1,beans:1,egg:2,corn:1,milk:2}};
const names={wheat:'小麦',beans:'小豆',egg:'卵',corn:'コーン',milk:'ミルク'};
window.ChillLife={
 mealLine(a,done){return (done?'ごちそうさま':'いただきます')+(a.id===0?'でやんす～！':a.id===1?'であります！':a.id===2?'ニョロ～！':done?'でした。':'。');},
 bite(g,a,time,duration,c){let u=time/duration,cycle=(time%3)/3,lift=Math.sin(Math.PI*clamp((cycle-.1)/.7,0,1)),hand=c.spriteAnchorWorld(a,[.53,.66],.055),mouth=c.spriteAnchorWorld(a,[.51,.49],.07);g.position.copy(hand).lerp(mouth,lift);g.scale.setScalar(Math.max(.14,1-u)*.7);g.rotation.z=Math.sin(time*3)*.035;if(!a.mealHands){a.mealHands=new THREE.Group();for(let x of [-.09,.09]){let o=new THREE.Mesh(new THREE.SphereGeometry(.052,10,8),new THREE.MeshStandardMaterial({color:'#faf2dd'}));o.position.x=x;a.mealHands.add(o);}g.parent.add(a.mealHands);}a.mealHands.position.copy(g.position);a.mealHands.position.y-=.025;a.mealHands.visible=true;},
 bubbles(actors,view){let footer=$('footer').getBoundingClientRect(),top=Math.max(104,$('#roomSwitch')?.getBoundingClientRect().bottom+4||104),bottom=Math.min(footer.top,$('#activityToggle')?.getBoundingClientRect().top||footer.top)-8,placed=[];for(let a of actors){let e=a.bubble,home=a.pos.x<6&&a.pos.z<4.6;if(a.speech<=0||view!==(home?'home':'cafe')){e.style.opacity=0;continue;}e.style.display='block';let r=e.getBoundingClientRect(),w=Math.min(r.width,innerWidth-16),h=r.height,x=clamp(parseFloat(e.style.left)||innerWidth/2,w/2+8,innerWidth-w/2-8),y=clamp(parseFloat(e.style.top)||top+h,top+h,bottom);for(let n=0;n<8;n++){let hit=placed.find(p=>Math.abs(x-p.x)<(w+p.w)/2+4&&y-h<p.y+4&&y>p.y-p.h-4);if(!hit)break;y=hit.y-hit.h-7;if(y-h<top){y=bottom;x=x<innerWidth/2?innerWidth-w/2-8:w/2+8;}}e.style.left=x+'px';e.style.top=y+'px';e.style.opacity=1;placed.push({x,y,w,h});}},
};
const Base=window.ChillCafe;
window.ChillCafe=class extends Base{
 constructor(c){super(c);this.wallet={balance:0,pending:[],serial:0,claimed:{},funDay:'',funCount:0,funTimes:{}};this.dirty=[false,false,false];this.cleaning=null;this.plates=this.tables.map(()=>{let g=new THREE.Group();c.room.cyl(g,0,0,0,.29,.26,.025,'#fcf5de');c.room.cyl(g,0,.012,0,.25,.25,.012,'#eee1c7');c.scene.add(g);g.visible=false;return g;});this.bites=this.tables.map(()=>{let g=c.snack.clone(true);c.scene.add(g);g.visible=false;return g;});this.dropNodes=new Map();this.installWallet();}
 serialize(){return{...super.serialize(),wallet:this.wallet,dirty:this.dirty};}
 restore(s){super.restore(s);let w=s?.wallet||{},n=x=>Number.isSafeInteger(x)&&x>=0?x:0;this.wallet={balance:n(w.balance),serial:n(w.serial),pending:(w.pending||[]).filter(d=>Number.isSafeInteger(d.id)&&d.id>0&&Number.isSafeInteger(d.value)&&d.value>0&&d.value<=3&&Array.isArray(d.pos)&&d.pos.length===3&&d.pos.every(Number.isFinite)).slice(0,100),claimed:w.claimed&&typeof w.claimed==='object'?w.claimed:{},funDay:typeof w.funDay==='string'?w.funDay:'',funCount:n(w.funCount),funTimes:w.funTimes&&typeof w.funTimes==='object'?w.funTimes:{}};this.wallet.pending=this.wallet.pending.filter((d,i,all)=>all.findIndex(x=>x.id===d.id)===i);this.wallet.serial=Math.max(this.wallet.serial,...this.wallet.pending.map(d=>d.id),0);this.dirty=[0,1,2].map(i=>!!s?.dirty?.[i]);this.cleaning=null;}
 reward(id,a,type){if(!id||id.endsWith('undefined')||this.wallet.claimed[id]||this.wallet.pending.length>=100)return false;let old=JSON.stringify(this.wallet),w=this.wallet,now=Date.now()/1000;if(type==='fun'){let day=new Date().toISOString().slice(0,10);if(w.funDay!==day){w.funDay=day;w.funCount=0;}if(w.funCount>=CONFIG.funLimit||now-(w.funTimes[a.id]||0)<CONFIG.funCooldown)return false;w.funTimes[a.id]=now;w.funCount++;}w.claimed[id]=true;w.pending.push({id:++w.serial,value:CONFIG[type],pos:a.pos.toArray(),room:a.room});if(this.c.save())return true;this.wallet=JSON.parse(old);return false;}
 collectHeart(id){let w=this.wallet,i=w.pending.findIndex(d=>d.id===id);if(i<0)return false;let d=w.pending[i];w.pending.splice(i,1);w.balance+=d.value;if(this.c.save())return true;w.balance-=d.value;w.pending.splice(i,0,d);return false;}
 buy(k){let price=CONFIG.prices[k],p=this.c.kitchen.inventory,w=this.wallet;if(!price||w.balance<price||!Number.isSafeInteger(p[k])||p[k]<0)return false;w.balance-=price;p[k]++;if(this.c.save())return true;p[k]--;w.balance+=price;return false;}
 installWallet(){let b=document.createElement('button');b.id='heartWallet';b.textContent='♥ 0';b.setAttribute('aria-label','ハートと食材のお店');$('.top').prepend(b);b.onclick=()=>this.shop();let nav=$('footer nav'),more=$('#more'),box=document.createElement('div');box.id='extraControls';box.hidden=true;for(let id of ['observe','edit','food','pause','speed'])box.appendChild($('#'+id));nav.after(box);let toggle=document.createElement('button');toggle.id='lifeControls';toggle.textContent='操作';toggle.setAttribute('aria-expanded','false');nav.insertBefore(toggle,more);toggle.onclick=()=>{box.hidden=!box.hidden;toggle.setAttribute('aria-expanded',String(!box.hidden));};}
 menu(a){if(a.id!==3)return super.menu(a);this.closeActivity();this.c.modal('イルカエルのカフェ','<p>あら～、ご用は何でしょう。</p><div class="shop-actions"><button id="giveMeals">料理を預ける</button><button id="buyIngredients">ハートで食材を買う</button></div>');$('#giveMeals').onclick=()=>this.depositMenu();$('#buyIngredients').onclick=()=>this.shop();}
 shop(){this.closeActivity();this.c.modal('イルカエルの食材屋さん','<p>ふふっ、今日のお料理にどうぞ。</p><p>所持ハート <b id="shopBalance">'+this.wallet.balance+'</b></p>'+Object.entries(names).map(([k,n])=>'<div class="shop-row"><span>'+n+' <small>所持 '+this.c.kitchen.inventory[k]+'</small></span><button data-buy="'+k+'">♥ '+CONFIG.prices[k]+'で1個</button></div>').join('')+'<p id="shopStatus" role="status">おいしい・うれしい時のハートをタップして集めます。</p>');document.querySelectorAll('[data-buy]').forEach(b=>{b.disabled=this.wallet.balance<CONFIG.prices[b.dataset.buy];b.onclick=()=>{if(this.buy(b.dataset.buy))this.shop();else $('#shopStatus').textContent='購入できませんでした。ハートと保存状態を確認してください。';};});}
 completeMeal(a){this.dirty[a.cafeSeat]=true;this.c.speak(a,ChillLife.mealLine(a,true),5,true);this.reward('cafe:'+a.mealRewardId,a,'meal');this.c.save();}
 updateJoy(){for(let a of this.c.actors){if(a.room==='home'&&a.state==='acting'&&['joy','dance','dj'].includes(a.action)&&a.phaseTime>=.7)this.reward('fun:'+a.id+':'+a.action+':'+a.done[a.action],a,'fun');}}
 leave(a){let i=this.seats.indexOf(a.id),old=i>=0?this.dirty[i]:false;if(i>=0&&a.cafeMode==='eating')this.dirty[i]=true;let result=super.leave(a);if(!result&&i>=0)this.dirty[i]=old;else if(result)this.c.save();return result;}
 setTableVisible(i,v){if(this.dirty[i]||this.cleaning?.seat===i)return false;return super.setTableVisible(i,v);}
 waiter(dt){let a=this.c.actors[3];if(this.cleaning){a.speech=Math.max(0,a.speech-dt);if(a.cafePath?.length){this.move(a,dt);return;}let s=this.cleaning;s.time+=dt;if(s.stage==='approach'&&s.time>=1){s.stage='return';s.time=0;this.returnToCounter();this.staff('tidy');}else if(s.stage==='return'&&s.time>=.6){let i=s.seat;this.dirty[i]=false;if(!this.c.save()){this.dirty[i]=true;return;}this.cleaning=null;}return;}if(!this.service&&!a.cafePath?.length){let i=this.dirty.findIndex((d,i)=>d&&this.seats[i]===null);if(i>=0){this.cleaning={seat:i,stage:'approach',time:0};a.cafePath=[V(this.tables[i].serve.x,0,-1.8),this.tables[i].serve.clone()];return;}}super.waiter(dt);}
 render(){super.render();let c=this.c;for(let a of c.actors)if(a.mealHands)a.mealHands.visible=(a.cafeMode==='eating'&&this.view==='cafe')||(a.phase?.hold==='food'&&this.view==='home');for(let i=0;i<3;i++){let p=this.plates[i],b=this.bites[i],a=c.actors[this.seats[i]],s=this.service?.seat===i?this.service:null,d=this.dishes[i];p.visible=this.view==='cafe'&&(!!s||a?.cafeMode==='eating'||this.dirty[i]);p.position.copy(this.tables[i].plate);p.position.y=.838;if(s){p.position.copy(d.position);p.position.y-=({dorayaki:.066,omelet:.017,soup:.013}[this.ledger.orders[i]?.kind]||.066)-.028;d.position.y+=.027;}if(this.cleaning?.seat===i){let cl=this.cleaning;if(cl.stage==='return')p.position.copy(this.handPoint());else if(!c.actors[3].cafePath?.length)p.position.lerp(this.handPoint(),clamp(cl.time,0,1));}b.visible=this.view==='cafe'&&a?.cafeMode==='eating';if(b.visible){ChillLiving.meal(b,{kind:a.mealKind},null);ChillLife.bite(b,a,a.cafeTimer,32,c);b.scale.multiplyScalar(.3);d.position.y+=.027;if(a.mealKind==='soup'){let g=d.mealGroups.soup;g.children[1].position.y=.13-a.cafeTimer/32*.09;g.children.slice(2).forEach(o=>o.visible=a.cafeTimer<25);}if(a.mealKind==='omelet')d.mealGroups.omelet.children.forEach((o,j)=>o.visible=j>=Math.floor(a.cafeTimer/32*3));}if(this.view!=='cafe')d.visible=false;}for(let a of c.actors)if(a.cafeMode==='satisfied')a.effect.textContent='♪';this.renderHearts();}
 renderHearts(){let active=new Set();for(let d of this.wallet.pending){active.add(d.id);let el=this.dropNodes.get(d.id);if(!el){el=document.createElement('button');el.className='heart-drop';el.textContent='♥';el.setAttribute('aria-label','ハート'+d.value+'個を拾う');el.onclick=e=>{e.stopPropagation();this.collectHeart(d.id);};$('#labels').appendChild(el);this.dropNodes.set(d.id,el);}let p=V(...d.pos);p.y=.15;p.project(this.c.camera);el.hidden=this.view!==d.room||p.z>1||Math.abs(p.x)>.96||Math.abs(p.y)>.9||!!this.c.room.mobileEditor||$('#modal').open;el.style.left=clamp((p.x*.5+.5)*innerWidth,24,innerWidth-24)+'px';el.style.top=clamp((-p.y*.5+.5)*innerHeight,150,$('footer').getBoundingClientRect().top-24)+'px';}for(let [id,el]of this.dropNodes)if(!active.has(id)){el.remove();this.dropNodes.delete(id);}$('#heartWallet').textContent='♥ '+this.wallet.balance;}
};
})();
