/* V20: shared indoor routes, six resident activities and reserved sleeping furniture. */
(()=>{'use strict';const T=THREE,V=(x=0,y=0,z=0)=>new T.Vector3(x,y,z),$=s=>document.querySelector(s),clamp=x=>Math.max(0,Math.min(1,x));
const doors={home:V(1.9,0,3.45),cafe:V(14,0,3.45),bath:V(28,0,3.3),arcade:V(56,0,3.45),farm:V(42,0,3.45)};
function zone(p){return p.z>4.25?'hall':p.x<6?'home':p.x<22?'cafe':p.x<35?'bath':p.x<49?'farm':'arcade';}
function direction(h,camera){camera.updateMatrixWorld();const x=V().setFromMatrixColumn(camera.matrixWorld,0),z=V().setFromMatrixColumn(camera.matrixWorld,2);x.y=z.y=0;x.normalize();z.normalize();const dx=h.dot(x),dz=h.dot(z);return Math.abs(dx)>Math.abs(dz)?dx<0?'left':'right':dz<0?'back':'front';}
class InteriorRoutes20{
 constructor(cafe){this.cafe=cafe;this.c=cafe.c;}
 rects(room){const c=this.cafe,rects=[];const add=(id,x,z,w,d)=>rects.push({id,minX:x-w/2-.12,maxX:x+w/2+.12,minZ:z-d/2-.12,maxZ:z+d/2+.12});if(room==='cafe'){for(let i=0;i<c.tables.length;i++){const t=c.tables[i];if(t.group.visible){add('table'+i,t.x,0,1.08,.95);add('chair'+i,t.x,-1.03,.65,.65);}}add('counter',14,-2.65,3.6,.9);add('shelf',10.7,-3.5,1.7,.7);add('cafeSofa',17.2,-2.85,1.85,.9);}if(room==='bath'){add('pool',28,-.05,5.5,4.5);for(let i=0;i<2;i++)add('recliner'+i,24.9+i*6.2,3.65,1.65,.9);}if(room==='arcade'){add('gacha0',52.4,-2.6,1.2,1.0);add('gacha1',54,-2.6,1.2,1.0);add('ufo',59.2,-2.1,2.8,2.2);add('race0',55.3,1.9,1.2,.75);add('race1',56.7,1.9,1.2,.75);}return rects;}
 inside(p,room){const b={cafe:[9.7,18.3,-3.75,4.2],bath:[23.65,32.35,-3.5,4.2],arcade:[50.85,61.15,-3.6,4.2],farm:[36,47,-3.6,4.2]}[room];return !b||p.x>=b[0]&&p.x<=b[1]&&p.z>=b[2]&&p.z<=b[3];}
 blocked(a,b,rects){return rects.some(r=>{let lo=0,hi=1;for(const [k,min,max]of [['x',r.minX,r.maxX],['z',r.minZ,r.maxZ]]){const d=b[k]-a[k];if(Math.abs(d)<1e-8){if(a[k]<=min||a[k]>=max)return false;}else{let u=(min-a[k])/d,v=(max-a[k])/d;if(u>v)[u,v]=[v,u];lo=Math.max(lo,u);hi=Math.min(hi,v);if(lo>=hi)return false;}}return hi>0&&lo<1;});}
 route(room,from,to,ignore=null){if(room==='home')return this.c.route(from,to);if(!this.inside(from,room)||!this.inside(to,room))return null;const rects=this.rects(room).filter(r=>r.id!==ignore),valid=p=>this.inside(p,room)&&!rects.some(r=>p.x>r.minX&&p.x<r.maxX&&p.z>r.minZ&&p.z<r.maxZ);if(!valid(to)||!valid(from))return null;if(!this.blocked(from,to,rects))return[to.clone()];const nodes=[from.clone(),to.clone()];for(const r of rects)for(const x of [r.minX-.06,r.maxX+.06])for(const z of [r.minZ-.06,r.maxZ+.06]){const p=V(x,0,z);if(valid(p))nodes.push(p);}const dist=nodes.map(()=>Infinity),prev=[],open=new Set(nodes.map((_,i)=>i));dist[0]=0;while(open.size){const u=[...open].sort((i,j)=>dist[i]-dist[j])[0];open.delete(u);if(u===1||!Number.isFinite(dist[u]))break;for(const j of open)if(!this.blocked(nodes[u],nodes[j],rects)){const d=dist[u]+nodes[u].distanceTo(nodes[j]);if(d<dist[j]){dist[j]=d;prev[j]=u;}}}if(!Number.isFinite(dist[1]))return null;const out=[];for(let n=1;n!==0;n=prev[n])out.unshift(nodes[n]);return out;}
 landing(room,a){if(room==='home'){for(const p of [V((a.id%3-1)*.7,0,2),V(0,0,2.6),V(-1.4,0,2.6),V(1.2,0,1.5)])if(this.c.route(doors.home,p))return p;return null;}return room==='bath'?V(31.3,0,2.85):room==='cafe'?V(13.4+(a.id%3)*.55,0,2.4):room==='arcade'?V(57.8,0,3.1):V(42,0,2.6);}
 travel(a,to,target){const from=a.room,first=this.route(from,a.pos,doors[from]);if(!first)return null;const last=this.route(to,doors[to],target);if(!last)return null;return[...first,V(doors[from].x,0,5.3),V(doors[to].x,0,5.3),doors[to].clone(),...last];}
}
class SleepPlaces20{
 constructor(cafe){this.cafe=cafe;this.c=cafe.c;this.claims=new Map();this.pending=new Set();this.createFurniture();}
 createFurniture(){const c=this.cafe,r=this.c.room;const sofa=new T.Group();sofa.name='cafe-sofa-v20';sofa.position.set(17.2,0,-2.85);c.group.add(sofa);r.box(sofa,0,.34,0,1.85,.48,.86,'#b4956d');r.box(sofa,0,.61,.02,1.65,.18,.74,'#9da887');r.box(sofa,0,.87,-.35,1.85,.62,.17,'#9da887');for(const x of [-.87,.87])r.box(sofa,x,.68,0,.16,.36,.86,'#b4956d');this.sofa=sofa;this.recliners=[];for(let i=0;i<2;i++){const g=new T.Group();g.name='MOB-recliner-v20-'+i;g.position.set(24.9+i*6.2,0,3.65);g.rotation.y=Math.PI/2;c.bath.group.add(g);for(const x of [-.37,.37]){r.box(g,x,.28,0,.08,.56,1.4,'#a08058');r.box(g,x,.65,-.15,.1,.1,1.0,'#bb986b');}r.box(g,0,.47,.25,.72,.16,1.1,'#c6b98d');const back=r.box(g,0,.84,-.51,.72,.95,.16,'#a5b4a0');back.rotation.x=-.32;const cv=document.createElement('canvas');cv.width=256;cv.height=96;const ctx=cv.getContext('2d');ctx.clearRect(0,0,256,96);ctx.fillStyle='#40584b';ctx.font='bold 64px sans-serif';ctx.textAlign='center';ctx.fillText('MOB',128,72);const tx=new T.CanvasTexture(cv);tx.colorSpace=T.SRGBColorSpace;const label=new T.Mesh(new T.PlaneGeometry(.55,.2),new T.MeshBasicMaterial({map:tx,transparent:true,depthWrite:false}));label.position.set(0,1.06,-.31);label.rotation.x=-.32;g.add(label);this.recliners.push(g);}}
 places(){const c=this.cafe,r=this.c.room,key=['bed','sofa'].map(k=>{const g=r.furniture[k]?.group;return g?[g.uuid,g.visible,...g.position.toArray(),g.rotation.y].join(','):'';}).join('|')+'|'+c.tables.map(t=>t.group.visible).join(',');if(this.placeKey20===key)return this.placeCache20;const p=[];if(r.furniture.bed?.group.visible)p.push({id:'home:bed',priority:0,room:'home',kind:'lie',furniture:'bed',entry:r.socket('bed','entry'),point:r.socket('bed','center'),angle:r.furniture.bed.group.rotation.y-Math.PI/2,size:[1.55,.8]});if(r.furniture.sofa?.group.visible)p.push({id:'home:sofa',priority:1,room:'home',kind:'lie',furniture:'sofa',entry:r.socket('sofa','entry'),point:r.furniture.sofa.group.localToWorld(V(.18,.915,0)),angle:r.furniture.sofa.group.rotation.y-Math.PI/2,size:[1.55,.75]});p.push({id:'cafe:sofa',priority:1,room:'cafe',kind:'lie',entry:V(17.2,0,-1.85),point:V(17.2,.72,-2.82),angle:0,size:[1.5,.65]});for(let i=0;i<c.tables.length;i++)if(c.tables[i].group.visible)p.push({id:'cafe:chair'+i,priority:2,room:'cafe',kind:'seat',seat:i,entry:c.tables[i].approach.clone(),point:c.tables[i].seat.clone(),angle:0,size:[1,1]});for(let i=0;i<2;i++)p.push({id:'bath:recliner'+i,priority:2,room:'bath',kind:'seat',entry:V(24.9+i*6.2,0,2.65),point:V(25.15+i*6.2,.56,3.65),angle:0,size:[1.05,1.05]});this.placeKey20=key;this.placeCache20=p;return p;}
 free(p,a){if(this.claims.has(p.id)&&this.claims.get(p.id)!==a.id)return false;if(p.furniture&&window.CHILL?.reservations.has(p.furniture)&&CHILL.reservations.get(p.furniture)!==a.id)return false;if(p.seat!==undefined&&(this.cafe.seats[p.seat]!==null||this.cafe.ledger.orders[p.seat]||this.cafe.dirty[p.seat]))return false;return true;}
 request(a,record=null,night=false){const c=this.cafe;if(!a.lifeReady20||a.addedResident&&!a.motion18Ready)return false;if(this.c.editing()||this.c.room.mobileEditor||$('#modal').open||a.rest20||a.transit20||a.townAction19||!c.routine.idle(a)||a.key==='nekokoo'&&!!c.routine.state.ownerMeal||a.bagAnimation||c.service?.actor===a.id)return false;const places=this.places().slice().sort((x,y)=>x.priority-y.priority||(x.room===a.room?-1:1)-(y.room===a.room?-1:1));for(const p of places){if(!this.free(p,a))continue;const path=p.room===a.room?c.routes20.route(p.room,a.pos,p.entry):c.routes20.travel(a,p.room,p.entry);if(!path)continue;const old={state:a.state,cafeMode:a.cafeMode,path:a.path,cafePath:a.cafePath,timer:a.timer,cafeWait:a.cafeWait,routineRest:a.routineRest};this.claims.set(p.id,a.id);if(p.furniture&&window.CHILL)CHILL.reservations.set(p.furniture,a.id);if(p.seat!==undefined)c.seats[p.seat]=a.id;a.rest20={place:p,night,phase:'approach',path,time:0,origin:a.room,record:record?.slot};a.cafeMode=null;a.state='idle';a.path=[];a.cafePath=[];a.routineRest=false;if(!this.c.save()){this.release(a);Object.assign(a,old);return false;}if(record){record.phase='resting';record.next=c.clock14+15;}c.routine.say(a,'bed');this.pending.delete(a.id);return true;}if(record){record.phase='queued';record.next=c.clock14+12;}this.pending.add(a.id);return false;}
 release(a){const s=a.rest20;if(!s)return;const p=s.place;this.claims.delete(p.id);if(p.furniture&&window.CHILL?.reservations.get(p.furniture)===a.id)CHILL.reservations.delete(p.furniture);if(p.seat!==undefined&&this.cafe.seats[p.seat]===a.id)this.cafe.seats[p.seat]=null;delete a.rest20;a.routineRest=false;a.sleepGroup.visible=false;a.timer=8;a.cafeWait=60;if(a.room==='cafe'&&a.id!==3)a.cafeMode='waiting';const home=a.key==='nekokoo'?'bath':a.id===3?'cafe':null;if(home&&a.room!==home&&s.phase==='exit'){const target=a.id===3?this.cafe.counter.clone():this.cafe.routes20.landing(home,a),path=this.cafe.routes20.travel(a,home,target);if(path){a.cafeMode=null;a.transit20={path,room:home,origin:a.room};}}}
 update(a,dt){const s=a.rest20;if(!s)return false;a.speech=Math.max(0,a.speech-dt);const p=s.place,current=this.places().find(x=>x.id===p.id),editing=this.c.editing()||this.c.room.mobileEditor;let wake=!current||editing||s.night&&this.cafe.routine.hour>=6&&this.cafe.routine.hour<22||!s.night&&s.phase==='sleep'&&s.time>16;if(s.phase==='approach'){if(wake){this.release(a);return true;}if(this.cafe.follow20(a,s.path,dt)){a.room=p.room;s.phase='settle';s.from=a.pos.clone();s.time=0;}return true;}if(wake&&s.phase!=='exit'){s.phase='exit';s.from=a.pos.clone();s.time=0;}s.time+=dt;if(s.phase==='settle'||s.phase==='exit'){const u=clamp(s.time/1.25),target=s.phase==='settle'?p.point:p.entry;a.pos.copy(s.from).lerp(target,u*u*(3-2*u));if(u>=1){if(s.phase==='exit'){a.pos.y=0;this.release(a);this.c.save();}else{s.phase='sleep';s.time=0;a.speech=0;this.c.save();}}}return true;}
 restore(){for(const a of this.c.actors){if(a.rest20)this.release(a);a.routineRest=a.routineNight=false;const m=this.cafe.routine.meta(a);m.rest=m.bed=false;if(a.phase?.routineRest)a.phase=null;if(a.addedResident)a.npcPose='idle';}this.claims.clear();for(const r of Object.values(this.cafe.routine.state.days))if(r.type==='sleep'&&r.phase==='resting'){r.phase='queued';r.next=0;}}
 render(a){const s=a.rest20;if(!s)return;const visible=this.cafe.view===zone(a.pos);if(s.phase!=='sleep'){a.sleepGroup.visible=false;return;}const p=s.place,index=Math.floor(s.time/1.8)%2,tex=a.life20?.[p.kind==='lie'?'sleepLie':'sleepSeat']?.[index]||a.motion18?.frames[28+index];if(!tex)return;a.sprite.visible=false;a.shadow.visible=false;a.sleepGroup.visible=false;if(!a.restSprite20){const material=new T.SpriteMaterial({transparent:true,alphaTest:.05,depthWrite:false}),spr=new T.Sprite(material);this.c.scene.add(spr);a.restSprite20=spr;const holder={sprite:spr};ChillContactDepth.install(holder);a.restDepth20=holder.contactDepth;const geom=new T.PlaneGeometry(1,1,20,20),verts=geom.attributes.position;for(let i=0;i<verts.count;i++){const x=verts.getX(i),y=verts.getY(i);verts.setZ(i,.08*Math.max(0,1-(x/.5)**2-(y/.4)**2));}geom.computeVertexNormals();const plane=new T.Mesh(geom,new T.MeshBasicMaterial({transparent:true,alphaTest:.05,depthWrite:false,side:T.DoubleSide}));plane.rotation.x=-Math.PI/2;for(let i=1;i<=3;i++){const layer=new T.Mesh(new T.PlaneGeometry(1,1),plane.material.clone());layer.material.color.set(i===3?'#c9c3af':'#eee5cc');layer.position.z=-i*.018;plane.add(layer);}this.c.scene.add(plane);a.restPlane20=plane;}if(p.kind==='lie'){a.restSprite20.visible=false;const plane=a.restPlane20;plane.visible=visible;plane.material.map=tex;plane.position.copy(p.point).add(V(0,.035,0));plane.rotation.set(-Math.PI/2,0,p.angle);const span=p.size[0]*(a.key==='tetsu'?.8:1);plane.scale.set(span,span,1);for(const layer of plane.children)layer.material.map=tex;}else{a.restPlane20.visible=false;const spr=a.restSprite20;spr.visible=visible;spr.material.map=tex;spr.center.set(.5,.14);spr.position.copy(p.point);const size=a.key==='tetsu'?1.32:a.addedResident?1.65:a.scale;spr.scale.set(size,size,1);a.restDepth20.value=1;}a.effect.hidden=false;a.effect.textContent='z z Z';a.effect.style.opacity=visible?1:0;const point=a.pos.clone().add(V(0,.8,0)).project(this.c.camera);a.effect.style.left=(point.x*.5+.5)*innerWidth+'px';a.effect.style.top=(-point.y*.5+.5)*innerHeight+'px';$('#state'+a.id).textContent='すやすや';}
}
const sampleBag20=ChillBagMotion.sample.bind(ChillBagMotion);ChillBagMotion.sample=a=>{const sample=sampleBag20(a);if(a.addedResident&&sample?.pose.startsWith('meal_'))sample.anchor=a.mealFrameMeta?.[Number(sample.pose.slice(5))]?.heldFoodAnchorPx||sample.anchor;return sample;};
const Base=ChillCafe;window.ChillCafe=class extends Base{
 constructor(c){super(c);const speak=c.speak;c.speak=(a,text,...args)=>speak(a,text||(a?.key==='tetsu'?'楽しみでござる！':a?.key==='nekokoo'?'オラも楽しむんだぞ！':''),...args);this.routes20=new InteriorRoutes20(this);this.sleep20=new SleepPlaces20(this);for(const a of c.actors){if(a.key==='tetsu')a.scale=1.32;a.phases=a.phases||[];a.phaseIndex=a.phaseIndex||0;this.arcadeNext[a.id]=this.arcadeClock+40+a.id*9;this.bagIdle[a.id]=30+a.id*7;if(a.addedResident){a.npcPose='idle';a.timer=2+a.id;this.loadLife20(a);}else this.loadLife20(a);}const idle=this.routine.idle.bind(this.routine);this.routine.idle=a=>a.id===3&&this.routine.window(a)?.type==='sleep'&&!a.rest20&&!a.transit20&&!a.phase&&!a.arcadeMode&&!a.bathMode&&!a.bagAnimation&&!a.cafePath?.length&&!this.service&&!this.cleaning&&!this.staffMeal&&this.seats.every(id=>id===null||this.c.actors[id]?.rest20)?true:idle(a);const bathEligible=this.bath.eligible.bind(this.bath);this.bath.eligible=a=>!a.rest20&&!a.transit20&&!a.townAction19&&bathEligible(a);const bathVisit=this.bath.visit.bind(this.bath);this.bath.visit=a=>{const local=a.room==='bath',path=local?this.routes20.route('bath',a.pos,doors.bath):null;if(local&&!path)return false;const ok=bathVisit(a);if(ok&&local)a.cafePath=path;return ok;};}
 loadLife20(a){const pack=CHILL_LIFE_ASSETS20[a.key];if(!pack)return;a.life20={};let pending=pack.groups.length;for(const g of pack.groups){const im=new Image();im.onload=()=>{a.life20[g.name]=g.rects.map(rect=>{const [x,y,w,h]=rect,cv=document.createElement('canvas');cv.width=cv.height=256;const cx=cv.getContext('2d'),scale=g.name==='sleepLie'?Math.min(242/w,188/h):Math.min((g.name==='sleepSeat'?158:180)/h,226/w),nw=Math.round(w*scale),nh=Math.round(h*scale);cx.imageSmoothingEnabled=false;cx.drawImage(im,x,y,w,h,Math.round((256-nw)/2),g.name==='sleepLie'?Math.round((256-nh)/2):230-nh,nw,nh);const tx=new T.CanvasTexture(cv);tx.magFilter=tx.minFilter=T.NearestFilter;tx.generateMipmaps=false;tx.colorSpace=T.SRGBColorSpace;return tx;});if(g.name==='bag'){for(let i=0;i<3;i++)a.textures['bag_'+i]=a.life20.bag[i];const hands=a.key==='tetsu'?[[128,187],[109,160],[128,159]]:[[128,184],[110,166],[128,164]];a.bagSpec={frames:hands.map((heldItemAnchorPx,i)=>({bagAnchorPx:[128,a.key==='tetsu'?190:188],heldItemAnchorPx,activeHandAnchorPx:[105,heldItemAnchorPx[1]],supportHandAnchorPx:[151,i===1?188:heldItemAnchorPx[1]]}))};a.bagReady=true;}if(--pending===0)a.lifeReady20=true;};im.src=g.url;}}
 ownerAtDesk20(a){return a.room==='bath'&&!a.transit20&&!a.rest20&&!a.bathMode&&!a.arcadeMode&&a.pos.distanceTo(V(31.25,0,2.8))<.45;}
 follow20(a,path,dt){const target=path[0];if(!target)return true;const delta=target.clone().sub(a.pos),distance=delta.length(),step=Math.min(distance,a.speed*dt);if(distance>.00001){a.heading=delta.normalize();a.pos.addScaledVector(a.heading,step);a.motionMoving18=true;a.motionHeading18=a.heading.clone();a.walkDistance18=(a.walkDistance18||0)+step;}if(distance<=step+.001)path.shift();return !path.length;}
 eligibleArcade(a){return !!a&&!a.rest20&&!a.transit20&&!a.townAction19&&!a.routineRest&&!this.routine?.meta(a).rest&&this.routine?.window(a)?.type!=='sleep'&&(a.room==='bath'&&a.key==='nekokoo'&&!this.routine?.state.ownerMeal&&!a.bathMode&&!a.arcadeMode&&!a.cafePath?.length&&!a.path?.length&&!a.bagAnimation||super.eligibleArcade(a));}
 eligibleBag(a){return !a.rest20&&!a.transit20&&!a.townAction19&&(super.eligibleBag(a)||a.key==='nekokoo'&&a.room==='bath'&&a.bagReady&&!a.bathMode&&!a.arcadeMode&&!a.cafePath?.length&&!a.bagAnimation&&!this.routine.state.ownerMeal);}
 visit(a){if(a.key==='nekokoo'&&this.routine.state.ownerMeal)return false;if(a.rest20||a.transit20||a.townAction19||a.phase||a.path?.length||a.bagAnimation||a.arcadeMode||a.bathMode)return false;if(a.room==='bath'&&a.key==='nekokoo'){const target=this.routes20.landing('cafe',a),path=this.routes20.travel(a,'cafe',target);if(!path)return false;a.cafeOrigin20='bath';a.cafeMode='toCafe';a.cafePath=path;return true;}const ok=super.visit(a);if(ok){a.cafeOrigin20='home';const target=this.routes20.landing('cafe',a),tail=this.routes20.route('cafe',this.entry,target);if(tail)a.cafePath.push(...tail);}return ok;}
 leave(a){const ok=super.leave(a);if(!ok)return false;if(a.cafeOrigin20==='bath'){const first=this.routes20.route('cafe',V(a.pos.x-.85,0,a.pos.z),this.entry);if(first)a.cafePath=[V(a.pos.x-.85,0,a.pos.z),...first,V(14,0,5.3),V(28,0,5.3),doors.bath.clone(),...(this.routes20.route('bath',doors.bath,V(31.25,0,2.8))||[])];a.returnRoom20='bath';}else{const landing=this.routes20.landing('home',a);if(landing)a.cafePath.push(...(this.c.route(this.homeDoor,landing)||[]));}return true;}
 travelArcade(a,target,role){if(!this.eligibleArcade(a))return false;const path=this.routes20.travel(a,role.kind==='farm'?'farm':'arcade',target);if(!path)return false;a.arcadeOrigin=a.room;a.arcadeMode='travel';a.arcadeTarget=role;a.cafeMode=null;a.state='idle';a.path=[];a.cafePath=path;return true;}
 returnArcade(a){super.returnArcade(a);if(a.arcadeMode!=='return')return;const dest=a.arcadeOrigin||'home',landing=a.id===3?this.counter.clone():this.routes20.landing(dest,a),local=zone(a.pos),first=this.routes20.route(local,a.pos,doors[local]),last=landing&&this.routes20.route(dest,doors[dest],landing);if(first&&last)a.cafePath=[...first,V(doors[local].x,0,5.3),V(doors[dest].x,0,5.3),doors[dest].clone(),...last];}
 move(a,dt){let path=a.cafePath;if(!path?.length)return true;const target=path[0],room=zone(a.pos),same=room===zone(target)&&room!=='hall',doorLane=doors[room]&&Math.abs(a.pos.x-doors[room].x)<.3&&Math.abs(target.x-doors[room].x)<.3&&Math.max(a.pos.z,target.z)>3.4;if(same&&!doorLane&&a.pos.y<.05&&target.y<.05&&!['enter','exit'].includes(a.bathMode)){if(a.navPath20!==path||a.navTarget20!==target){const local=this.routes20.route(room,a.pos,target);if(local){path.splice(0,1,...local);a.navPath20=path;a.navTarget20=path[0];}else{a.navBlocked20=(a.navBlocked20||0)+dt;return false;}}}const out=super.move(a,dt);if(path[0]!==a.navTarget20)a.navTarget20=null;return out;}
 update(a,dt){if(a.id===0){this.routine?.plan();if(a.rest20||a.transit20||a.townAction19)this.arcadeTick(dt);}if(this.sleep20?.update(a,dt))return true;if(a.transit20){if(this.follow20(a,a.transit20.path,dt)){a.room=a.transit20.room;delete a.transit20;a.state='idle';a.timer=5;}return true;}const before=a.pos.clone(),oldCafe=a.cafeMode,oldBath=a.bathMode;let result=super.update(a,dt);if(oldCafe==='toHome'&&!a.cafeMode&&a.returnRoom20){a.room=a.returnRoom20;delete a.returnRoom20;}if(oldBath==='exit'&&a.bathMode==='return'&&a.bathOrigin==='bath'){a.cafePath=this.routes20.route('bath',a.pos,this.routes20.landing('bath',a))||a.cafePath;}if(oldBath==='return'&&!a.bathMode){const landing=this.routes20.landing(a.room,a),path=landing&&this.routes20.route(a.room,a.pos,landing);if(path?.length){a.transit20={path,room:a.room};}}
 if(a.transit20){if(this.follow20(a,a.transit20.path,dt)){a.room=a.transit20.room;delete a.transit20;a.state='idle';a.timer=5;}result=true;}
 if(a.room==='bath'&&a.key==='nekokoo'&&!a.bathMode&&!a.arcadeMode&&!a.cafeMode&&!a.bagAnimation&&!a.transit20&&!this.routine.state.ownerMeal){a.speech=Math.max(0,a.speech-dt);a.cafeWait-=dt;if(a.cafeWait<=0&&this.visit(a)){a.cafeWait=90;result=true;}else{a.timer-=dt;if(a.timer<=0){const target=a.pos.distanceTo(V(31.25,0,2.8))<.3?V(31.1,0,.8):V(31.25,0,2.8),path=this.routes20.route('bath',a.pos,target);if(path)a.transit20={path,room:'bath'};a.timer=12;}result=true;}}
 const delta=a.pos.clone().sub(before);if(delta.lengthSq()>.00000001){a.heading20=delta.normalize();a.lastMoved20=this.clock14;}return result;}
 menu(a){if(!a.addedResident)return super.menu(a);this.closeActivity();this.c.speak(a,a.key==='tetsu'?'拙者、今日は何をしようかでござる。':'オラも遊びに行きたいんだぞ。',5,true);this.c.modal(a.name,'<div class="shop-actions"><button id="lifeBag20">バッグ</button><button id="lifeCafe20">カフェへ誘う</button><button id="lifeGame20">ゲームへ誘う</button><button id="lifeSleep20">寝床で休む</button></div><p id="lifeStatus20" role="status"></p>');$('#lifeBag20').onclick=()=>this.bagMenu(a.id);const action=(id,fn)=>$(id).onclick=()=>{if(fn())$('#modal').close();else $('#lifeStatus20').textContent='今の用事が終わるか、空き場所ができてからお誘いください。';};action('#lifeCafe20',()=>{this.routine.manual.set(a.key,this.clock14+120);return this.visit(a);});action('#lifeGame20',()=>{const t=this.arcadeScene.targets.find(t=>t.kind==='gacha'&&!this.collections.busyDevice(t.device)&&!this.c.actors.some(b=>b.arcadeTarget?.device===t.device));return t&&this.travelArcade(a,t.seat,t);});action('#lifeSleep20',()=>{const modal=$('#modal');modal.close();const ok=this.sleep20.request(a);if(!ok)modal.showModal();return ok;});}
 say(a,n){if(a.key==='nekokoo')return['オラもひと休みするんだぞ。','落ち着く場所だぞ。','オラもカフェへ行くんだぞ。','のんびり待つんだぞ。','おいしいんだぞ！','温泉に戻るんだぞ。'][n%6];return super.say(a,n);}
 arcadeJoy(a,id){if(a.id<4)return super.arcadeJoy(a,id);this.reward('arcade:'+id+':'+a.id,a,'arcade');a.arcadeJoyTime=1.2;a.motionJoy18=2;this.c.speak(a,a.id===4?'うれしいでござる！':'オラ、うれしいんだぞ！',4,true);}
 installRaceDrivers(ids){super.installRaceDrivers(ids);for(let i=0;i<2;i++){const a=this.c.actors[ids[i]],driver=this.arcadeScene.carts[i].driver;if(a?.motion18&&driver)driver.material.map=a.motion18.frames[13];}}
 walkingTexture20(a,h,distance){const dir=direction(h,this.c.camera),step=Math.floor(distance/.18)%2;a.walkDirection=dir;if(a.motion18)return a.motion18.frames[a.motion18.groups[dir][step]];if(a.key==='irukaeru'&&a.life20?.walk)return a.life20.walk[{front:0,back:2,left:4,right:6}[dir]+step];if(a.key==='nyoro'){const prefix=(a.umbrella?'umbrella_':'')+'walk',name=prefix+(dir==='front'?'':'_'+dir)+'_'+String(step).padStart(2,'0');return a.textures[name];}return a.textures['walk_'+(dir==='left'||dir==='right'?'side':dir)+'_'+(step+1)];}
 afterRender(){super.afterRender();for(const a of this.c.actors){const actual=a.renderLast20?a.pos.clone().sub(a.renderLast20):V();a.renderLast20=a.pos.clone();if(actual.lengthSq()>.0000001){a.walkDistance20=(a.walkDistance20||0)+actual.length();a.heading20=actual.normalize();a.lastMoved20=this.clock14;}a.restSprite20&&(a.restSprite20.visible=false);a.restPlane20&&(a.restPlane20.visible=false);if(a.townOutside19)continue;const moved=this.clock14-(a.lastMoved20??-100)<.14,walking=!!(a.cafePath?.length||a.path?.length||a.transit20||a.rest20?.phase==='approach'||a.state==='moving'||a.phase?.point)&&moved;let heading=a.heading20||a.heading;if(walking&&heading){const tex=this.walkingTexture20(a,heading,a.walkDistance20||a.walkDistance18||0);if(tex){a.sprite.material.map=tex;a.sprite.material.rotation=0;const flip=a.id<2&&a.walkDirection==='left'?-1:1;a.sprite.scale.x=Math.abs(a.sprite.scale.x)*flip;}}else if(a.addedResident&&!a.bathMode&&!a.cafeMode&&!a.routineRest){if(a.bagAnimation){const pose=ChillBagMotion.pose(a);a.sprite.material.map=a.textures[pose]||(pose?.startsWith('meal_')?a.motion18?.frames[8+Number(pose.slice(5))]:null)||a.sprite.material.map;}else if(a.arcadeMode==='racing'||a.phase?.pose==='sit')a.sprite.material.map=a.motion18?.frames[13]||a.sprite.material.map;else if(a.phase?.pose==='joy')a.sprite.material.map=a.motion18?.frames[20+Math.floor(this.clock14*4)%4]||a.sprite.material.map;}
 if(a.addedResident&&a.rest20?.phase!=='sleep'){const visible=this.view===zone(a.pos);a.sprite.visible=visible;a.shadow.visible=visible&&!['soak','exitWait'].includes(a.bathMode);if(['seated','eating','satisfied'].includes(a.cafeMode)||a.phase?.pose==='sit')a.contactDepth.value=1;}
 if(a.bagAnimation&&a.addedResident){a.sprite.center.set(.5,26/256);a.sprite.scale.setScalar(a.key==='tetsu'?1.32:1.65);ChillBagMotion.render(a,this);}
 this.sleep20.render(a);const proxy=this.town14.residentProxies.find(p=>p.a===a);if(proxy&&a.rest20?.phase==='approach'&&a.rest20.origin!==a.rest20.place.room){const s=a.rest20;if(!s.townRoute){s.townRoute=this.townNavigation.route(s.origin,s.place.room);let prev=a.pos;s.townTotal=s.path.reduce((sum,p)=>{const d=prev.distanceTo(p);prev=p;return sum+d;},0);}let prev=a.pos;const remain=s.path.reduce((sum,p)=>{const d=prev.distanceTo(p);prev=p;return sum+d;},0),u=clamp(1-remain/(s.townTotal||1)),route=s.townRoute;const lengths=route.slice(1).map((p,i)=>p.distanceTo(route[i]));let left=u*lengths.reduce((n,d)=>n+d,0);for(let i=0;i<lengths.length;i++){if(left<=lengths[i]){proxy.sprite.position.copy(route[i]).lerp(route[i+1],left/(lengths[i]||1));break;}left-=lengths[i];}proxy.sprite.visible=this.view==='town';}if(proxy?.sprite.visible){const d=proxy.last20?proxy.sprite.position.clone().sub(proxy.last20):V();proxy.last20=proxy.sprite.position.clone();if(d.lengthSq()>.00001){proxy.distance20=(proxy.distance20||0)+d.length();const tex=this.walkingTexture20(a,d.normalize(),proxy.distance20);if(tex)proxy.sprite.material.map=tex;const flip=a.id<2&&a.walkDirection==='left'?-1:1;proxy.sprite.scale.x=Math.abs(proxy.sprite.scale.x)*flip;}}}}
 serialize(){return{...super.serialize(),life20:{v:1,residents:this.c.actors.map(a=>({id:a.id,room:a.room,point:a.pos.toArray(),rest:!!a.rest20}))}};}
 restore(raw){super.restore(raw);if(!this.sleep20)return;this.sleep20.restore();for(const a of this.c.actors){a.transit20=null;a.navPath20=null;a.navTarget20=null;this.arcadeNext[a.id]=this.arcadeClock+40+a.id*9;this.bagIdle[a.id]=30+a.id*7;if(a.addedResident){a.npcPose='idle';a.npcOutdoor=a.npcWalking=false;a.timer=3+a.id;const saved=raw?.life20?.residents?.find(s=>s.id===a.id);if(saved&&!a.bathMode&&!a.cafeMode&&['home','bath'].includes(saved.room)){a.room=saved.room;const safe=this.routes20.landing(a.room,a);if(safe)a.pos.copy(safe);}}}}
};
window.ChillInteriorRoutes20=InteriorRoutes20;
})();
