/* Furniture editing and additional recipes; all coordinates are room-local. */
(()=>{'use strict';
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x)),copy=x=>JSON.parse(JSON.stringify(x));
const names={sofa:'ソファ',bed:'ベッド',table:'食事テーブル',shelf:'本棚',plant:'植物',deck:'音楽台',oven:'オーブン',stove:'コンロ',tv:'テレビ',pc:'PCデスク',sideTable:'小テーブル',pan:'フライパン',pot:'鍋'};
window.CHILL_RECIPES={dorayaki:{name:'どら焼き',station:'oven',cost:{wheat:1,beans:1},seconds:60},omelet:{name:'卵焼き',station:'pan',cost:{egg:1},seconds:60},soup:{name:'コーンスープ',station:'pot',cost:{corn:1,milk:1},seconds:60}};
window.CHILL_INITIAL_PANTRY={egg:10,corn:10,milk:10,omelet:0,soup:0};const recipes=window.CHILL_RECIPES,ingredients={wheat:'小麦',beans:'小豆',egg:'卵',corn:'とうもろこし',milk:'牛乳'};
const R=ChillRoom.prototype,oldConfigs=R.configs,oldCreate=R.create,oldLayout=R.applyLayout;
R.configs=function(){return oldConfigs.call(this).map(c=>({...c,stove:[-2.3,3.1,Math.PI],tv:[3.6,-2.05,0],pc:[-2.4,3.1,Math.PI],sideTable:[1.7,-.4,0]}))};
R.create=function(key,...args){let f=oldCreate.call(this,key,...args),b=(...a)=>this.box(f.group,...a),c=(...a)=>this.cyl(f.group,...a);if(key==='stove'){f.w=1.1;f.d=.8;b(0,.3,0,1.1,.55,.78,'#b7c7ba');b(0,.61,0,1.18,.07,.84,this.cream);f.vessels={};for(let [i,k]of ['pan','pot'].entries()){let x=i?.29:-.29;c(x,.66,0,.225,.225,.04,'#59655a');let fire=new THREE.Mesh(new THREE.TorusGeometry(.16,.028,6,18),new THREE.MeshBasicMaterial({color:'#f9b057'}));fire.rotation.x=Math.PI/2;fire.position.set(x,.69,0);f.group.add(fire);let g=new THREE.Group();g.position.set(x,.72,0);f.group.add(g);let edible;
if(k==='pan'){this.cyl(g,0,0,0,.22,.21,.05,'#555c56');this.box(g,0,.012,.34,.075,.04,.32,this.wood);edible=this.box(g,0,.047,0,.24,.055,.16,new THREE.MeshStandardMaterial({color:'#ffe294',roughness:.9}));}else{let wall=new THREE.Mesh(new THREE.CylinderGeometry(.205,.19,.18,24,1,true),new THREE.MeshStandardMaterial({color:'#d3ad83',side:THREE.DoubleSide}));wall.position.y=.07;g.add(wall);this.cyl(g,0,-.02,0,.19,.19,.02,'#b89776');let rim=new THREE.Mesh(new THREE.TorusGeometry(.20,.022,6,20),this.cream);rim.rotation.x=Math.PI/2;rim.position.y=.16;g.add(rim);for(let xx of [-.24,.24])this.box(g,xx,.09,0,.09,.035,.075,this.wood);edible=this.cyl(g,0,.16,0,.177,.177,.015,new THREE.MeshStandardMaterial({color:'#f5dd99'}));for(let j=0;j<5;j++){let corn=this.cyl(g,Math.sin(j*3)*.10,.174,Math.cos(j*3)*.10,.025,.025,.018,'#f7c744',8);edible.add(corn);corn.position.y=.014;}}
let steam=[];for(let j=0;j<4;j++){let o=new THREE.Mesh(new THREE.SphereGeometry(.042,6,6),new THREE.MeshBasicMaterial({color:'#eee9dc',transparent:true,opacity:0,depthWrite:false}));g.add(o);steam.push(o)}f.vessels[k]={group:g,fire,edible,steam};}f.sockets.entry=new THREE.Vector3(0,0,1.07);}
if(key==='tv'){f.w=1.35;f.d=.48;b(0,.26,0,1.3,.46,.46,this.oak);b(0,.84,0,1.25,.72,.10,'#4b5b54');f.screen=b(0,.85,.057,1.12,.60,.015,new THREE.MeshStandardMaterial({color:'#92b6ab',emissive:'#8dafa2',emissiveIntensity:.2}));b(-.16,.8,.075,.52,.15,.02,'#d5dac1');b(.28,1,.075,.17,.16,.02,'#ede2af');f.sockets.entry=new THREE.Vector3(0,0,1.0);}
if(key==='pc'){f.w=1.25;f.d=.65;b(0,.46,0,1.25,.09,.65,this.oak);for(let x of [-.51,.51])b(x,.22,0,.07,.45,.48,this.wood);b(0,.75,-.18,.64,.45,.06,'#53695f');f.screen=b(0,.76,-.14,.55,.34,.012,new THREE.MeshStandardMaterial({color:'#b7c6b3',emissive:'#acc6ac',emissiveIntensity:.2}));b(0,.526,.12,.52,.024,.20,'#e8e2cf');for(let x=-.2;x<=.2;x+=.08)b(x,.541,.12,.045,.008,.13,'#899584');f.sockets.entry=new THREE.Vector3(0,0,1.0);}
if(key==='sideTable'){f.w=.7;f.d=.7;c(0,.56,0,.35,.35,.06,this.oak);c(0,.28,0,.065,.17,.54,this.cream);}
return f;};
R.applyLayout=function(index){oldLayout.call(this,index);this.arrangement=this.arrangement||{};this.rebuildPlacement();};
R.rebuildPlacement=function(){this.bounds=[];for(let [k,f]of Object.entries(this.furniture)){let a=this.arrangement[k],base=this.configs()[this.layout][k];f.group.position.set(a?.x??base[0],0,a?.z??base[1]);f.group.rotation.y=a?.rotation??base[2];f.group.visible=a?.visible??!['tv','pc','sideTable'].includes(k);if(k==='stove')for(let v of ['pan','pot'])f.vessels[v].group.visible=this.arrangement[v]?.visible!==false;if(!f.group.visible)continue;let r=f.group.rotation.y;this.bounds.push({key:k,x:f.group.position.x,z:f.group.position.z,w:Math.abs(Math.cos(r))*f.w+Math.abs(Math.sin(r))*f.d+.36,d:Math.abs(Math.sin(r))*f.w+Math.abs(Math.cos(r))*f.d+.36});}this.bounds.push({key:'lamp',x:-4.5,z:2.85,w:.7,d:.7});this.scene.updateMatrixWorld(true);};
R.propose=function(key,values){let next=copy(this.arrangement);const f=this.furniture[key];next[key]={...(f?{x:f.group.position.x,z:f.group.position.z,rotation:f.group.rotation.y,visible:f.group.visible}:{visible:this.arrangement[key]?.visible!==false}),...values};return next;};
R.validateArrangement=function(next,kitchen,food){let boxes=[],points=[[-.8,1.4],[.8,1.4],[0,1.45],[.7,1.45],[-1.15,1.45],[-1.65,2.05],[-2.3,-3.12],[-.4,.4],[0,.25],[.65,.25]],sockets=[];for(let k of ['pan','pot'])if(kitchen?.stove?.[k]&&JSON.stringify(next[k]||{})!==JSON.stringify(this.arrangement[k]||{}))return '調理中・完成品がある器具は、受取後に収納できます。';
for(let [k,f]of Object.entries(this.furniture)){let a=next[k]||{},old=this.arrangement[k]||{},base=this.configs()[this.layout][k],x=a.x??base[0],z=a.z??base[1],r=a.rotation??base[2],visible=a.visible??!['tv','pc','sideTable'].includes(k);if((k==='oven'&&kitchen?.batch||k==='stove'&&Object.values(kitchen?.stove||{}).some(Boolean)||k==='table'&&food)&&JSON.stringify(a)!==JSON.stringify(old))return k==='table'?'配膳した料理がなくなってから動かせます。':'調理器具は料理を受け取ってから動かせます。';if(!visible)continue;if(![x,z,r].every(Number.isFinite))return '位置を数字で指定してください。';let w=Math.abs(Math.cos(r))*f.w+Math.abs(Math.sin(r))*f.d+.36,d=Math.abs(Math.sin(r))*f.w+Math.abs(Math.cos(r))*f.d+.36;if(Math.abs(x)+(w-.36)/2>5||Math.abs(z)+(d-.36)/2>4)return '家具が部屋の外へ出ています。';boxes.push({x,z,w,d,k});let p=f.sockets.entry;if(p)sockets.push([x+p.x*Math.cos(r)+p.z*Math.sin(r),z-p.x*Math.sin(r)+p.z*Math.cos(r)]);}
boxes.push({x:-4.5,z:2.85,w:.7,d:.7,k:'lamp'});for(let i=0;i<boxes.length;i++)for(let j=0;j<i;j++){let a=boxes[i],b=boxes[j];if(Math.abs(a.x-b.x)<(a.w+b.w)/2-.015&&Math.abs(a.z-b.z)<(a.d+b.d)/2-.015)return '家具が近すぎます。少し離してください。';}
const valid=(x,z)=>x>=-4.6&&x<=4.6&&z>=-3.55&&z<=3.65&&!boxes.some(b=>Math.abs(x-b.x)<b.w/2&&Math.abs(z-b.z)<b.d/2);if([...points,...sockets].some(([x,z])=>!valid(x,z)))return '家具の前と中央の通り道を空けてください。';
const step=.2,cols=47,rows=37,key=(x,z)=>Math.round((x+4.6)/step)+','+Math.round((z+3.55)/step),seen=new Set(),q=[[23,25]];for(let i=0;i<q.length;i++){let [cx,cz]=q[i],id=cx+','+cz;if(seen.has(id)||cx<0||cx>=cols||cz<0||cz>=rows||!valid(-4.6+cx*step,-3.55+cz*step))continue;seen.add(id);q.push([cx+1,cz],[cx-1,cz],[cx,cz+1],[cx,cz-1]);}for(let [x,z]of [...points,...sockets]){let [ix,iz]=key(x,z).split(',').map(Number),reachable=false;for(let dx=-1;dx<=1;dx++)for(let dz=-1;dz<=1;dz++){let nx=ix+dx,nz=iz+dz,tx=-4.6+nx*step,tz=-3.55+nz*step;if(seen.has(nx+','+nz)&&Array.from({length:7},(_,i)=>valid(x+(tx-x)*i/6,z+(tz-z)*i/6)).every(Boolean))reachable=true;}if(!reachable)return '家具へ向かう通路がふさがっています。';}return null;};
R.openFurniture=function(hooks){let key=this.editKey||'table';const render=()=>{this.editKey=key;let f=this.furniture[key],a=f?{x:f.group.position.x,z:f.group.position.z,rotation:f.group.rotation.y,visible:f.group.visible}:{visible:this.arrangement[key]?.visible!==false};if(this.editDraft?.key===key)a={...a,...this.editDraft.values};hooks.modal('家具の配置と収納',`<div class="furniture-editor"><label>家具 <select id="furnitureKey">${Object.entries(names).map(([k,n])=>`<option value="${k}" ${k===key?'selected':''}>${n}</option>`).join('')}</select></label><label><input type="checkbox" id="furnitureVisible" ${a.visible?'checked':''}> 部屋に出す</label>${f?`<div class="coordinates"><label>横の位置 <input id="furnitureX" type="number" min="-4.5" max="4.5" step="0.25" value="${a.x}"></label><label>奥行き <input id="furnitureZ" type="number" min="-3.5" max="3.5" step="0.25" value="${a.z}"></label><label>向き <select id="furnitureRotation">${[0,1,2,3].map(i=>`<option value="${i*Math.PI/2}" ${Math.abs((a.rotation+Math.PI*2)%(Math.PI*2)-i*Math.PI/2)<.01?'selected':''}>${i*90}°</option>`).join('')}</select></label></div>`:'<p>鍋とフライパンはコンロ上に置きます。</p>'}<p class="caption">横：左−／右＋、奥行き：窓側−／手前＋。中央と家具の前は通路です。使用中は作業終了を待ちます。</p><button id="furniturePreview">位置をプレビュー</button><button id="furnitureApply" class="primary">この配置にする</button><p id="furnitureMessage" role="status"></p></div>`);document.querySelector('#furnitureKey').onchange=e=>{key=e.target.value;render()};const proposal=()=>this.propose(key,{visible:document.querySelector('#furnitureVisible').checked,...(f?{x:+document.querySelector('#furnitureX').value,z:+document.querySelector('#furnitureZ').value,rotation:+document.querySelector('#furnitureRotation').value}:{})});document.querySelector('#furnitureApply').onclick=()=>{let next=proposal(),error=hooks.change(next);document.querySelector('#furnitureMessage').textContent=error||'作業終了を待って配置を変えます。';if(!error){this.editDraft=null;document.querySelector('#modal').close()}};document.querySelector('#furniturePreview').onclick=()=>{let next=proposal(),error=this.validateArrangement(next,hooks.kitchen(),hooks.food());document.querySelector('#furnitureMessage').textContent=error||'プレビュー中。部屋に戻って位置を確認できます。';this.clearPreview();if(!error)this.editDraft={key,values:next[key]};if(!error&&f){let g=new THREE.Group(),m=new THREE.MeshBasicMaterial({color:'#90b688',transparent:true,opacity:.38,depthWrite:false}),o=new THREE.Mesh(new THREE.BoxGeometry(f.w,.2,f.d),m),a=next[key];o.position.set(a.x,.18,a.z);o.rotation.y=a.rotation;g.add(o);this.scene.add(g);this.preview=g;}};};render();};

const Base=window.ChillKitchen;
window.ChillKitchen=class extends Base{
reset(){super.reset();Object.assign(this.inventory,window.CHILL_INITIAL_PANTRY);this.stove={pan:null,pot:null};}
serialize(){return{...super.serialize(),v:2,stove:copy(this.stove)}}
restore(d){super.restore(d?{...d,v:1}:d);const n=x=>Number.isSafeInteger(x)&&x>=0?Math.min(x,999999):0;for(let k of ['egg','corn','milk','omelet','soup'])this.inventory[k]=d?.v>=2?n(d.inventory?.[k]):window.CHILL_INITIAL_PANTRY[k];this.stove={pan:null,pot:null};for(let k of ['pan','pot']){let b=d?.stove?.[k];if(b&&recipes[b.recipe]?.station===k&&['baking','ready'].includes(b.status)&&Number.isFinite(b.startedAt)&&b.endsAt-b.startedAt===recipes[b.recipe].seconds*1000)this.stove[k]={...b}}}
available(station){return station==='oven'?this.room.furniture.oven.group.visible:this.room.furniture.stove.group.visible&&this.room.furniture.stove.vessels[station].group.visible}
start(){if(!this.available('oven')){this.hooks.toast('オーブンを部屋に出してください。');return false}return super.start()}
startRecipe(id){let r=recipes[id];if(!r)return false;if(id==='dorayaki')return this.start();this.update();if(!this.available(r.station)||this.stove[r.station])return false;if(Object.entries(r.cost).some(([k,n])=>this.inventory[k]<n))return false;const now=Date.now();let ok=this.transaction(()=>{for(let [k,n]of Object.entries(r.cost))this.inventory[k]-=n;this.stove[r.station]={recipe:id,status:'baking',startedAt:now,endsAt:now+r.seconds*1000}});if(ok){this.hooks.toast(r.name+'を作ります。じっくり60秒。');this.hooks.tone(330)}return ok}
collectRecipe(id){let r=recipes[id];if(id==='dorayaki')return super.collect();this.update();if(!r||this.stove[r.station]?.status!=='ready')return false;return this.transaction(()=>{this.inventory[id]++;this.stove[r.station]=null})}
update(){let now=super.update();for(let [k,b]of Object.entries(this.stove||{}))if(b?.status==='baking'&&now>=b.endsAt){b.status='ready';this.hooks.save();this.hooks.toast(recipes[b.recipe].name+'ができました。');this.hooks.tone(740)}return now}
open(){this.hooks.modal('小さなキッチン',`<div class="kitchen-store">${Object.entries(ingredients).map(([k,n])=>`<span>${n} <b data-stock="${k}"></b></span>`).join('')}</div><div class="recipe-list">${Object.entries(recipes).map(([id,r])=>`<section><h3>${r.name}<small>${r.station==='oven'?'オーブン':r.station==='pan'?'フライパン':'鍋'}</small></h3><p>${Object.entries(r.cost).map(([k,n])=>ingredients[k]+' '+n).join(' ＋ ')} ／ ${r.seconds}秒</p><div class="bake-track"><i data-progress="${id}"></i></div><p data-state="${id}"></p><button class="primary" data-start="${id}">材料を入れる</button><button class="primary" data-collect="${id}">受け取る</button><span> 所持 <b data-stock="${id}"></b></span></section>`).join('')}</div><p class="oven-note">実時間で調理します。画面を閉じても完成時刻は変わりません。材料は自動補充されません。</p>`);document.querySelectorAll('[data-start]').forEach(b=>b.onclick=()=>this.startRecipe(b.dataset.start));document.querySelectorAll('[data-collect]').forEach(b=>b.onclick=()=>this.collectRecipe(b.dataset.collect));this.render();document.querySelector('#modal').scrollTop=0;}
serveMenu(){this.hooks.modal('料理をテーブルへ',`<p>ふたりが好きなときに食べます。テーブルには1品ずつ。</p><div class="meal-choices">${Object.entries(recipes).map(([id,r])=>`<button data-serve="${id}" ${this.inventory[id]<1?'disabled':''}>${r.name} <b>${this.inventory[id]}</b></button>`).join('')}</div>`);document.querySelectorAll('[data-serve]').forEach(b=>b.onclick=()=>{if(this.hooks.serve(b.dataset.serve))document.querySelector('#modal').close()});}
render(){super.render();let now=Date.now();document.querySelectorAll('[data-stock]').forEach(e=>e.textContent=this.inventory[e.dataset.stock]);for(let [id,r]of Object.entries(recipes)){let b=id==='dorayaki'?this.batch:this.stove[r.station],remaining=b?Math.max(0,Math.ceil((b.endsAt-now)/1000)):0,active=this.available(r.station),state=document.querySelector('[data-state="'+id+'"]');if(state){state.textContent=!active?'部屋づくりで器具を出してください。':b?.status==='ready'?'できあがり！':b?'あと '+remaining+' 秒':Object.entries(r.cost).some(([k,n])=>this.inventory[k]<n)?'材料が足りません。':'準備できています。';let start=document.querySelector('[data-start="'+id+'"]'),collect=document.querySelector('[data-collect="'+id+'"]');start.disabled=!active||!!b||Object.entries(r.cost).some(([k,n])=>this.inventory[k]<n);collect.hidden=b?.status!=='ready';document.querySelector('[data-progress="'+id+'"]').style.width=(b?clamp((now-b.startedAt)/(r.seconds*1000),0,1)*100:0)+'%';}
if(r.station!=='oven'){let v=this.room.furniture.stove.vessels[r.station],b=this.stove[r.station],progress=b?clamp((now-b.startedAt)/(r.seconds*1000),0,1):0;v.fire.visible=!!b&&b.status==='baking'&&v.group.visible&&this.room.furniture.stove.group.visible;v.fire.scale.setScalar(1+.06*Math.sin(now/120));v.edible.visible=!!b;v.edible.material.color.set(id==='omelet'?'#ffe394':'#f2dc96').lerp(new THREE.Color(id==='omelet'?'#d8a14d':'#e5c56f'),progress);if(id==='soup')v.edible.position.y=.16+(b?.status==='baking'?Math.sin(now/170)*.006:0);v.steam.forEach((o,i)=>{let t=(now/1900+i*.23)%1;o.visible=!!b;o.position.set(Math.sin(i*2)*.12,.21+t*.55,Math.cos(i*2)*.12);o.scale.setScalar(.5+t);o.material.opacity=b?(1-t)*.17:0});}}
// World labels use the same persisted end timestamps as the recipe panel.
this.labels=this.labels||{};for(let station of ['oven','stove']){let f=this.room.furniture[station];if(!this.labels[station]){let el=document.createElement('div');el.className='cooking-label';document.querySelector('#labels').appendChild(el);this.labels[station]=el}let batches=station==='oven'?[this.batch]:Object.values(this.stove),texts=batches.filter(Boolean).map(b=>b.status==='ready'?'できあがり':Math.max(0,Math.ceil((b.endsAt-now)/1000))+'秒');this.labels[station].textContent=texts.join(' / ');this.labels[station].hidden=!texts.length||!f.group.visible;}
let oven=this.room.furniture.oven.oven;if(this.batch?.status==='baking')oven.steam.forEach((o,i)=>{let t=(now/2200+i*.21)%1;o.visible=true;o.position.set(Math.sin(i*2)*.10,1+t*.6,-.05);o.scale.setScalar(.45+t*.7);o.material.opacity=(1-t)*.10});
const button=document.querySelector('#ovenButton');if(button)button.textContent=[this.batch,...Object.values(this.stove)].some(b=>b?.status==='ready')?'できた！':'調理';
}
};
window.ChillLiving={names,recipes,positionLabels(kitchen,camera,w,h){for(let [key,el]of Object.entries(kitchen.labels||{})){let p=kitchen.room.furniture[key].group.position.clone().add(new THREE.Vector3(0,1.25,0)).project(camera);el.style.left=clamp((p.x*.5+.5)*w,65,w-65)+'px';el.style.top=clamp((-.5*p.y+.5)*h,100,h-180)+'px';}},
sleepVolume(a){if(!a.sleepLayers){const g=new THREE.PlaneGeometry(1,1,24,24),v=g.attributes.position;for(let i=0;i<v.count;i++){let x=v.getX(i),y=v.getY(i);v.setZ(i,.075*Math.max(0,1-(x/.42)**2-(y/.34)**2))}g.computeVertexNormals();a.sleepPlane.geometry.dispose();a.sleepPlane.geometry=g;a.sleepLayers=[];for(let i=0;i<3;i++){let m=a.sleepPlane.material.clone();m.color.set(i?'#eee5cc':'#c9c3af');let layer=new THREE.Mesh(new THREE.PlaneGeometry(1,1),m);layer.rotation.copy(a.sleepPlane.rotation);a.sleepGroup.add(layer);a.sleepLayers.push(layer)}}for(let [i,l]of a.sleepLayers.entries()){l.material.map=a.sleepPlane.material.map;l.position.copy(a.sleepPlane.position);l.position.y=.005+i*.015;l.scale.copy(a.sleepPlane.scale)}},
meal(snack,food,actor){if(!snack.mealGroups){snack.dorayakiParts=[...snack.children];snack.mealGroups={};let egg=new THREE.Group(),soup=new THREE.Group();for(let i=0;i<3;i++){let o=new THREE.Mesh(new THREE.BoxGeometry(.10,.09,.19),new THREE.MeshStandardMaterial({color:i%2?'#edc35d':'#f3d479',roughness:.9}));o.position.set((i-1)*.105,.025,0);egg.add(o)}let bowl=new THREE.Mesh(new THREE.CylinderGeometry(.185,.13,.14,22),new THREE.MeshStandardMaterial({color:'#e6cfb3'}));bowl.position.y=.055;soup.add(bowl);let liquid=new THREE.Mesh(new THREE.CylinderGeometry(.163,.163,.012,22),new THREE.MeshStandardMaterial({color:'#efd477'}));liquid.position.y=.13;soup.add(liquid);for(let j=0;j<4;j++){let c=new THREE.Mesh(new THREE.SphereGeometry(.023,7,6),new THREE.MeshStandardMaterial({color:'#eabd44'}));c.position.set(Math.sin(j*3)*.09,.144,Math.cos(j*3)*.09);soup.add(c)}snack.add(egg,soup);snack.mealGroups={omelet:egg,soup};}let kind=food?.kind||'dorayaki';snack.dorayakiParts.forEach(o=>o.visible=kind==='dorayaki');for(let [k,g]of Object.entries(snack.mealGroups))g.visible=k===kind;let u=actor?.phase?.hold==='food'?clamp(actor.phaseTime/actor.phase.duration,0,1):0;if(kind==='soup'){snack.scale.setScalar(1);snack.mealGroups.soup.children[1].position.y=.13-u*.09;snack.mealGroups.soup.children.slice(2).forEach(o=>o.visible=u<.8)}if(kind==='omelet'){snack.scale.setScalar(1);snack.mealGroups.omelet.children.forEach((o,i)=>o.visible=i>=Math.floor(u*3))}}
};
})();
