/* Touch editor uses discrete steps; scrolling never drags scene furniture. */
(()=>{'use strict';
const $=s=>document.querySelector(s);
ChillRoom.prototype.openFurniture=function(h){
 if(this.mobileEditor)return;const panel=document.createElement('section');panel.id='furnitureSheet';panel.setAttribute('aria-label','家具の配置編集');this.mobileEditor=panel;document.body.appendChild(panel);let key=this.editKey||'table',values,outline;
 const cleanup=()=>{this.clearPreview();if(outline){this.scene.remove(outline);outline.geometry.dispose();outline.material.dispose();}panel.remove();this.mobileEditor=null;h.layout();};
 const select=()=>{this.editKey=key;let f=this.furniture[key];values=f?{x:f.group.position.x,z:f.group.position.z,rotation:f.group.rotation.y,visible:f.group.visible}:{visible:this.arrangement[key]?.visible!==false};render();preview();};
 const proposal=()=>this.propose(key,values);
 const preview=()=>{this.clearPreview();if(outline){this.scene.remove(outline);outline.geometry.dispose();outline.material.dispose();outline=null;}let f=this.furniture[key],error=this.validateArrangement(proposal(),h.kitchen(),h.food());$('#placementStatus').textContent=error||'緑の枠が変更後の位置です。確定するまで元の家具は動きません。';$('#placementStatus').classList.toggle('error',!!error);if(f&&values.visible){let g=new THREE.Group(),o=new THREE.Mesh(new THREE.BoxGeometry(f.w,.1,f.d),new THREE.MeshBasicMaterial({color:error?'#c06d57':'#53945b',transparent:true,opacity:.5}));o.position.set(values.x,.15,values.z);o.rotation.y=values.rotation;g.add(o);this.scene.add(g);this.preview=g;outline=new THREE.BoxHelper(f.group,'#e3a340');this.scene.add(outline);}$('#placementCoords').textContent=f?'横 '+values.x.toFixed(2)+' ／ 奥行 '+values.z.toFixed(2)+' ／ '+Math.round(values.rotation*180/Math.PI)%360+'°': 'コンロ上の器具';};
 const render=()=>{panel.innerHTML='<div class="furniture-title"><strong>家具を選んで配置</strong><button id="cancelFurniture">キャンセル</button></div><label>選択中 <select id="mobileFurnitureKey">'+Object.entries(ChillLiving.names).map(([k,n])=>'<option value="'+k+'" '+(k===key?'selected':'')+'>'+n+'</option>').join('')+'</select></label><div class="move-pad"><button data-move="0,-0.25" aria-label="奥へ移動">奥へ ↑</button><button data-move="-0.25,0" aria-label="左へ移動">← 左へ</button><button id="rotateFurniture">90°回転</button><button data-move="0.25,0" aria-label="右へ移動">右へ →</button><button data-move="0,0.25" aria-label="手前へ移動">手前 ↓</button></div><div class="placement-actions"><button id="storeFurniture">'+(values.visible?'収納する':'部屋に出す')+'</button><button id="applyFurniture" class="primary">配置を確定</button></div><output id="placementCoords"></output><p id="placementStatus" role="status"></p>';
 $('#cancelFurniture').onclick=cleanup;$('#mobileFurnitureKey').onchange=e=>{key=e.target.value;select();};panel.querySelectorAll('[data-move]').forEach(b=>{b.disabled=!this.furniture[key];b.onclick=()=>{let [x,z]=b.dataset.move.split(',').map(Number);values.x+=x;values.z+=z;preview();};});$('#rotateFurniture').disabled=!this.furniture[key];$('#rotateFurniture').onclick=()=>{values.rotation=(values.rotation+Math.PI/2)%(2*Math.PI);preview();};$('#storeFurniture').onclick=()=>{values.visible=!values.visible;render();preview();};$('#applyFurniture').onclick=()=>{let error=h.change(proposal());if(error){$('#placementStatus').textContent=error;return;}cleanup();};};
 panel.addEventListener('keydown',e=>{if(e.key==='Escape')cleanup();});select();h.layout();
};
// The door approach remains clear for every accepted future arrangement.
const validate=ChillRoom.prototype.validateArrangement;
ChillRoom.prototype.validateArrangement=function(next,k,f){let error=validate.call(this,next,k,f);if(error)return error;for(let [id,item]of Object.entries(this.furniture)){let a=next[id]||{},base=this.configs()[this.layout][id];if(!(a.visible??!['tv','pc','sideTable'].includes(id)))continue;let r=a.rotation??base[2],w=Math.abs(Math.cos(r))*item.w+Math.abs(Math.sin(r))*item.d+.4,d=Math.abs(Math.sin(r))*item.w+Math.abs(Math.cos(r))*item.d+.4;if(Math.abs((a.x??base[0])-1.9)<w/2&&Math.abs((a.z??base[1])-3.45)<d/2)return '家のドア前を空けてください。';}return null;};
const render=ChillKitchen.prototype.render;
ChillKitchen.prototype.collectReady=function(station){this.update();if(!this.available(station)||this.hooks.canCook?.()===false||$('#modal').open)return false;let id=Object.keys(CHILL_RECIPES).find(k=>CHILL_RECIPES[k].station===station),batch=station==='oven'?this.batch:this.stove[station];if(batch?.status!=='ready')return false;return this.transaction(()=>{this.inventory[id]++;if(station==='oven')this.batch=null;else this.stove[station]=null;});};
ChillKitchen.prototype.render=function(){render.call(this);Object.values(this.labels||{}).forEach(e=>e.hidden=true);this.readyLabels=this.readyLabels||{};for(let [id,r]of Object.entries(CHILL_RECIPES)){let el=this.readyLabels[r.station];if(!el){el=document.createElement('button');el.className='cooking-bubble';el.setAttribute('aria-label',r.name+'の完成品を回収');$('#labels').appendChild(el);el.onclick=e=>{e.stopPropagation();let batch=r.station==='oven'?this.batch:this.stove[r.station];if(batch?.status==='ready'){if(this.collectReady(r.station))this.hooks.toast(r.name+'を1個受け取りました。');}else this.openStation(r.station);};this.readyLabels[r.station]=el;}let b=r.station==='oven'?this.batch:this.stove[r.station],ready=b?.status==='ready';el.classList.toggle('complete',ready);el.classList.toggle('station-idle',!b&&r.station!=='oven');el.textContent=ready?({dorayaki:'🥞',omelet:'🍳',soup:'🥣'}[id]+' 完成！'):b?Math.max(0,Math.ceil((b.endsAt-Date.now())/1000))+'秒':r.station==='pan'?'フライパン':r.station==='pot'?'鍋':'';el.disabled=false;el.hidden=(!b&&r.station==='oven')||!this.available(r.station)||this.hooks.canCook?.()===false||$('#modal').open;}}
ChillLiving.positionLabels=function(k,camera,w,h){for(let [s,el]of Object.entries(k.readyLabels||{})){if(el.hidden)continue;let f=k.room.furniture[s==='oven'?'oven':'stove'],p=s==='oven'?f.group.localToWorld(new THREE.Vector3(0,1.2,.2)):f.vessels[s].group.localToWorld(new THREE.Vector3(0,.35,0));p.project(camera);if(p.z>1||p.x<-.95||p.x>.95||p.y<-.95||p.y>.95){el.hidden=true;continue;}el.style.left=(p.x*.5+.5)*w+'px';el.style.top=(-p.y*.5+.5)*h+'px';}let pan=k.readyLabels.pan,pot=k.readyLabels.pot;if(pan&&!pan.hidden&&pot&&!pot.hidden){let a=pan.getBoundingClientRect(),b=pot.getBoundingClientRect();if(a.left<b.right&&a.right>b.left&&a.top<b.bottom&&a.bottom>b.top)pot.style.top=(parseFloat(pot.style.top)-52)+'px';}};
})();
