/* Layered, articulated player. Clothing never changes the black body or silent face. */
(()=>{'use strict';const T=THREE,V=(x=0,y=0,z=0)=>new T.Vector3(x,y,z);
const palette=['#f0e4c5','#88bfa9','#a3b9df','#dfabc4','#f2cd68'];
class Player24{
 constructor(cafe){this.cafe=cafe;this.c=cafe.c;this.room='myhome';this.pos=V(192,0,2.8);this.heading=0;this.path=[];this.motion='idle';this.time=0;this.distance=0;this.wear={hat:0,poncho:0,glasses:0,accessory:0,special:false};this.group=new T.Group();this.group.name='silent-player';this.c.scene.add(this.group);this.layers={};this.build();}
 mat(c){return new T.MeshToonMaterial({color:c});}
 mesh(g,geo,c,x=0,y=0,z=0){const m=new T.Mesh(geo,this.mat(c));m.position.set(x,y,z);m.castShadow=true;g.add(m);return m;}
 ball(g,x,y,z,rx,ry,rz,c){const m=this.mesh(g,new T.SphereGeometry(1,24,16),c,x,y,z);m.scale.set(rx,ry,rz);return m;}
 layer(name,parent=this.root){const g=new T.Group();g.name='player-layer-'+name;parent.add(g);this.layers[name]=g;return g;}
 build(){this.root=new T.Group();this.group.add(this.root);const body=this.layer('body');this.ball(body,0,.63,0,.25,.3,.18,'#08090c');this.head=this.layer('face');this.head.position.y=1.07;this.ball(this.head,0,0,0,.37,.32,.29,'#050608');this.ball(this.head,-.125,.025,.277,.047,.07,.025,'#ffffff');this.ball(this.head,.125,.025,.277,.047,.07,.025,'#ffffff');this.arms=[];this.legs=[];for(const x of [-1,1]){const a=new T.Group();a.position.set(x*.26,.74,0);body.add(a);this.ball(a,0,-.13,0,.078,.19,.085,'#08090c');this.ball(a,0,-.28,0,.085,.085,.085,'#08090c');this.arms.push(a);const l=new T.Group();l.position.set(x*.115,.4,0);body.add(l);this.ball(l,0,-.13,0,.089,.19,.1,'#08090c');this.ball(l,0,-.3,.035,.1,.08,.16,'#08090c');this.legs.push(l);}this.layer('hat',this.head);this.layer('glasses',this.head);this.layer('poncho');this.layer('accessory');this.dish=this.layer('held-food');this.dish.visible=false;this.ball(this.dish,0,0,0,.13,.04,.13,'#cf9754');this.dish.position.set(0,.72,.33);this.applyWear();}
 clear(g){while(g.children.length){const o=g.children[0];g.remove(o);o.traverse(m=>{m.geometry?.dispose();if(m.material)for(const mat of [].concat(m.material))mat.dispose();});}}
 applyWear(){for(const k of ['hat','poncho','glasses','accessory'])this.clear(this.layers[k]);const w=this.wear,s=w.special,hat=this.layers.hat,c=s?'#f43e90':palette[w.hat],poncho=this.layers.poncho;const cap=this.mesh(hat,new T.ConeGeometry(.4,.37,4),c,0,.34,0);cap.rotation.y=Math.PI/4;cap.scale.z=.83;for(const side of [-1,1]){const ear=this.mesh(hat,new T.ConeGeometry(.12,.29,3),c,side*.27,.44,0);ear.rotation.z=-side*.22;this.mesh(hat,new T.ConeGeometry(.063,.17,3),s?'#ffa1ca':'#d1b994',side*.27,.43,.069);}if(w.hat===1&&!s)this.mesh(hat,new T.TorusGeometry(.31,.025,8,32),'#fff6df',0,.2,0).rotation.x=Math.PI/2;if(w.hat===2&&!s)this.ball(hat,0,.56,0,.08,.08,.08,'#fff6df');if(w.hat===3&&!s)this.mesh(hat,new T.TorusGeometry(.2,.018,8,5),'#f3d37a',0,.3,.25);if(w.hat===4&&!s)this.ball(hat,.25,.33,.13,.07,.07,.05,'#ffffff');
 const p=this.mesh(poncho,new T.CylinderGeometry(.22,.39,.44,8,1,true),s?'#f43e90':palette[w.poncho],0,.69,0);p.scale.z=.7;this.mesh(poncho,new T.TorusGeometry(.225,.028,8,24),'#f7f0de',0,.905,0).rotation.x=Math.PI/2;for(const side of [-1,1])this.ball(poncho,side*.075,.81,.185,.021,.075,.021,'#fff9ed');const trim=this.mesh(poncho,new T.CylinderGeometry(.37,.4,.055,8,1,true),s?'#f2d536':w.poncho===4?'#6e907d':'#faf2da',0,.46,0);trim.scale.z=.7;if(w.poncho===1||s)this.ball(poncho,0,.66,.245,.042,.042,.02,s?'#ffe164':'#476f5a');if(w.poncho===2)this.mesh(poncho,new T.BoxGeometry(.36,.06,.02),'#fffaf1',0,.64,.23);if(w.poncho===3)this.mesh(poncho,new T.TorusGeometry(.046,.014,8,5),'#fff8e8',0,.7,.24);
 const glasses=this.layers.glasses;for(const x of [-.125,.125]){const g=this.mesh(glasses,new T.TorusGeometry(w.glasses===2?.117:.105,w.glasses===1?.023:.017,8,w.glasses===3?8:32),'#ffffff',x,.015,.299);if(w.glasses===4)g.scale.y=.84;}this.mesh(glasses,new T.BoxGeometry(.05,.016,.018),'#ffffff',0,.015,.303);if(w.glasses===1)this.mesh(glasses,new T.BoxGeometry(.4,.012,.012),'#ffffff',0,.13,.29);
 const accessory=this.layers.accessory,n=w.accessory;if(n===1)this.mesh(accessory,new T.TorusGeometry(.075,.024,8,5),'#f0cd5d',.21,.67,.22);if(n===2){this.ball(accessory,-.1,.87,.21,.09,.05,.03,'#df8caa');this.ball(accessory,.1,.87,.21,.09,.05,.03,'#df8caa');}if(n===3)this.ball(accessory,0,.68,-.21,.19,.22,.1,'#936841');if(n===4){for(const x of [-.36,.36])this.ball(accessory,x,1.1,0,.065,.12,.1,'#a9d2c2');}if(n===5)this.mesh(accessory,new T.TorusGeometry(.065,.021,8,4),'#ffffff',-.21,.65,.23);}
 tick(dt){this.time+=dt;let moved=0;if(this.path.length){this.motion='walk';const d=this.path[0].clone().sub(this.pos);d.y=0;const n=d.length(),step=Math.min(n,1.5*dt);if(n<.035)this.path.shift();else{this.pos.addScaledVector(d,step/n);this.heading=Math.atan2(d.x,d.z);moved=step;}if(!this.path.length){this.motion='idle';const fn=this.arrived;this.arrived=null;fn?.();}}if(this.settle){const q=this.settle;q.t+=dt;const u=Math.min(1,q.t/.75);this.pos.copy(q.from).lerp(q.to,u*u*(3-2*u));this.motion=u<1?'settle':q.motion;if(u>=1)this.settle=null;}this.distance+=moved;this.root.rotation.set(0,0,0);this.root.position.set(0,0,0);this.head.rotation.z=0;const cycle=this.distance*12;for(let i=0;i<2;i++){const swing=this.motion==='walk'?Math.sin(cycle+i*Math.PI)*.5:0;this.legs[i].rotation.x=swing;this.arms[i].rotation.set(-swing*.75,0,0);}this.dish.visible=this.motion==='eat';if(this.motion==='sit'||this.motion==='eat'){if(this.motion==='sit'||this.seatEntry){this.legs.forEach(l=>l.rotation.x=-Math.PI/2);this.root.position.y=-.15;}if(this.motion==='eat')this.arms.forEach(a=>a.rotation.x=-.85+Math.sin(this.time*4)*.15);}if(this.motion==='sleep'){this.root.rotation.x=-Math.PI/2;this.root.position.z=.7;}if(this.motion==='cook'){this.arms[1].rotation.x=-.9+Math.sin(this.time*5)*.25;}if(this.motion==='settle'){this.legs.forEach(l=>l.rotation.x=-.4);this.arms.forEach(a=>a.rotation.x=-.45);}if(this.motion==='idle')this.root.position.y=Math.sin(this.time*1.8)*.012;if(this.motion==='stretch'){this.arms[0].rotation.z=-2.6;this.arms[1].rotation.z=2.6;this.head.rotation.z=Math.sin(this.time)*.12;}if(this.motion==='dance'){this.root.position.y=Math.abs(Math.sin(this.time*4))*.08;this.root.rotation.z=Math.sin(this.time*4)*.1;this.arms.forEach((a,i)=>a.rotation.z=(i?1:-1)*(.9+Math.sin(this.time*4)*.3));this.legs.forEach((l,i)=>l.rotation.x=Math.sin(this.time*4+i*Math.PI)*.25);}if(this.motion==='wave')this.arms[0].rotation.z=-2.3+Math.sin(this.time*6)*.15;this.group.position.copy(this.pos);this.group.rotation.y=this.heading;this.group.visible=this.cafe.view===this.room&&(!this.cafe.firstPerson24||!!this.cafe.photo24);}
 serialize(){return{room:this.room,pos:(this.seatEntry||this.pos).clone().setY(0).toArray(),heading:this.heading,wear:{...this.wear}};}
 restore(s){this.room=this.cafe.rooms24?.[s?.room]?s.room:'myhome';this.pos.fromArray(Array.isArray(s?.pos)&&s.pos.length===3&&s.pos.every(Number.isFinite)?s.pos:[192,0,2.8]);this.heading=Number.isFinite(s?.heading)?s.heading:0;for(const k of ['hat','poncho','glasses'])this.wear[k]=Math.max(0,Math.min(4,Math.floor(s?.wear?.[k]||0)));this.wear.accessory=Math.max(0,Math.min(5,Math.floor(s?.wear?.accessory||0)));this.wear.special=!!s?.wear?.special;this.applyWear();this.path=[];this.settle=null;this.seatEntry=null;this.motion='idle';this.pos.y=0;if(!this.cafe.routes20.route(this.room,this.pos,this.cafe.door24(this.room)))this.pos.copy(this.cafe.door24(this.room));}
}
window.ChillPlayer24=Player24;
})();
