const {chromium}=require('C:/Users/CB-Me/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),fs=require('fs'),path=require('path'),assert=require('assert');
(async()=>{let out=path.join(__dirname,'verification-life');fs.mkdirSync(out,{recursive:true});let b=await chromium.launch({channel:'msedge',headless:true,args:['--allow-file-access-from-files']}),page=await b.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('file:///'+path.join(__dirname,'MOB_CHILL_LIFE.html').replaceAll('\\','/'));await page.waitForFunction(()=>window.CHILL?.actors[0].motionsReady);await page.evaluate(()=>{CHILL.reset();CHILL.setPaused(true);CHILL.actors.forEach(a=>{a.cafeWait=1e9;a.timer=1e9;});});
console.log('inventory',await page.evaluate(()=>CHILL.kitchen.inventory));
let economy=await page.evaluate(()=>{let c=CHILL.cafe,a=CHILL.actors[0],p=CHILL.kitchen.inventory;let initial={...p};let r=c.reward('test:meal',a,'meal'),id=c.wallet.pending[0].id,twice=c.reward('test:meal',a,'meal'),collect=c.collectHeart(id),double=c.collectHeart(id),buy=c.buy('egg');CHILL.save();return{r,twice,collect,double,buy,balance:c.wallet.balance,egg:p.egg-initial.egg};});assert.deepEqual(economy,{r:true,twice:false,collect:true,double:false,buy:true,balance:1,egg:1});checks.push('heart reward/collection idempotence and exact ingredient transaction');
await page.reload();await page.waitForFunction(()=>window.CHILL?.actors[0].motionsReady);assert.equal(await page.evaluate(()=>CHILL.cafe.wallet.balance),1);assert.equal(await page.evaluate(()=>CHILL.cafe.wallet.pending.length),0);checks.push('wallet reload no duplicate');
await page.evaluate(()=>{CHILL.setPaused(true);let c=CHILL.cafe;c.setView('cafe');c.ledger.stock={dorayaki:1,omelet:1,soup:1};CHILL.actors.slice(0,3).forEach((a,i)=>{a.room='cafe';a.cafeMode='waiting';a.phase=null;a.state='idle';a.pos.set(13+i*.7,0,3.2);a.cafeTimer=0;a.cafeWait=1e9;});});
let states=new Set(),lines=new Set();for(let i=0;i<2200;i++){let result=await page.evaluate(()=>{CHILL.advance(.1);CHILL.tick(0);return{m:CHILL.actors.slice(0,3).map(a=>a.cafeMode),lines:CHILL.actors.slice(0,3).map(a=>a.bubble.textContent),dirty:CHILL.cafe.dirty,clean:CHILL.cafe.cleaning?.stage};});result.m.forEach(s=>states.add(s));result.lines.forEach(s=>lines.add(s));if(i===450)await page.screenshot({path:path.join(out,'service-390.png')});if(result.clean)states.add('clean:'+result.clean);if(states.has('clean:return')&&i>1600)break;}
assert(states.has('eating'));assert(states.has('satisfied'));assert(states.has('clean:return'));for(let suffix of ['でやんす～！','であります！','ニョロ～！'])for(let prefix of ['いただきます','ごちそうさま'])assert([...lines].some(l=>l.includes(prefix+suffix)),prefix+suffix);checks.push('three foods, three customers, before/after exact dialogue, plate retrieval');
console.log('states', [...states]);
let result=await page.evaluate(()=>({wallet:CHILL.cafe.wallet,dirty:CHILL.cafe.dirty,seats:CHILL.cafe.seats,stock:CHILL.cafe.ledger.stock,eaten:CHILL.cafe.ledger.eaten}));assert.equal(result.eaten,3);assert.equal(result.wallet.pending.filter(d=>d.value===3).reduce((s,d)=>s+d.value,0),9);checks.push('three completed meals award exactly nine hearts');
for(let width of [320,390,430]){await page.setViewportSize({width,height:844});await page.evaluate(()=>{let c=CHILL.cafe;c.setView('cafe');c.staff('welcome');CHILL.tick(0);});let speech=await page.evaluate(()=>{let e=CHILL.actors[3].bubble,r=e.getBoundingClientRect();return{display:getComputedStyle(e).display,opacity:e.style.opacity,rect:[r.left,r.top,r.right,r.bottom],overflow:document.documentElement.scrollWidth>innerWidth};});assert.notEqual(speech.display,'none');assert.equal(speech.opacity,'1');assert(speech.rect[0]>=0&&speech.rect[2]<=width);assert(!speech.overflow);await page.screenshot({path:path.join(out,'dialogue-'+width+'.png')});await page.evaluate(()=>CHILL.cafe.shop());await page.screenshot({path:path.join(out,'shop-'+width+'.png')});await page.locator('#modalClose').click();checks.push('mobile '+width+' speech and shop');}
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({checks,economy,result,states:[...states],lines:[...lines],errors},null,2));console.log('Passed '+checks.length);await b.close();})().catch(e=>{console.error(e);process.exit(1)});
