/* Additional residents use their supplied designs, with an explicit, limited front-facing pose atlas. */
(()=>{'use strict';const T=THREE,V=(x=0,y=0,z=0)=>new T.Vector3(x,y,z),$=s=>document.querySelector(s);
const mealLine=ChillLife.mealLine;ChillLife.mealLine=(a,done)=>a.key==='tetsu'?(done?'ごちそうさまでござる！':'いただくでござる！'):a.key==='nekokoo'?(done?'ごちそうさまだぞ。':'いただくんだぞ。'):mealLine(a,done);
const Base=ChillCafe;window.ChillCafe=class extends Base{
 constructor(c){super(c);this.extraClock=0;for(const [key,name,id,pos]of [['tetsu','モブテツ',4,[-1.1,0,2.1]],['nekokoo','ネコクー',5,[31.25,0,2.8]]]){if(c.actors.some(a=>a.key===key))continue;const a={id,key,name,addedResident:true,pos:V(...pos),room:id===4?'home':'bath',speed:.9,state:'idle',action:'walk',timer:18,path:[],cafePath:[],cafeMode:null,cafeWait:70,done:{},cooldowns:{},speech:0,textures:{},scale:1.65,anchor:[.5,.94],hasAsset:false,npcPose:'idle',npcTime:0,phase:null};a.sprite=new T.Sprite(new T.SpriteMaterial({transparent:true,alphaTest:.04,depthWrite:false}));a.sprite.center.set(.5,.06);a.sprite.scale.set(1.65,1.65,1);a.sprite.visible=false;c.scene.add(a.sprite);a.sleepGroup=new T.Group();a.sleepGroup.visible=false;c.scene.add(a.sleepGroup);a.shadow=new T.Mesh(new T.CircleGeometry(.23,20),new T.MeshBasicMaterial({color:'#526949',transparent:true,opacity:.15,depthWrite:false}));a.shadow.rotation.x=-Math.PI/2;c.scene.add(a.shadow);a.bubble=document.createElement('div');a.bubble.className='bubble';$('#labels').appendChild(a.bubble);a.effect=document.createElement('div');a.effect.className='bubble effect';a.effect.hidden=true;$('#labels').appendChild(a.effect);c.actors.push(a);const b=document.createElement('button');b.dataset.actor=id;b.innerHTML='<span class="badge">'+(id===4?'T':'N')+'</span><span><b>'+name+'</b><small id="state'+id+'">'+(id===4?'のんびり':'温泉の番台')+'</small></span>';$('.residents').appendChild(b);b.onclick=()=>this.menu(a);const proxy=new T.Sprite(a.sprite.material.clone());proxy.center.copy(a.sprite.center);proxy.scale.setScalar(1.25);this.town14.group.add(proxy);this.town14.residentProxies.push({a,sprite:proxy,last:a.pos.clone(),journey:null});}
 this.loadExtraAtlas();this.collections.state.mood[4]=3;const bathEligible=this.bath.eligible.bind(this.bath);this.bath.eligible=a=>!a.addedResident&&bathEligible(a);
 }
 loadExtraAtlas(){new T.TextureLoader().load(CHILL_NPC_ATLAS16,atlas=>{for(const a of this.c.actors.filter(a=>a.addedResident)){for(let i=0;i<16;i++){const t=atlas.clone(),cell=(a.id===4?0:16)+i;const xs=[0,220,445,670,890,1110,1340,1560,1774],ys=[0,258,485,695,887],col=cell%8,row=Math.floor(cell/8);t.repeat.set((xs[col+1]-xs[col])/1774,(ys[row+1]-ys[row])/887);t.offset.set(xs[col]/1774,1-ys[row+1]/887);t.magFilter=t.minFilter=T.NearestFilter;t.generateMipmaps=false;t.colorSpace=T.SRGBColorSpace;t.needsUpdate=true;a.textures[i]=t;}a.hasAsset=true;a.sprite.material.map=a.textures[0];a.sprite.material.needsUpdate=true;const proxy=this.town14.residentProxies.find(p=>p.a===a);proxy.sprite.material.map=a.textures[0];proxy.sprite.material.needsUpdate=true;}if(this.c.actors.every(a=>a.hasAsset))document.querySelector('#dev').hidden=true;atlas.dispose();});}
 serialize(){return{...super.serialize(),npc16:{version:1,residents:Object.fromEntries(this.c.actors.filter(a=>a.addedResident).map(a=>[a.key,{pose:a.npcPose,time:a.npcTime,visits:a.npcVisits||0}]))}};}
 restore(s){super.restore(s);if(!this.c.actors.some(a=>a.addedResident))return;for(const a of this.c.actors.filter(a=>a.addedResident)){const state=s?.npc16?.residents?.[a.key];a.npcPose=['idle','meditate','sleepSeat','sleepWide'].includes(state?.pose)?state.pose:'idle';a.npcTime=Number.isFinite(state?.time)?Math.max(0,Math.min(30,state.time)):0;a.npcVisits=Number.isSafeInteger(state?.visits)?state.visits:0;a.state='idle';a.phase=null;a.path=[];a.timer=18;if(a.key==='nekokoo'){a.room='bath';a.pos.set(31.25,0,2.8);a.cafeMode=null;a.npcOutdoor=false;a.cafePath=[];}else if(a.room==='home')a.pos.set(-1.1,0,2.1);}if(this.collections)this.collections.state.mood[4]=3;}
 say(a,index){if(a.key==='tetsu')return['ここは落ち着くでござるな～。','ひと休みするでござる。','拙者、カフェへ参るでござる！','お主も一緒にどうでござる？','美味でござる！','また来るでござる！'][index%6];return super.say(a,index);}
 menu(a){if(!a.addedResident)return super.menu(a);this.closeActivity();if(a.key==='nekokoo'){this.c.speak(a,'オラがネコクーだぞ。ゆっくりしていくんだぞ。',5,true);this.c.modal(a.name,'<p>オラは温泉の番台にいるんだぞ。ときどき表でひと休みだぞ。</p><button id="npcBathInvite">温泉へ誘う</button>');$('#npcBathInvite').onclick=()=>this.bath.menu();return;}this.c.modal(a.name,'<p>拙者、モブテツでござる。お主もひと息つくでござるな～。</p><div class="shop-actions"><button data-npc-pose="meditate">座って瞑想</button><button data-npc-pose="sleepSeat">座って眠る</button><button data-npc-pose="sleepWide">大の字で眠る</button><button id="npcVisitCafe">カフェへ行く</button></div><p id="npcStatus"></p>');document.querySelectorAll('[data-npc-pose]').forEach(b=>b.onclick=()=>{if(a.room!=='home'||a.cafeMode){$('#npcStatus').textContent='今の用事が終わってからでござる。';return;}a.npcPose=b.dataset.npcPose;a.npcTime=0;a.path=[];a.cafeWait=55;this.c.speak(a,a.npcPose==='meditate'?'心を静めるでござる。':'しばし休むでござるな～。',5,true);this.c.save();$('#modal').close();});$('#npcVisitCafe').onclick=()=>{if(this.visit(a)){$('#modal').close();a.npcPose='idle';}else $('#npcStatus').textContent='道が空いてから参るでござる。';};}
 update(a,dt){if(!a.addedResident)return super.update(a,dt);if(a.state==='staging')return false;if(a.state==='ready')return true;if(a.key==='nekokoo'){a.speech=Math.max(0,a.speech-dt);a.npcTime+=dt;const phase=a.npcTime%100,was=a.npcOutdoor;a.npcOutdoor=phase>=65&&phase<87;const destination=phase>=58&&phase<90?V(28,0,3.3):V(31.25,0,2.8),delta=destination.clone().sub(a.pos);a.npcWalking=delta.length()>.03;if(a.npcWalking){const d=delta.length();a.pos.addScaledVector(delta.normalize(),Math.min(.8*dt,d));}if(a.npcOutdoor&&!was)this.c.speak(a,'オラ、少し表でひと休みだぞ。',5,true);if(!a.npcOutdoor&&was)this.c.speak(a,'オラの温泉で、ぽかぽかだぞ。',5,true);return true;}
 if(a.cafeMode){if(!['seated','eating','satisfied','seating'].includes(a.cafeMode))delete this.requests[a.id];return super.update(a,dt);}a.speech=Math.max(0,a.speech-dt);a.npcTime+=dt;a.cafeWait-=dt;if(a.cafeWait<=0&&this.visit(a)){a.npcPose='idle';a.npcVisits++;return true;}if(a.path.length){const target=a.path[0],d=a.pos.distanceTo(target);if(d<.04){a.pos.copy(target);a.path.shift();}else if(this.c.room.segmentClear(a.pos,target))a.pos.lerp(target,Math.min(1,dt*a.speed/d));else a.path=[];return true;}if(a.npcTime>24){a.npcTime=0;const poses=['meditate','sleepSeat','idle','sleepSeat','meditate','sleepWide'];a.npcPose=poses[(a.done.rest||0)%poses.length];a.done.rest=(a.done.rest||0)+1;if(a.npcPose==='idle'){const points=[V(-1.1,0,2.1),V(0,0,2.6),V(1.1,0,2.3)];a.path=this.c.route(a.pos,points[a.done.rest%3])||[];}else this.c.speak(a,a.npcPose==='meditate'?'心を静めるでござるな～。':'少し休むでござる。',5,true);}return true;
 }
 renderExtraActor(a){if(!a.hasAsset){a.sprite.visible=false;return;}const moving=a.path.length||a.cafePath?.length||a.npcWalking,t=this.clock14,frame=Math.floor(t*5)%2;let pose=moving?2+frame:a.speech>0?5:frame;if(a.key==='tetsu'&&!moving){if(a.cafeMode==='eating')pose=14; /* Shared meal meshes own the food. */else if(['seated','satisfied'].includes(a.cafeMode))pose=14;else if(a.npcPose==='meditate')pose=6+frame;else if(a.npcPose==='sleepSeat')pose=8+frame;else if(a.npcPose==='sleepWide')pose=10+frame;}a.sprite.material.map=a.textures[pose];a.sprite.position.copy(a.pos);a.sprite.scale.set(1.65,1.65,1);a.sprite.center.set(.5,.06);a.sprite.visible=this.view===a.room&&!a.npcOutdoor;a.shadow.position.set(a.pos.x,.067,a.pos.z);a.shadow.visible=a.sprite.visible&&a.pos.y<.15;a.sleepGroup.visible=false;const p=a.pos.clone().add(V(0,1.65,0)).project(this.c.camera);a.bubble.style.left=(p.x*.5+.5)*innerWidth+'px';a.bubble.style.top=(-p.y*.5+.5)*innerHeight+'px';a.bubble.style.opacity=a.sprite.visible&&a.speech>0?1:0;$('#state'+a.id).textContent=a.key==='nekokoo'?(a.npcOutdoor?'表へひと歩き':'温泉の番台'):a.cafeMode?'カフェでひと休み':a.npcPose==='meditate'?'瞑想中':a.npcPose.startsWith('sleep')?'おやすみ':'のんびり';}
 afterRender(){super.afterRender();const a=this.c.actors.find(a=>a.key==='nekokoo');if(a){const p=this.town14.residentProxies.find(p=>p.a===a);p.sprite.visible=this.view==='town'&&a.npcOutdoor&&a.hasAsset;if(p.sprite.visible){const f=this.town14.facilities.find(f=>f.id==='bath'),u=(a.npcTime%100-65)/22,travel=Math.min(1,Math.min(u,1-u)*5);p.sprite.position.copy(f.door).lerp(f.approach,Math.max(0,travel));p.sprite.material.map=a.textures[travel<1?2+Math.floor(this.clock14*5)%2:0];}a.sprite.visible=this.view==='bath'&&!a.npcOutdoor&&a.hasAsset;a.shadow.visible=a.sprite.visible;}}
};
})();
