/* Smooth resident atlases keep the existing action clocks and physical interaction systems. */
(()=>{'use strict';const T=THREE,V=(x=0,y=0,z=0)=>new T.Vector3(x,y,z),$=s=>document.querySelector(s),groups={front:[0,1],left:[2,3],right:[4,5],back:[6,7],meal:[8,9,10,11,12],wait:[13,14,15],bath:[16,17,18,19],joy:[20,21,22,23],idle:[24,25],greet:[26,27],sleep:[28,29],quiet:[30,31]};
const moneyLines={breakfast:['おはよう！ 朝ごはんにしましょう♪','今日はふわふわの卵の気分ね。'],lunch:['お腹空いたなー・・。一緒に行く？','あっちにいきましょう♪ お昼の時間よ！'],snack:['今日は甘いものの気分ね。','一口ちょうだい？ ふふ、冗談よ。'],dinner:['今日は何があるのかしら？','たくさん歩いたし、ちゃんと食べましょ！'],hungry:['お腹空いたなー・・。','いい匂い！ もうすぐかしら？'],wait:['分かった！ ここで待ってる。','そう？ じゃあ、先にどうぞ。'],bathBefore:['杖をここに置いて……温まってくるわ！','今日はゆっくりお風呂の気分ね。'],bathAfter:['ふー、気持ちよかった！','杖も忘れてないわ。帰りましょう♪'],bed:['おやすみー！ また明日ねー！','今日はもう休むわ。あんたも早く寝なさいよ。'],wake:['おはよう！ 今日も一緒に行く？','よく寝たー！ さ、出かけましょう♪'],fallback:['いいわよ！ 少し休みましょ。','分かった！ また後でね。']};
CHILL_ROUTINE_DATA.dialogue.money=moneyLines;ChillVoice21.greetings.money=['いいわよ！ 一緒に行く？','あっちにいきましょう♪','お腹空いたなー・・。','分かった！ ここで待ってる。','おいしい！ 今日はこれの気分ね。','また明日ねー！'];
const voice=ChillVoice21.line;ChillVoice21.line=(a,line)=>{if(a?.key!=='money')return voice(a,line);return String(line||'いいわよ！').replace(/オラ|拙者|僕/g,'あたし').replace(/であります！?|でござる(?:な～)?[！。]?|でやんす[～！。]?|だニョロ[～！。]?|なんだぞ[！。]?|だぞ[！。]?/g,'ね！');};
const mealLine=ChillLife.mealLine;ChillLife.mealLine=(a,done)=>a.key==='money'?(done?'ごちそうさま！ また食べに来ましょ♪':'いただきまーす！'):mealLine(a,done);
CHILL_SHOP_LINES22.money={browse:['この子、かわいいじゃない♪','今日は何を選ぼうかなー。','ギターの子も気になるわ！','細かいところまでよくできてるわね。'],take:['決めた！ この子にするわ♪','落とさないように、そーっとね。','いいわよ！ レジへ行きましょう。'],wait:['お会計お願いしまーす！','急がなくていいわよ。ここで待ってる。','分かった！ 順番ね。'],buy:['ありがと！ 大事にするわ♪','いい買い物しちゃった！','ふふ、みんなにも見せなくちゃ。'],empty:['そっかー。また見に来るわ。','並んだら教えてね♪']};
const pairs=[
 ['tetsu','money','杖を預かるでござるか？','ありがと！ でも、自分で置けるわ。','承知でござる。隣を空けておくでござる。','ふふ、気が利くじゃない。'],
 ['money','tetsu','今日も素振り？ 頑張るわね。','毎日の積み重ねでござる。お主も一緒にどうでござる？','いいわよ！ まずは見てるわ。','では、周りを確かめてからでござる。'],
 ['denden','pink','今日の選曲、どうでやんす？','僕、思わず足が動くであります！','ほぅ～、一曲踊るでやんす♪','一緒に踊るであります！'],
 ['pink','nyoro','その傘、おしゃれでありますね！','お気に入りだニョロ～。','僕も大切なものは長く使うであります！','それがいいニョロ♪'],
 ['money','denden','今日はどらやきの気分ね。','オイラもちょうど食べたかったでやんす。','じゃ、一緒に行く？','もちろんでやんす～♪'],
 ['tetsu','pink','お主、少し肩の力を抜くでござる。','僕、張り切りすぎたでありますか？','よく頑張った証でござるな～。','では、ひと息つくであります！'],
 ['nyoro','money','帽子の星が揺れてるニョロ！','そう？ これ、お気に入りなの♪','きらきらでかわいいニョロ～。','ふふ、あんたも見る目あるじゃない。'],
 ['nekokoo','tetsu','今日もいい湯にしてあるぞ。','鍛錬のあとの湯は格別でござる。','刀は入口に置いてくれよな。','もちろんでござる。大切に立てかけるでござる。'],
 ['irukaeru','money','あら～、今日は何の気分ですか？','甘いもの！ でも先にごはんかしら。','ゆっくり選んでくださいね。','分かった！ おすすめも聞かせて♪'],
 ['mita','pink','新しいフィギュア、並べてみました♪','僕、台座まで見てしまうであります！','細かいところも楽しんでくださいね。','ゆっくり選ぶであります！'],
 ['mita','tetsu','お元気ですか？','拙者、今日も健やかでござる。','それは何よりです♪','お主も無理をせず、休むでござるよ。'],
 ['irukaeru','nekokoo','温泉のおかげで、足が軽いです。','それならオラもうれしいぞ。','今度はカフェで休んでくださいね。','仕事が落ち着いたら行くぞ。'],
 ['denden','nyoro','あの雲、どらやきみたいでやんす。','お腹が鳴ったニョロ……。','オイラもでやんす。','カフェまで一緒に行くニョロ♪'],
 ['money','pink','ちょっと！ あんた元気すぎて声が大きいわ。','申し訳ないであります！','ふふ、怒ってないわよ。小声で話しましょ。','了解であります……！'],
 ['nekokoo','money','その杖、立派だな。','大事な相棒よ。置き忘れないようにしなくちゃ。','帰りにオラも声をかけるぞ。','ありがと！ 頼りにしてるわ。'],
 ['irukaeru','tetsu','お皿を運んでくださって、ありがとうございます。','お主の手助けになれば幸いでござる。','ふふっ、次はお茶にしましょう。','ありがたく頂くでござる。'],
 ['mita','money','たくさん見て行ってください♪','このギターの子、楽しそうね！','音楽がお好きなんですね。','今日はライブの気分だわ♪'],
 ['pink','denden','MOB PLAYの記録、もう少しで抜けそうであります！','オイラも応援するでやんす。','次は一緒に遊ぶであります！','楽しみでやんす～。']
];
function mappedPose(name,p){name=String(name||'idle');const n=+(name.match(/(\d+)$/)?.[1]||0);if(/^turnDance/.test(name)&&p.turnjoy)return p.turnjoy[n%16];if(/^taso/.test(name)&&p.taso)return p.taso[n%16];if(/^music|^dance/.test(name)&&p.dance)return p.dance[n%16];if(/joy|cheer_cheeks/.test(name)&&p.cheeks)return p.cheeks[6+n%6];if(p.domestic){if(/book|read/.test(name))return p.domestic[/reach/.test(name)?0:/return/.test(name)?3:/hold/.test(name)?1:2];if(/clean/.test(name))return p.domestic[4+n%4];if(/garden|plant/.test(name))return p.domestic[8+n%4];if(/dj/.test(name))return p.domestic[12+n%4];}if(/walk|run/.test(name)){const row=/back/.test(name)?3:/left|side/.test(name)?1:/right/.test(name)?2:0;return p.walk[row*4+n%4];}if(/meal|dorayaki|eat/.test(name))return p.life[8+Math.min(3,n%5)];if(/sleep|nap/.test(name))return p.life[/lie|wide/.test(name)?14:13];if(/book|read|hold/.test(name))return p.life[6+n%2];if(/sit|seated|wait/.test(name))return p.life[5+n%2];if(/bath/.test(name))return p.life[5];if(/bag|reach|return|mount/.test(name))return p.action[n%8];if(/dance|dj|music|clean|garden|plant/.test(name))return p.action[8+n%4];if(/joy|cheer|hop/.test(name))return p.action[12];if(/stretch/.test(name))return p.action[12];if(/wave|greet|chat|talk/.test(name))return p.life[2+n%2];if(/yawn/.test(name))return p.life[12];return p.life[n%2];}
const Base=ChillCafe;window.ChillCafe=class extends Base{
 constructor(c){super(c);this.installMoney23();this.tavern23=new ChillTavern23(this);this.figureShelves23();this.installProducts21();this.installResidentUI23();this.socialNext23=25;this.socialCount23=0;this.props23=new Map();const idle=this.routine.idle.bind(this.routine);this.routine.idle=a=>!a.social23&&!a.propSequence23&&idle(a);for(const a of c.actors){if(CHILL_RESIDENTS23[a.key])this.loadResident23(a);if(['tetsu','money'].includes(a.key))this.props23.set(a.key,this.makeProp23(a.key));}const approach=this.bath.approach.bind(this.bath);this.bath.approach=a=>{if(this.props23.has(a.key)&&!a.propPark23){if(!a.propSequence23)this.deposit23(a,'bath',()=>approach(a));return;}return approach(a);};this.installTown23();}
 installMoney23(){const c=this.c,a={id:7,key:'money',name:'モブマニー',addedResident:true,pos:V(1.2,0,2.5),room:'home',speed:1.15,state:'idle',action:'walk',timer:18,path:[],cafePath:[],cafeMode:null,cafeWait:75,done:{},cooldowns:{},speech:0,textures:{},scale:1.65,anchor:[.5,.94],hasAsset:false,npcPose:'idle',npcTime:0,phase:null,phases:[],phaseIndex:0};a.sprite=new T.Sprite(new T.SpriteMaterial({transparent:true,alphaTest:.04,depthWrite:false}));a.sprite.center.set(.5,.06);a.sprite.scale.setScalar(1.65);c.scene.add(a.sprite);a.sleepGroup=new T.Group();c.scene.add(a.sleepGroup);a.shadow=new T.Mesh(new T.CircleGeometry(.24,20),new T.MeshBasicMaterial({color:'#526949',transparent:true,opacity:.15,depthWrite:false}));a.shadow.rotation.x=-Math.PI/2;c.scene.add(a.shadow);for(const key of ['bubble','effect']){a[key]=document.createElement('div');a[key].className='bubble'+(key==='effect'?' effect':'');$('#labels').appendChild(a[key]);}ChillContactDepth.install(a);c.actors.push(a);this.bagIdle[7]=72;this.arcadeNext[7]=this.arcadeClock+110;const b=document.createElement('button');b.dataset.actor=7;b.innerHTML='<span class="badge">★</span><span><b>モブマニー</b><small id="state7">のんびり</small></span>';$('.residents').appendChild(b);b.onclick=()=>this.menu(a);const proxy=new T.Sprite(a.sprite.material.clone());proxy.center.copy(a.sprite.center);proxy.scale.setScalar(1.25);this.town14.group.add(proxy);this.town14.residentProxies.push({a,sprite:proxy,last:a.pos.clone(),journey:null});}
 async loadResident23(a){try{const packets=CHILL_RESIDENTS23[a.key],p={};await Promise.all(Object.entries(packets).map(async([kind,spec])=>{const im=new Image();im.src=spec.url;await im.decode();const scale=Math.min(216/Math.max(...spec.rects.map(r=>r[2])),218/Math.max(...spec.rects.map(r=>r[3])));p[kind]=spec.rects.map((r,i)=>{const cv=document.createElement('canvas');cv.width=cv.height=512;const ctx=cv.getContext('2d');ctx.scale(2,2);ctx.imageSmoothingQuality='high';const lie=kind==='life'&&i>=14,s=lie?Math.min(235/r[2],155/r[3]):scale,w=r[2]*s,h=r[3]*s;ctx.drawImage(im,...r,128-w/2,lie?128-h/2:240-h,w,h);const tx=new T.CanvasTexture(cv);tx.magFilter=tx.minFilter=T.LinearFilter;tx.generateMipmaps=false;tx.colorSpace=T.SRGBColorSpace;tx.userData.v23=true;return tx;});}));if(a.key==='denden'){for(const base of [0,12])for(let i=0;i<2;i++){const tx=p.walk[base+i].clone();tx.repeat.x=-1;tx.offset.x=1;tx.needsUpdate=true;tx.userData.v23=true;p.walk[base+2+i]=tx;}}a.smooth23=p;this.remap23(a);a.hasAsset=a.lifeReady20=a.bagReady=a.mealReady=a.bathReady=a.motion18Ready=true;a.sprite.material.map=p.life[0];a.sprite.material.needsUpdate=true;this.remapUntil23=performance.now()+15000;}catch(e){a.smoothError23=String(e);console.error('Resident atlas',a.key,e);}}
 remap23(a){const p=a.smooth23;if(!p)return;for(const key of Object.keys(a.textures))a.textures[key]=mappedPose(key,p);Object.assign(a.textures,{idle:p.life[0],sit:p.life[5],sleep:p.life[14],read:p.life[7],bag_0:p.action[2],bag_1:p.action[5],bag_2:p.life[7]});for(let n=0;n<5;n++)a.textures['meal_'+n]=p.life[8+Math.min(3,n)];a.motion18={groups,frames:[p.walk[0],p.walk[2],p.walk[4],p.walk[6],p.walk[8],p.walk[10],p.walk[12],p.walk[14],p.life[8],p.life[9],p.life[10],p.life[11],p.life[11],p.life[5],p.life[6],p.life[5],p.life[5],p.life[11],p.life[5],p.life[11],p.action[12],p.action[14],p.action[12],p.action[14],p.life[0],p.life[1],p.life[2],p.life[3],p.life[13],p.life[13],p.life[5],p.life[1]]};a.life20={...(a.life20||{}),sleepLie:[p.life[14],p.life[15]],sleepSeat:[p.life[13],p.life[13]],bag:[p.action[2],p.action[5],p.life[7]],walk:[p.walk[0],p.walk[2],p.walk[12],p.walk[14],p.walk[4],p.walk[6],p.walk[8],p.walk[10]]};a.bagSpec={frames:[{heldItemAnchorPx:[128,192]},{heldItemAnchorPx:[117,167]},{heldItemAnchorPx:[128,165]}].map(f=>({...f,bagAnchorPx:[128,200],activeHandAnchorPx:f.heldItemAnchorPx,supportHandAnchorPx:[148,180]}))};a.mealFrameMeta=[192,180,168,168,188].map(y=>({handAnchorPx:[128,y],heldFoodAnchorPx:[128,y],mouthAnchorPx:[128,154]}));a.motion18Ready=a.lifeReady20=a.bagReady=a.mealReady=a.bathReady=true;}
 walkingTexture20(a,h,d=0){if(!a.smooth23)return super.walkingTexture20(a,h,d);const right=V().setFromMatrixColumn(this.c.camera.matrixWorld,0),front=V().setFromMatrixColumn(this.c.camera.matrixWorld,2),x=h.dot(right),z=h.dot(front),dir=Math.abs(x)>Math.abs(z)?x<0?'left':'right':z<0?'back':'front';a.walkDirection=dir;const row=(a.key==='tetsu'?{front:0,left:2,right:1,back:3}:{front:0,left:1,right:2,back:3})[dir];return a.smooth23.walk[row*4+Math.floor(d/.11)%4];}
 products21(){return[...super.products21(),...(window.CHILL_SHOP_FIGURES23||[])];}
 price21(item){return item.shopOnly?item.price:super.price21(item);}
 itemName(key){return CHILL_SHOP_FIGURES23.find(p=>p.id===key)?.name||super.itemName(key);}
 figureShelves23(){const g=this.spaces21.groups.shop;for(let row=0;row<2;row++){const z=.05+row*2.45;this.spaces21.box(g,-2.8,.46,z,3.5,.92,.72,'#eee2c6');this.spaces21.box(g,-2.8,.96,z,3.65,.09,.86,'#d3a750');for(let col=0;col<4;col++){const i=row*4+col,x=-4.12+col*.88,model=new T.Group();model.position.set(x,1.01,z);g.add(model);this.spaces21.targets.push({room:'shop',point:V(128+x,1.45,z),approach:V(128+x,0,z+.93),label:'',action:'product'+(i+6),model});}}const rects=this.routes20.rects.bind(this.routes20);this.routes20.rects=room=>room==='shop'?[...rects(room),...Array.from({length:2},(_,i)=>({id:'figures'+i,minX:123.3,maxX:127.12,minZ:-.46+i*2.45,maxZ:.56+i*2.45}))]:rects(room);}
 installResidentUI23(){const b=document.createElement('button');b.dataset.room='tavern';b.textContent='酒場';b.onclick=()=>this.setView('tavern');$('#roomSwitch').appendChild(b);}
 setView(v){if(v==='tavern'){if($('#modal').open||this.c.editing()||this.c.room.mobileEditor)return false;this.closeActivity();this.view=v;$('#farmToolbar').hidden=$('#arcadeToolbar').hidden=true;document.querySelectorAll('[data-room]').forEach(b=>b.classList.toggle('active',b.dataset.room===v));this.c.layout();return true;}return super.setView(v);}
 menu(a){if(a.key!=='money')return super.menu(a);this.c.speak(a,this.say(a,(this.moneyGreeting23=(this.moneyGreeting23||0)+1)),5,true);this.c.modal(a.name,'<p>一緒に行く？ 今日は何して遊ぼうかな♪</p><div class="shop-actions"><button data-money="bag">バッグを見る</button><button data-money="cafe">カフェへ誘う</button><button data-money="bath">温泉へ誘う</button><button data-money="rest">寝床で休む</button></div><p data-money-status></p>');document.querySelectorAll('[data-money]').forEach(b=>b.onclick=()=>{const task=b.dataset.money;if(task==='bag')return this.bagMenu(a.id);$('#modal').close();const ok=task==='cafe'?this.visit(a):task==='bath'?this.bath.visit(a):this.sleep20.request(a);if(!ok)this.c.speak(a,'分かった！ 今の用事が終わったらね。',5,true);});}
 makeProp23(key){const g=new T.Group();g.name=key==='tetsu'?'Tetsu-sword':'Manny-paw-staff';this.c.scene.add(g);const box=(x,y,z,w,h,d,c)=>this.spaces21.box(g,x,y,z,w,h,d,c);if(key==='tetsu'){box(0,.44,0,.075,.88,.055,'#27242c');box(0,.91,0,.21,.045,.13,'#c6b27b');box(0,1.075,0,.066,.28,.06,'#eee2c5');for(let i=0;i<5;i++){const m=box(0,.972+i*.044,.035,.057,.028,.013,'#41383e');m.rotation.z=.7;}box(0,.48,.035,.019,.62,.012,'#ada8a5');}else{box(0,.57,0,.055,1.14,.05,'#8b592c');for(const y of [.15,.98])box(0,y,0,.083,.045,.075,'#daa740');const paw=new T.Mesh(new T.SphereGeometry(.16,16,12),new T.MeshStandardMaterial({color:'#fff0ce'}));paw.scale.set(1,1.12,.35);paw.position.y=1.22;g.add(paw);for(const [x,y]of [[-.14,1.37],[-.05,1.44],[.07,1.44],[.16,1.35],[0,1.2]]){const pad=new T.Mesh(new T.SphereGeometry(y<1.3?.085:.063,12,10),new T.MeshStandardMaterial({color:'#ed9baa'}));pad.scale.z=.45;pad.position.set(x,y,.06);g.add(pad);}for(const x of [-.09,.09]){const bow=box(x,1.03,0,.16,.1,.05,'#efa3ba');bow.rotation.z=x<0?.3:-.3;}}g.visible=false;return g;}
 deposit23(a,reason,done){if(a.propSequence23||a.propPark23)return;const point=a.pos.clone(),right=V(.42,0,.08);point.y=0;a.propSequence23={kind:'put',time:0,reason,point:point.clone().add(right),entry:point,room:a.room,done};}
 wantsPark23(a){return a.rest20&&['settle','sleep'].includes(a.rest20.phase)||['seating','seated','eating','satisfied'].includes(a.cafeMode)||a.activity21?.phase==='use'||a.phase&&/sit|read|sleep|nap/.test(a.phase.pose||'')||a.npcPose==='meditate';}
 tickProp23(a,dt){const s=a.propSequence23;if(!s)return false;a.speech=Math.max(0,a.speech-dt);if(s.path?.length){this.follow20(a,s.path,dt);return true;}s.time+=dt;if(s.time>=1.15){if(s.kind==='put')a.propPark23={point:s.point,entry:s.entry,room:s.room,reason:s.reason};else delete a.propPark23;delete a.propSequence23;s.done?.();}return true;}
 update(a,dt){if(a.id===0&&this.props23){this.socialNext23-=dt;if(this.social23)this.tickSocial23(dt);else if(this.socialNext23<=0){this.socialNext23=22;this.startSocial23();}}if(!this.props23)return super.update(a,dt);if(a.social23){if(a.id===0){this.tick21(dt);this.routine.plan();this.arcadeTick(dt);}a.speech=Math.max(0,a.speech-dt);return true;}if(this.props23.has(a.key)){if(this.tickProp23(a,dt))return true;const park=a.propPark23,want=this.wantsPark23(a);if(!park&&want){this.deposit23(a,'seat');return true;}if(park&&!want&&(park.reason!=='bath'||!a.bathMode||a.bathMode==='return')){const path=this.routes20.route(a.room,a.pos,park.entry);if(path){a.propSequence23={kind:'pick',time:0,point:park.point,entry:park.entry,room:park.room,path};return true;}}}return super.update(a,dt);}
 socialFree23(a){return !a.social23&&!a.propSequence23&&!a.propPark23&&!a.path?.length&&!a.cafePath?.length&&!a.phase&&!a.rest20&&!a.transit20&&!a.activity21&&!a.shopVisit22&&!a.bathMode&&!a.arcadeMode&&!a.bagAnimation&&!a.townAction19&&(!a.cafeMode||a.cafeMode==='waiting')&&(a.key!=='mita'||!a.mitaState21?.path?.length&&!this.cashier22)&&(a.id!==3||!this.service&&!this.cleaning&&!this.staffMeal);}
 startSocial23(){if($('#modal').open||this.routine.hour<6||this.routine.hour>=22)return false;for(let i=0;i<pairs.length;i++){const ix=(this.socialCount23+i)%pairs.length,p=pairs[ix],a=this.c.actors.find(a=>a.key===p[0]),b=this.c.actors.find(a=>a.key===p[1]);if(!a||!b||a.room!==b.room||a.pos.distanceTo(b.pos)>2.8||!this.socialFree23(a)||!this.socialFree23(b))continue;this.socialCount23=ix+1;a.social23=b.social23=true;this.social23={a,b,lines:p.slice(2),index:0,time:0};this.c.speak(a,p[2],3.5,true);return true;}return false;}
 tickSocial23(dt){const s=this.social23;s.time+=dt;if(s.time<3.8)return;s.time=0;s.index++;if(s.index>=s.lines.length){delete s.a.social23;delete s.b.social23;this.social23=null;this.socialNext23=30;return;}this.c.speak(s.index%2?s.b:s.a,s.lines[s.index],3.5,true);}
 installTown23(){const sys=this.townActions19,program=sys.program.bind(sys);sys.program=a=>{if(a.key!=='tetsu')return program(a);const f=this.town14.facilities.find(f=>f.id==='home'),start=f.door.clone(),patch=f.approach.clone().add(V(0,0,1.5)),path=[start,f.approach.clone(),patch];return{door:start,segments:[{kind:'walk',path,duration:4},...Array.from({length:12},(_,i)=>({kind:'hold',duration:.65,frame:8+i%4})),{kind:'walk',path:path.slice().reverse(),duration:4}],practice23:true};};const render=sys.render.bind(sys);sys.render=()=>{render();const s=sys.active;if(!s||!sys.sprite.visible||!s.a.smooth23)return;const p=s.a.smooth23;sys.sprite.material.map=s.walking?this.walkingTexture20(s.a,s.heading||V(0,0,1),s.walkDistance):s.plan.practice23?p.action[8+(s.frame-8)%4]:p.town?p.town[({pink:[1,3,4,5,6,8,10,12],nyoro:[2,3,4,5,6,8,10,12]}[s.a.key]||[0,1,2,3,4,5,6,7])[s.frame%8]]:p.action[8+s.frame%4];sys.sprite.center.set(.5,16/256);sys.sprite.scale.setScalar(1.35);if(s.a.key==='tetsu'){s.a.townAction19='素振り';const prop=this.props23.get('tetsu');prop.visible=true;prop.position.copy(this.town14.group.localToWorld(sys.sprite.position.clone())).add(V(.22,.23,.05));prop.rotation.set(0,0,s.walking?-.45:Math.sin(s.time/.65*Math.PI)*-1.6);}};}
 drawSmooth23(a){const p=a.smooth23;if(!p){if(CHILL_RESIDENTS23[a.key])a.sprite.visible=false;return;}for(const key in a.textures)if(!a.textures[key]?.userData?.v23){this.remap23(a);break;}const moving=!!(a.path?.length||a.cafePath?.length||a.transit20||a.rest20?.phase==='approach'||a.activity21?.path?.length||a.shopVisit22?.path?.length||a.propSequence23?.path?.length||a.phase?.point);let tex;const seq=a.propSequence23,meal=ChillMeal.state(a);if(seq&&!seq.path?.length)tex=p.action[(seq.kind==='pick'?4:0)+Math.min(3,Math.floor(seq.time/1.15*4))];else if(moving)tex=this.walkingTexture20(a,a.heading20||a.heading||a.motionHeading18||V(0,0,1),a.walkDistance20||a.walkDistance18||0);else if(meal)tex=p.life[8+Math.min(3,meal.index)];else if(a.bagAnimation)tex=mappedPose(ChillBagMotion.pose(a),p);else if(a.bathMode==='soak'||a.bathMode==='exitWait')tex=p.life[5];else if(a.activity21?.phase==='use'||a.cafeMode==='seated'||a.cafeMode==='satisfied'||a.arcadeMode==='racing')tex=p.life[5];else if(a.key==='denden'&&p.cheeks&&(a.phase?.pose==='joy'||a.arcadeJoyTime>0&&!a.arcadeSad14))tex=p.cheeks[a.phase?.pose==='joy'?(a.phase.name==='両手をほっぺに'?Math.min(5,Math.floor(a.phaseTime*5)):a.phase.name==='ほぅ～！'?6+Math.min(5,Math.floor(a.phaseTime*5)):12+Math.min(3,Math.floor(a.phaseTime*2))):6+Math.floor(this.clock14*5)%6];else if(a.key==='denden'&&p.turnjoy&&a.phase?.pose==='turnDance')tex=p.turnjoy[Math.floor(a.phaseTime*5)%16];else if(a.key==='denden'&&p.dance&&['music','dance'].includes(a.phase?.pose))tex=p.dance[Math.floor(a.phaseTime*5)%16];else if(a.social23||a.speech>0&&!a.phase)tex=p.life[2+Math.floor(this.clock14*2)%2];else if(a.id===3&&(this.service||this.cleaning))tex=p.action[8+Math.floor(this.clock14*3)%4];else {const pose=a.drawPose||a.phase?.pose||'idle';tex=p.domestic&&/clean|garden|plant|dj/.test(pose)?p.domestic[(/clean/.test(pose)?4:/garden|plant/.test(pose)?8:12)+Math.floor(this.clock14*3)%4]:mappedPose(pose,p);}a.sprite.material.map=tex;a.sprite.scale.set(1.9,1.9,1);a.scale=1.9;if(a.addedResident)a.sprite.center.set(.5,16/256);const proxy=this.town14.residentProxies.find(p=>p.a===a);if(proxy?.sprite.visible)proxy.sprite.material.map=this.walkingTexture20(a,proxy.motionHeading18||a.heading20||V(0,0,1),proxy.walkDistance18||this.clock14*.4);}
 renderProp23(a,g){const park=a.propPark23,s=a.propSequence23;if(a.townOutside19){g.visible=this.view==='town'&&this.townActions19.active?.a===a;return;}g.visible=false;g.rotation.set(0,0,0);if(park||s){const point=park?.point||s.point,room=park?.room||s.room;g.visible=this.view===room;g.position.copy(point);g.rotation.z=park?.reason==='bath'||s?.reason==='bath'?.18:1.4;if(s){const u=Math.min(1,s.time/1.15);g.position.y=s.kind==='put'?(1-u)*.45:u*.45;}}else if(a.sprite.visible){g.visible=true;const offset=V(a.key==='tetsu'?-.37:.36,.17,.04).applyQuaternion(this.c.camera.quaternion);g.position.copy(a.sprite.position).add(offset);g.rotation.z=a.key==='tetsu'?-.48:.08;}}
 afterRender(){super.afterRender();if(!this.tavern23)return;this.tavern23.update(this.clock14);if(this.remapUntil23>performance.now()&&performance.now()>(this.remapNext23||0)){this.remapNext23=performance.now()+1000;for(const a of this.c.actors)if(a.smooth23)this.remap23(a);}for(const a of this.c.actors){this.drawSmooth23(a);const prop=this.props23?.get(a.key);if(prop)this.renderProp23(a,prop);}if(this.view==='tavern'){this.group.visible=false;for(const a of this.c.actors){a.sprite.visible=a.shadow.visible=false;a.bubble.style.opacity=0;}}this.placeBubbles22?.();}
 restore(s){super.restore(s);if(!this.props23)return;this.social23=null;for(const a of this.c.actors){delete a.propSequence23;delete a.propPark23;delete a.social23;}this.socialNext23=30;}
};
})();




