/* Physical first-hit picking: transparent sprite padding never captures a dish tap. */
window.ChillPicking={
 pixels:new WeakMap(),
 belongs(object,root){for(let o=object;o;o=o.parent)if(o===root)return true;return false;},
 first(ray,scene){scene.updateMatrixWorld(true);return ray.intersectObject(scene,true).map(h=>{let w=h.object.userData.contactDepth?.value;if(w&&h.uv&&ray.camera){let o=h.object,r=o.material.rotation||0,y=Math.sin(r)*(h.uv.x-o.center.x)*o.scale.x+Math.cos(r)*(h.uv.y-o.center.y)*o.scale.y,m=ray.camera.matrixWorldInverse.elements;h.distance-=w*y*m[6]/Math.max(.25,m[5]);}return h;}).sort((a,b)=>a.distance-b.distance).find(h=>{for(let o=h.object;o;o=o.parent)if(!o.visible)return false;let m=h.object.material;if(!m||m.transparent&&m.opacity<.3)return false;let im=m.map?.image;if(!im||!h.uv)return true;try{let data=this.pixels.get(im);if(!data){let c=document.createElement('canvas');c.width=im.width;c.height=im.height;let x=c.getContext('2d');x.drawImage(im,0,0);data=x.getImageData(0,0,c.width,c.height).data;this.pixels.set(im,data);}let x=Math.max(0,Math.min(im.width-1,Math.floor(h.uv.x*im.width))),y=Math.max(0,Math.min(im.height-1,Math.floor((m.map.flipY?1-h.uv.y:h.uv.y)*im.height)));return data[(y*im.width+x)*4+3]>=Math.max(32,(m.alphaTest||0)*255);}catch{return true;}});}
};
(()=>{const $=s=>document.querySelector(s),old=ChillLiving.positionLabels;
// The wrapper runs after mobile.js defines its label positioning.
window.addEventListener('load',()=>{const position=ChillLiving.positionLabels;ChillLiving.positionLabels=function(k,camera,w,h){position(k,camera,w,h);let plate=k.plateTap;if(!plate){plate=k.plateTap=document.createElement('button');plate.id='plateTap';plate.className='cooking-bubble plate-tap';plate.textContent='料理を置く';plate.setAttribute('aria-label','お皿に料理を置く');plate.onclick=e=>{e.stopPropagation();k.serveMenu();};$('#labels').appendChild(plate);}plate.hidden=!k.room.furniture.table.group.visible||k.hooks.canCook?.()===false||$('#modal').open;plate.textContent=k.hooks.food?.()?'お皿を確認':'料理を置く';const targets=[];for(let [station,el]of Object.entries(k.readyLabels||{})){if(el.hidden)continue;let f=k.room.furniture[station==='oven'?'oven':'stove'],p=station==='oven'?f.group.localToWorld(new THREE.Vector3(0,1.2,.2)):f.vessels[station].group.localToWorld(new THREE.Vector3(0,.17,0));targets.push({el,p,station});}if(!plate.hidden)targets.push({el:plate,p:k.room.socket('table','food'),station:'plate'});let used=[],bottom=$('footer').getBoundingClientRect().top-12;for(let t of targets){let p=t.p.clone().project(camera);if(p.z>1||Math.abs(p.x)>.96||Math.abs(p.y)>.95){t.el.hidden=true;continue;}let x=(p.x*.5+.5)*w,y=(-p.y*.5+.5)*h,r=t.el.getBoundingClientRect(),left=Math.max(r.width/2+8,Math.min(w-r.width/2-8,x)),top=Math.max(155+r.height,Math.min(bottom,y-12));for(let n=0;n<8;n++){let hit=used.find(u=>Math.abs(left-u.x)<(r.width+u.w)/2+5&&top-r.height<u.y+5&&top>u.y-u.h-5);if(!hit)break;top=hit.y-hit.h-8;}t.el.style.left=left+'px';t.el.style.top=top+'px';t.anchor={x,y,left,top};used.push({x:left,y:top,w:r.width,h:r.height});}let svg=k.touchLeaders;if(!svg){svg=k.touchLeaders=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.id='kitchenTouchLeaders';$('#labels').prepend(svg);}svg.setAttribute('viewBox','0 0 '+w+' '+h);svg.replaceChildren();for(let t of targets){if(t.el.hidden||!t.anchor)continue;let l=document.createElementNS(svg.namespaceURI,'line'),a=t.anchor;l.setAttribute('x1',a.left);l.setAttribute('y1',a.top);l.setAttribute('x2',a.x);l.setAttribute('y2',a.y);svg.appendChild(l);}};});
})();
