/* Claw motion, compound contact, lift/slip, gravity and chute detection; no prize lottery. */
(function(){'use strict';
window.ChillUfoGame=class {
 constructor(options){this.o=options;this.T=options.THREE;this.scene=new this.T.Scene();this.scene.background=new this.T.Color('#e4d8de');this.camera=new this.T.PerspectiveCamera(38,1,.1,50);this.camera.position.set(6,5.6,7);this.camera.lookAt(0,.8,0);this.phase='aim';this.time=0;this.keys={};this.done=false;this.closed=false;this.bodies=[];this.base=new this.T.Vector3(0,2.7,0);this.open=.43;this.build();if(options.container){const el=options.container;this.renderer=new this.T.WebGLRenderer({antialias:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));el.appendChild(this.renderer.domElement);this.resize=()=>{let r=el.getBoundingClientRect();this.renderer.setSize(r.width,Math.max(100,r.height));this.camera.aspect=r.width/Math.max(100,r.height);this.camera.updateProjectionMatrix();};this.resize();this.observer=new ResizeObserver(this.resize);this.observer.observe(el);}this.last=performance.now();this.loop=now=>{if(this.closed)return;let dt=Math.min(.05,(now-this.last)/1000);this.last=now;this.step(dt);this.renderer?.render(this.scene,this.camera);this.raf=requestAnimationFrame(this.loop);};this.raf=requestAnimationFrame(this.loop);}
 box(x,y,z,w,h,d,color){const m=new this.T.Mesh(new this.T.BoxGeometry(w,h,d),new this.T.MeshStandardMaterial({color,roughness:.8}));m.position.set(x,y,z);this.scene.add(m);return m;}
 build(){const T=this.T;this.scene.add(new T.HemisphereLight(0xfff4de,0x968dab,2.5));let l=new T.DirectionalLight(0xffffff,2.5);l.position.set(-3,7,5);this.scene.add(l);this.box(.35,-.16,0,4.9,.24,4.2,'#f1dabf');this.box(0,.45,-2.15,5.6,.9,.12,'#c8b4d7');this.box(2.85,.45,0,.12,.9,4.3,'#c8b4d7');this.box(-2.85,.45,-.65,.12,.9,3,'#c8b4d7');this.box(.4,.45,2.15,4.9,.9,.12,'#c8b4d7');this.box(-2.5,-.58,1.75,1.0,.18,1,'#9baa9b');this.box(-2.5,-.25,2.3,1,.7,.1,'#b7c7b4');
 let ids=this.o.models.ids.filter(id=>this.o.stock[id]>0);for(let i=0;i<ids.length;i++){let {group,spec}=this.o.models.create(ids[i],T);const scale=.43;group.scale.setScalar(scale);const body={id:ids[i],group,spec,scale,pos:new T.Vector3((i%3-1)*1.25,.02,Math.floor(i/3)*1.2-1.35),velocity:new T.Vector3(),held:false};this.scene.add(group);this.bodies.push(body);group.position.copy(body.pos);}
 this.claw=new T.Group();this.scene.add(this.claw);const metal=new T.MeshStandardMaterial({color:'#adb1b0',metalness:.3,roughness:.5});const hub=new T.Mesh(new T.CylinderGeometry(.17,.2,.18,16),metal);this.claw.add(hub);this.fingers=[];for(let i=0;i<3;i++){const g=new T.Group(),upper=new T.Mesh(new T.CylinderGeometry(.035,.045,.55,8),metal),tip=new T.Mesh(new T.SphereGeometry(.065,8,6),metal);g.add(upper,tip);this.claw.add(g);this.fingers.push({g,upper,tip,angle:i*Math.PI*2/3});}this.cable=new T.Mesh(new T.CylinderGeometry(.012,.012,1,6),metal);this.scene.add(this.cable);this.positionClaw();}
 positionClaw(){this.claw.position.copy(this.base);for(let f of this.fingers){const x=Math.cos(f.angle)*this.open,z=Math.sin(f.angle)*this.open;f.tip.position.set(x,-.48,z);const end=new this.T.Vector3(x,-.48,z),start=new this.T.Vector3(Math.cos(f.angle)*.14,0,Math.sin(f.angle)*.14);f.upper.position.copy(start).add(end).multiplyScalar(.5);f.upper.quaternion.setFromUnitVectors(new this.T.Vector3(0,1,0),end.clone().sub(start).normalize());f.upper.scale.y=end.distanceTo(start)/.55;}this.cable.position.set(this.base.x,(3.3+this.base.y)/2,this.base.z);this.cable.scale.y=3.3-this.base.y;}
 move(direction,on){if(this.phase==='aim')this.keys[direction]=on;}
 grab(){if(this.phase!=='aim'||this.done)return false;this.phase='lower';this.time=0;this.keys={};return true;}
 startAuto(){this.auto=true;const b=this.bodies[Math.floor(Math.random()*this.bodies.length)];if(b){const gp=new this.T.Vector3(...b.spec.gripPoint).multiplyScalar(b.scale).add(b.pos);this.autoTarget={x:gp.x+(Math.random()-.5)*.28,z:gp.z+(Math.random()-.5)*.28};}else this.autoTarget={x:0,z:0};}
 contact(b){const T=this.T,point=new T.Vector3(...b.spec.gripPoint).multiplyScalar(b.scale).add(b.pos),center=this.base.clone().add(new T.Vector3(0,-.48,0)),radius=(b.spec.gripRadius||.28)*b.scale;let contacts=0;for(let f of this.fingers){const tip=f.tip.position.clone().add(this.base);if(b.spec.colliders.some(c=>{const p=new T.Vector3(...c.center).multiplyScalar(b.scale).add(b.pos);if(c.type==='sphere')return tip.distanceTo(p)<=c.radius*b.scale+.075;if(c.type==='box'){const h=c.halfExtents.map(v=>v*b.scale);return Math.hypot(Math.max(0,Math.abs(tip.x-p.x)-h[0]),Math.max(0,Math.abs(tip.y-p.y)-h[1]),Math.max(0,Math.abs(tip.z-p.z)-h[2]))<.075;}return false;}))contacts++;}return {contacts,point,offset:Math.hypot(center.x-point.x,center.z-point.z),vertical:Math.abs(center.y-point.y),radius};}
 step(dt){if(this.done||this.closed)return;this.time+=dt;
 if(this.phase==='aim'){const speed=1.1;this.base.x=Math.max(-1.9,Math.min(2,this.base.x+dt*speed*((this.keys.right?1:0)-(this.keys.left?1:0))));this.base.z=Math.max(-1.6,Math.min(1.6,this.base.z+dt*speed*((this.keys.front?1:0)-(this.keys.back?1:0))));if(this.auto){let t=this.autoTarget,dx=t.x-this.base.x,dz=t.z-this.base.z;this.base.x+=Math.sign(dx)*Math.min(Math.abs(dx),dt*speed);this.base.z+=Math.sign(dz)*Math.min(Math.abs(dz),dt*speed);if(Math.hypot(dx,dz)<.03)this.grab();}}
 else if(this.phase==='lower'){this.base.y=Math.max(.9,this.base.y-dt*.8);if(this.base.y<=.9){this.phase='close';this.time=0;}}
 else if(this.phase==='close'){this.open=Math.max(.095,.43-this.time*.28);if(this.time>=1.2){this.positionClaw();const choices=this.bodies.map(b=>({b,c:this.contact(b)})).filter(x=>x.c.contacts>=2&&x.c.offset<x.c.radius+.055&&x.c.vertical<.24).sort((a,b)=>a.c.offset-b.c.offset);if(choices.length){const {b,c}=choices[0];this.held=b;b.held=true;this.graspOffset=c.offset;this.graspQuality=Math.max(.05,1-c.offset/(c.radius+.055));this.holdDelta=b.pos.clone().sub(this.base);}this.phase='raise';this.time=0;}}
 else if(this.phase==='raise'){this.base.y=Math.min(2.7,this.base.y+dt*.8);if(this.held&&this.graspQuality<.28&&this.base.y>1.55){this.held.held=false;this.held.velocity.set(.13,0,.05);this.held=null;}if(this.base.y>=2.7){this.phase='travel';this.time=0;}}
 else if(this.phase==='travel'){const tx=-2.45,tz=1.8;this.base.x+=Math.sign(tx-this.base.x)*Math.min(Math.abs(tx-this.base.x),dt*1.1);this.base.z+=Math.sign(tz-this.base.z)*Math.min(Math.abs(tz-this.base.z),dt*1.1);if(Math.hypot(tx-this.base.x,tz-this.base.z)<.01){this.phase='release';this.time=0;}}
 else if(this.phase==='release'){this.open=Math.min(.43,.095+this.time*.6);if(this.held&&this.time>.3){this.held.held=false;this.held.velocity.set(0,0,0);this.held=null;}if(this.time>2.5)this.finish({caught:false});}
 for(let b of this.bodies){if(b.held){b.pos.copy(this.base).add(this.holdDelta);b.group.rotation.z=Math.sin(this.time*4)*.08*(1-this.graspQuality);}else{b.velocity.y-=dt*4.2;b.pos.addScaledVector(b.velocity,dt);const chute=b.pos.x<-2.05&&b.pos.z>1.25;if(chute&&b.pos.y<-.35){this.finish({caught:true,prize:b.id});return;}if(!chute&&b.pos.y<.02){b.pos.y=.02;b.velocity.y=Math.abs(b.velocity.y)*.12;if(b.velocity.y<.1)b.velocity.y=0;b.velocity.x*=.85;b.velocity.z*=.85;}if(!chute){b.pos.x=Math.max(-2,Math.min(2.1,b.pos.x));b.pos.z=Math.max(-1.7,Math.min(1.7,b.pos.z));}}b.group.position.copy(b.pos);}
 this.positionClaw();}
 finish(outcome){if(this.done||this.closed)return;if(this.o.onFinish(outcome)===true){this.done=true;this.phase='complete';}}
 close(){if(this.closed)return;if(!this.done)this.o.onClose();this.dispose();}
 dispose(){if(this.closed)return;this.closed=true;cancelAnimationFrame(this.raf);this.observer?.disconnect();this.renderer?.forceContextLoss();this.renderer?.dispose();this.renderer?.domElement.remove();for(let b of this.bodies){this.scene.remove(b.group);this.o.models.dispose?.(b.group);}this.scene.traverse(o=>{if(o.geometry)o.geometry.dispose();if(o.material)o.material.dispose();});}
};
})();
