const {chromium}=require('C:/Users/CB-Me/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),path=require('path'),assert=require('assert');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true,args:['--allow-file-access-from-files']});let checks=[],errors=[];const page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1});page.on('pageerror',e=>errors.push(e.message));await page.goto('file:///'+path.resolve(__dirname,'../index.html').replaceAll('\\','/'));await page.waitForFunction(()=>window.CHILL?.actors.every(a=>a.hasAsset));
async function check(name,fn){let result=await page.evaluate(fn);checks.push({name,result});assert(result===true,name+': '+JSON.stringify(result));}
await check('new save: four assets, no invented cafe stock',()=>{CHILL.reset();CHILL.setPaused(true);return CHILL.actors.length===4&&CHILL.actors.every(a=>a.hasAsset)&&Object.values(CHILL.cafe.ledger.stock).every(n=>n===0);});
await check('old v2 pantry and furniture preserved; cafe starts empty',()=>{let s=JSON.parse(localStorage.getItem('mob-chill-life-v2'));delete s.cafe;s.kitchen.inventory.dorayaki=7;s.kitchen.inventory.egg=3;s.furnishing.tv={visible:false};localStorage.setItem('mob-chill-life-v2',JSON.stringify(s));CHILL.restore();return CHILL.kitchen.inventory.dorayaki===7&&CHILL.kitchen.inventory.egg===3&&CHILL.room.arrangement.tv.visible===false&&CHILL.cafe.ledger.stock.dorayaki===0;});
await check('exact deposit, insufficient and invalid quantities rejected',()=>{let l=CHILL.cafe.ledger,k=CHILL.kitchen.inventory;return l.deposit(k,'dorayaki',3,CHILL.save)&&k.dorayaki===4&&l.stock.dorayaki===3&&!l.deposit(k,'dorayaki',5,CHILL.save)&&!l.deposit(k,'dorayaki',.5,CHILL.save)&&!l.deposit(k,'dorayaki',-1,CHILL.save);});
await check('failed persistence rolls back both owners',()=>{let l=CHILL.cafe.ledger,k=CHILL.kitchen.inventory,b=JSON.stringify([l.serialize(),k]);l.deposit(k,'dorayaki',1,()=>false);return JSON.stringify([l.serialize(),k])===b;});
await check('camera switch cannot teleport residents',()=>{let before=CHILL.actors.map(a=>a.pos.toArray()).flat().join();CHILL.cafe.setView('cafe');CHILL.cafe.setView('home');return before===CHILL.actors.map(a=>a.pos.toArray()).flat().join();});
await check('home to cafe via door, two seats for three guests',()=>{for(let a of CHILL.actors.slice(0,3)){a.state='idle';a.phase=null;a.cafeWait=0;}CHILL.advance(38);let seated=CHILL.cafe.seats.filter(x=>x!==null);return seated.length<=2&&new Set(seated).size===seated.length&&CHILL.actors.slice(0,3).some(a=>a.room==='cafe');});
await check('service conserves food through multiple guests',()=>{CHILL.advance(95);let l=CHILL.cafe.ledger;return l.stock.dorayaki+Object.keys(l.orders).length+l.eaten===3&&l.eaten>0;});
await check('orders canceled on departure; reload refunds unconsumed once',()=>{let l=CHILL.cafe.ledger;l.restore({stock:{dorayaki:2},orders:{}});l.reserve(0,0,CHILL.save);let s=l.serialize();l.restore(s);let once=l.stock.dorayaki;l.restore(l.serialize());return once===2&&l.stock.dorayaki===2&&Object.keys(l.orders).length===0;});
await check('empty stock cannot reserve or become negative',()=>{let l=CHILL.cafe.ledger;l.restore(null);return !l.reserve(0,0,CHILL.save)&&Object.values(l.stock).every(n=>n===0);});
await check('saved cafe pantry survives actual restore',()=>{CHILL.cafe.ledger.restore({stock:{dorayaki:2,omelet:3,soup:4}});CHILL.save();CHILL.restore();return CHILL.cafe.ledger.stock.omelet===3&&CHILL.cafe.ledger.stock.soup===4;});
await check('ready bubble is single collect for each recipe',()=>{CHILL.cafe.setView('home');for(let [id,r]of Object.entries(CHILL_RECIPES)){let k=CHILL.kitchen,b={status:'ready',recipe:id,startedAt:Date.now()-61000,endsAt:Date.now()-1000};if(id==='dorayaki')k.batch=b;else k.stove[r.station]=b;let n=k.inventory[id];for(let i=0;i<10;i++)k.collectReady(r.station);if(k.inventory[id]!==n+1)return id;}return true;});
for(let width of [320,390,430]){await page.setViewportSize({width,height:844});await page.evaluate(()=>{CHILL.reset();CHILL.setPaused(true);});await page.click('#furnitureButton');await page.selectOption('#mobileFurnitureKey','plant');await page.click('[data-move="0.25,0"]');await page.click('#rotateFurniture');await page.click('#storeFurniture');await page.click('#applyFurniture');await page.evaluate(()=>CHILL.advance(65));await check('furniture move rotate store confirm at '+width,()=>{let a=CHILL.room.arrangement.plant;return a?.visible===false&&Math.abs(a.x+4.05)<.001&&Math.abs(a.rotation-Math.PI/2)<.001;});await page.click('#furnitureButton');await page.selectOption('#mobileFurnitureKey','plant');await page.click('#storeFurniture');for(let i=0;i<3;i++)await page.click('#rotateFurniture');await page.click('#applyFurniture');await page.evaluate(()=>CHILL.advance(65));await check('furniture place at '+width,()=>CHILL.room.furniture.plant.group.visible);await page.click('#furnitureButton');await page.click('[data-move="0.25,0"]');await page.click('#cancelFurniture');await check('furniture cancel at '+width,()=>Math.abs(CHILL.room.arrangement.plant.x+4.05)<.001&&!CHILL.room.mobileEditor);await page.click('#furnitureButton');await page.screenshot({path:path.join(__dirname,'editor-'+width+'.png')});await check('editor within viewport at '+width,()=>{let r=document.querySelector('#furnitureSheet').getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.bottom<=innerHeight&&[...document.querySelectorAll('#furnitureSheet button')].every(b=>b.getBoundingClientRect().height>=44);});await page.click('#cancelFurniture');}
await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{CHILL.reset();CHILL.setPaused(true);CHILL.cafe.ledger.stock.dorayaki=3;CHILL.actors.slice(0,3).forEach(a=>a.cafeWait=0);CHILL.advance(33);CHILL.cafe.setView('cafe');CHILL.tick(0);});await page.screenshot({path:path.join(__dirname,'cafe-390.png')});
await check('room swipe blocked during editor and cooking modal',()=>{CHILL.cafe.setView('home');document.querySelector('#furnitureButton').click();let a=CHILL.cafe.setView('cafe')===false;document.querySelector('#cancelFurniture').click();CHILL.kitchen.openStation('oven');let b=CHILL.cafe.setView('cafe')===false;document.querySelector('#modal').close();return a&&b;});
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(__dirname,'qa-cafe-results.json'),JSON.stringify({checks,errors},null,2));console.log(JSON.stringify({passed:checks.length,errors}));await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
