const {chromium}=require('C:/Users/CB-Me/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const fs=require('fs'),path=require('path'),assert=require('assert'),crypto=require('crypto');const {PNG}=require('C:/Users/CB-Me/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/pngjs');
(async()=>{let root=path.resolve(__dirname,'..'),m=JSON.parse(fs.readFileSync(path.join(root,'MOB_CHILL_LIFE_Nyoro_Irukaeru_108frames/frames.json')));for(let f of m.frames){let img=PNG.sync.read(fs.readFileSync(path.join(root,'MOB_CHILL_LIFE_Nyoro_Irukaeru_108frames',f.file)));assert.equal(img.width,256);assert.equal(img.height,256);assert.equal(crypto.createHash('sha256').update(img.data).digest('hex'),f.sha256);}let results=['108 RGBA hashes and dimensions match manifest'];const browser=await chromium.launch({channel:'msedge',headless:true,args:['--allow-file-access-from-files']});const page=await browser.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true}),session=await page.context().newCDPSession(page);let errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('file:///'+path.join(root,'MOB_CHILL_LIFE.html').replaceAll('\\','/'));await page.waitForFunction(()=>window.CHILL?.actors.every(a=>a.hasAsset));await page.evaluate(()=>{CHILL.reset();CHILL.setPaused(true);});
async function swipe(x,y,dx,dy){await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});for(let i=1;i<=6;i++)await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+dx*i/6,y:y+dy*i/6}]});await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});}
let before=await page.evaluate(()=>CHILL.actors.map(a=>a.pos.toArray()));await swipe(245,101,-115,0);assert.equal(await page.evaluate(()=>CHILL.cafe.view),'cafe');assert.deepEqual(await page.evaluate(()=>CHILL.actors.map(a=>a.pos.toArray())),before);results.push('touch room-strip swipe switches only camera');await swipe(250,300,-110,0);assert.equal(await page.evaluate(()=>CHILL.cafe.view),'cafe');results.push('canvas drag remains camera rotation');await page.evaluate(()=>CHILL.cafe.setView('home'));await page.click('#furnitureButton');await swipe(200,640,0,-90);assert.equal(await page.evaluate(()=>CHILL.cafe.view),'home');await page.click('#cancelFurniture');results.push('furniture panel touch cannot switch rooms');
await page.evaluate(()=>{CHILL.reset();CHILL.setPaused(true);CHILL.setView(.7,.79);let k=CHILL.kitchen,n=Date.now();k.batch={status:'baking',startedAt:n-61000,endsAt:n-1000};k.stove.pan={recipe:'omelet',status:'baking',startedAt:n-61000,endsAt:n-1000};k.stove.pot={recipe:'soup',status:'baking',startedAt:n-61000,endsAt:n-1000};CHILL.tick(0);});await page.screenshot({path:path.join(__dirname,'ready-bubbles-390.png')});for(let name of ['どら焼き','卵焼き','コーンスープ']){let b=page.getByRole('button',{name:name+'の完成品を回収',exact:true});await b.tap();}assert.deepEqual(await page.evaluate(()=>['dorayaki','omelet','soup'].map(k=>CHILL.kitchen.inventory[k])),[1,1,1]);results.push('three actual ready bubbles tapped and collected exactly once');
await page.evaluate(()=>{let k=CHILL.kitchen,n=Date.now();k.batch={status:'baking',startedAt:n-20000,endsAt:n+40000};CHILL.save();});await page.reload();await page.waitForFunction(()=>window.CHILL?.actors.every(a=>a.hasAsset));assert(await page.evaluate(()=>CHILL.kitchen.batch?.status==='baking'&&CHILL.kitchen.inventory.dorayaki===1));results.push('actual browser reload preserves cooking and pantry');
assert(await page.evaluate(()=>{CHILL.setPaused(true);let c=CHILL.cafe,a=CHILL.actors[0];c.ledger.restore({stock:{soup:1}});a.room='cafe';a.cafeMode='seated';a.cafeSeat=0;a.pos.set(12.85,.49,0);c.seats=[0,null];c.actors;c.retry=0;c.waiter(.1);if(!c.service)return false;let ok=c.leave(a);return ok&&c.ledger.stock.soup===1&&Object.keys(c.ledger.orders).length===0&&c.service===null;}));results.push('customer leaving during carry refunds one dish and releases waiter');
assert(await page.evaluate(()=>{let c=CHILL.cafe,a=CHILL.actors[0];c.restore({stock:{omelet:1}});a.room='cafe';a.cafeMode='seated';a.cafeSeat=0;a.pos.set(12.85,.49,0);c.seats=[0,null];c.retry=0;c.waiter(.1);CHILL.save();CHILL.restore();return c.ledger.stock.omelet===1&&Object.keys(c.ledger.orders).length===0&&c.seats.every(s=>s===null);}));results.push('reload in active service refunds unconsumed order and clears seats');
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(__dirname,'qa-touch-results.json'),JSON.stringify({results,errors,artifact:'MOB_CHILL_LIFE.html'},null,2));console.log(JSON.stringify({passed:results.length,errors}));await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
