const {chromium}=require('C:/Users/CB-Me/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),fs=require('fs'),path=require('path'),assert=require('assert');
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true,args:['--allow-file-access-from-files']});const page=await b.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true});let errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('file:///'+path.resolve(__dirname,'../MOB_CHILL_LIFE.html').replaceAll('\\','/'));await page.waitForFunction(()=>window.CHILL?.actors.every(a=>a.hasAsset));
async function check(name,fn){let result=await page.evaluate(fn);checks.push({name,result});assert(result===true,name+': '+JSON.stringify(result));}
await check('Nyoro 0.85 scale, same foot anchor, three individual tables',()=>{CHILL.reset();CHILL.setPaused(true);let a=CHILL.actors[2];return Math.abs(a.scale-1.35*256/160*.85)<1e-6&&a.anchor[1]===.921875&&Math.abs(a.shadow.scale.x-.85)<1e-6&&CHILL.cafe.tables.length===3&&CHILL.cafe.seats.length===3;});
await check('v7 two-order save migrates with no food loss',()=>{let s=JSON.parse(localStorage.getItem('mob-chill-life-v2'));s.cafe={v:1,stock:{dorayaki:2,omelet:1,soup:0},orders:{0:{actor:0,kind:'soup'},1:{actor:1,kind:'dorayaki'}},residents:[{room:'cafe'},{room:'cafe'},{room:'home'}]};s.kitchen.inventory.egg=4;localStorage.setItem('mob-chill-life-v2',JSON.stringify(s));CHILL.restore();let c=CHILL.cafe;return c.seats.length===3&&c.seats.every(x=>x===null)&&c.tables.every(t=>t.group.visible)&&c.ledger.stock.dorayaki===3&&c.ledger.stock.soup===1&&CHILL.kitchen.inventory.egg===4;});
await check('dialogue cycle and reload cursor; no Nyoro smell lines',()=>{let c=CHILL.cafe,a=CHILL.actors[2];let list=Array.from({length:6},(_,i)=>c.say(a,i));if(list.some(t=>/香り|匂い/.test(t)))return false;let lines=Array.from({length:4},()=>c.pick('serve'));if(new Set(lines).size!==4)return false;c.pick('serve');let next=CHILL_CAFE_DIALOGUE.serve[c.dialogueCursor.serve%4];CHILL.save();CHILL.restore();return c.pick('serve')===next&&Object.values(CHILL_CAFE_DIALOGUE).flat().length>=35;});
for(let w of [320,390,430]){await page.setViewportSize({width:w,height:844});await page.evaluate(()=>{CHILL.reset();CHILL.setPaused(true);CHILL.tick(0);});await check('collapsed activity / room visibility '+w,()=>{let f=document.querySelector('footer').getBoundingClientRect();return document.querySelector('#activityPanel').hidden&&f.height<155&&document.querySelector('header').getBoundingClientRect().bottom<100;});await page.screenshot({path:path.join(__dirname,'v8-home-'+w+'.png')});await page.tap('#activityToggle');await check('open activity '+w,()=>!document.querySelector('#activityPanel').hidden);await page.screenshot({path:path.join(__dirname,'v8-activity-'+w+'.png')});await page.tap('#closeActivity');await check('close activity '+w,()=>document.querySelector('#activityPanel').hidden);await page.evaluate(()=>{for(let k of ['dorayaki','omelet','soup'])CHILL.kitchen.inventory[k]=3;CHILL.cafe.depositMenu();});await page.tap('[data-more="dorayaki"]');await page.tap('[data-more="dorayaki"]');await page.tap('[data-more="omelet"]');await page.tap('[data-more="soup"]');await page.tap('[data-less="soup"]');await page.tap('[data-more="soup"]');await page.screenshot({path:path.join(__dirname,'v8-deposit-'+w+'.png')});await check('card touch areas and safe bounds '+w,()=>{let d=document.querySelector('#modal').getBoundingClientRect();return d.left>=0&&d.right<=innerWidth&&d.top>=0&&d.bottom<=innerHeight&&[...document.querySelectorAll('.meal-deposit button')].every(b=>b.getBoundingClientRect().height>=44);});await page.tap('#confirmDeposit');await page.evaluate(()=>document.querySelector('#confirmDeposit').click());await check('card transfer quantities and repeat protection '+w,()=>{let k=CHILL.kitchen.inventory,s=CHILL.cafe.ledger.stock;return k.dorayaki===1&&k.omelet===2&&k.soup===2&&s.dorayaki===2&&s.omelet===1&&s.soup===1;});await page.tap('#depositBack');}
await check('mixed deposit rollback on persistence failure',()=>{let c=CHILL.cafe,k=CHILL.kitchen.inventory,before=JSON.stringify([k,c.ledger.serialize()]);c.ledger.depositMany(k,{dorayaki:1,omelet:1,soup:1},()=>false);return JSON.stringify([k,c.ledger.serialize()])===before;});
await page.setViewportSize({width:390,height:844});
await page.evaluate(()=>{CHILL.reset();CHILL.setPaused(true);let c=CHILL.cafe;c.setView('cafe');c.ledger.stock={dorayaki:1,omelet:1,soup:1};for(let a of CHILL.actors.slice(0,3)){a.room='cafe';a.cafeMode='waiting';a.cafePath=[];a.pos.set(12+a.id*2,0,2.8);a.cafeTimer=0;}});
let samples=await page.evaluate(()=>{let phases=[],maxDishStep=0,maxLowerSpan=0,prev=null,oldPhase=null,seen3=false;for(let n=0;n<1600;n++){CHILL.advance(1/30);CHILL.tick(0);let c=CHILL.cafe,s=c.service;if(s){if(s.stage!==oldPhase){phases.push([s.actor,s.stage]);oldPhase=s.stage;}if(s.stage==='lower'){maxLowerSpan=Math.max(maxLowerSpan,c.handPoint().distanceTo(c.tables[s.seat].plate));if(prev&&prev.seat===s.seat)maxDishStep=Math.max(maxDishStep,prev.p.distanceTo(c.dishes[s.seat].position));}prev={seat:s.seat,p:c.dishes[s.seat].position.clone()};}else {oldPhase=null;prev=null;}if(CHILL.actors.slice(0,3).every(a=>a.cafeMode==='eating')){seen3=true;break;}}return{phases,maxDishStep,maxLowerSpan,seen3,eaten:CHILL.cafe.ledger.eaten,snapshot:CHILL.snapshot()};});console.log(JSON.stringify(samples));assert(samples.seen3);assert.equal(samples.eaten,3);assert(samples.maxDishStep<.1);assert(samples.maxLowerSpan<1.0);checks.push({name:'all three guests eat simultaneously; walking, settle, lower, land, retract in order',result:samples});await page.screenshot({path:path.join(__dirname,'v8-three-eating.png')});
await check('occupied or reserved tables cannot be stored',()=>CHILL.cafe.tables.every((t,i)=>!CHILL.cafe.setTableVisible(i,false)));
await check('all meal ownership conserved during service',()=>{let l=CHILL.cafe.ledger;return Object.values(l.stock).reduce((a,b)=>a+b,0)+Object.keys(l.orders).length+l.eaten===3;});
for(let phase of ['carry','settle','lower','land','retract']){await page.evaluate(()=>{CHILL.reset();CHILL.setPaused(true);let c=CHILL.cafe;c.setView('cafe');c.ledger.stock.soup=1;let a=CHILL.actors[0];a.room='cafe';a.cafeMode='waiting';a.pos.set(12,0,2.2);});let reached=await page.evaluate(phase=>{for(let i=0;i<1000;i++){CHILL.advance(1/30);CHILL.tick(0);if(CHILL.cafe.service?.stage===phase)return true;}return false;},phase);assert(reached,phase);await page.screenshot({path:path.join(__dirname,'v8-service-'+phase+'.png')});await check('reload refunds once during '+phase,()=>{CHILL.save();CHILL.restore();CHILL.save();CHILL.restore();return CHILL.cafe.ledger.stock.soup===1&&Object.keys(CHILL.cafe.ledger.orders).length===0&&CHILL.cafe.seats.every(s=>s===null);});}
await check('table storage and restore persisted',()=>{let c=CHILL.cafe;CHILL.reset();if(!c.setTableVisible(1,false))return false;CHILL.save();CHILL.restore();if(c.tables[1].group.visible)return false;return c.setTableVisible(1,true)&&c.tables[1].group.visible;});
await check('empty stock does not deadlock waiter or invent meals',()=>{CHILL.reset();let c=CHILL.cafe;for(let a of CHILL.actors.slice(0,3)){a.room='cafe';a.cafeMode='waiting';a.pos.set(12+a.id*2,0,2.8);}CHILL.advance(85);return !c.service&&c.ledger.eaten===0&&Object.values(c.ledger.stock).every(n=>n===0)&&c.seats.every(s=>s===null);});
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(__dirname,'qa-v8-results.json'),JSON.stringify({checks,errors},null,2));console.log('Passed '+checks.length+' V8 checks');await b.close();})().catch(e=>{console.error(e);process.exit(1)});
