const fs=require('fs'),assert=require('assert'),{chromium}=require('C:/Users/CB-Me/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true,args:['--allow-file-access-from-files']}),p=await b.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),errors=[];p.on('pageerror',e=>{errors.push(e.message);console.log('PAGEERROR',e.message)});await p.goto('file:///C:/Users/CB-Me/Documents/GitHub/MOB-DENDEN/MOB_CHILL_LIFE.html');await p.waitForFunction(()=>window.CHILL?.cafe?.routine&&CHILL.actors.every(a=>a.hasAsset));await p.evaluate(()=>CHILL.setPaused(true));
const setup=async(hour)=>p.evaluate(hour=>{CHILL.reset();CHILL.setPaused(true);const c=CHILL.cafe;c.clock14=hour/24*CHILL_WORLD_CONFIG.daySeconds;c.arcadeNext=CHILL.actors.map(()=>1e9);CHILL.actors.forEach(a=>{a.timer=a.cafeWait=1e9;a.state='idle';a.phase=null;});c.routine.state={v:1,days:{},meta:{},ownerMeal:null};c.routine.lastPlan=-1;},hour);
const step=async(seconds)=>p.evaluate(seconds=>{const c=CHILL.cafe;for(let t=0;t<seconds;t+=.3){c.clock14+=.3;CHILL.advance(.3);}CHILL.tick(0);},seconds);
await setup(7.1);const before=await p.evaluate(()=>JSON.stringify(CHILL.kitchen.inventory));await step(12);assert.equal(await p.evaluate(()=>JSON.stringify(CHILL.kitchen.inventory)),before);assert.equal(await p.evaluate(()=>CHILL.cafe.wallet.pending.length),0);assert(await p.evaluate(()=>Object.values(CHILL.cafe.routine.state.days).every(r=>r.phase!=='done')));console.log('PASS empty-food morning, no invented food/hearts');
await setup(7.9);await p.evaluate(()=>{CHILL.kitchen.inventory.dorayaki=5;CHILL.kitchen.inventory.omelet=5;CHILL.kitchen.inventory.soup=5;});await step(80);console.log(await p.evaluate(()=>({records:CHILL.cafe.routine.state.days,stock:CHILL.cafe.ledger.stock,meta:CHILL.cafe.routine.state.meta,modes:CHILL.actors.map(a=>[a.key,a.room,a.cafeMode,a.state]),owner:CHILL.cafe.routine.state.ownerMeal})));assert(await p.evaluate(()=>CHILL.cafe.ledger.eaten>0));const total=await p.evaluate(()=>{let c=CHILL.cafe;return ['dorayaki','omelet','soup'].reduce((s,k)=>s+CHILL.kitchen.inventory[k]+c.ledger.stock[k],0)+Object.keys(c.ledger.orders).length+(c.staffMeal&&!c.staffMeal.consumed?1:0)+(c.routine.state.ownerMeal&&!c.routine.state.ownerMeal.consumed?1:0)+c.ledger.eaten+(c.routine.state.meta.nekokoo?.meals||0)});assert.equal(total,15);assert(await p.evaluate(()=>Object.values(CHILL.cafe.routine.state.meta).every(m=>m.meals<=1)));await p.screenshot({path:__dirname+'/routine-meal.png'});console.log('PASS staggered breakfast, stock conservation, one meal per resident');
await setup(12.8);await p.evaluate(()=>{let a=CHILL.actors[0];a.state='acting';a.action='read';a.phase={name:'test job',pose:'idle',duration:1000};a.phaseTime=0;CHILL.kitchen.inventory.soup=2;});await step(5);assert.equal(await p.evaluate(()=>CHILL.actors[0].action),'read');assert.equal(await p.evaluate(()=>CHILL.actors[0].phase.name),'test job');console.log('PASS active work not canceled');
await setup(22.8);await step(35);console.log(await p.evaluate(()=>CHILL.actors.map(a=>({key:a.key,state:a.state,phase:a.phase?.pose,rest:a.routineRest,bed:CHILL.cafe.routine.meta(a).bed}))));assert(await p.evaluate(()=>Object.values(CHILL.cafe.routine.state.meta).filter(m=>m.bed).length<=1));assert(await p.evaluate(()=>CHILL.actors.filter(a=>a.routineRest||CHILL.cafe.routine.meta(a).bed).length===6));await p.screenshot({path:__dirname+'/routine-sleep.png'});await p.evaluate(()=>CHILL.cafe.clock14=CHILL_WORLD_CONFIG.daySeconds+6.1/24*CHILL_WORLD_CONFIG.daySeconds);await step(2);assert(await p.evaluate(()=>CHILL.actors.every(a=>!a.routineRest&&!CHILL.cafe.routine.meta(a).bed)));console.log('PASS sleep / single bed / wake');
await setup(7.9);await p.evaluate(()=>{const a=CHILL.actors[0],r=CHILL.cafe.routine;CHILL.kitchen.inventory.egg=42;r.credit(a);CHILL.save();});const saved=await p.evaluate(()=>({meta:JSON.stringify(CHILL.cafe.routine.state.meta),inv:JSON.stringify(CHILL.kitchen.inventory),clock:CHILL.cafe.clock14}));await p.reload();await p.waitForFunction(()=>window.CHILL?.cafe?.routine);await p.evaluate(()=>CHILL.setPaused(true));assert.equal(await p.evaluate(()=>CHILL.kitchen.inventory.egg),42);assert.equal(await p.evaluate(()=>CHILL.cafe.routine.meta(CHILL.actors[0]).meals),1);assert.equal(await p.evaluate(()=>CHILL.cafe.routine.canEat(CHILL.actors[0])),false);assert(Math.abs(await p.evaluate(()=>CHILL.cafe.clock14)-saved.clock)<1);assert.deepEqual(errors,[]);fs.writeFileSync(__dirname+'/routine-results.json',JSON.stringify({emptyFood:true,noConversationHearts:true,stockConservation:true,oncePerWindow:true,noInterrupt:true,sleepWake:true,singleBed:true,reloadMealRecord:true,offlineClockPreserved:true,errors},null,2));await b.close();console.log('PASS saved daily record / no offline catchup / no errors');})().catch(e=>{console.error(e);process.exit(1)});
