const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{chromium}=require('C:/Users/CB-Me/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true,args:['--allow-file-access-from-files']}),p=await b.newPage({viewport:{width:1400,height:1000}}),errors=[],result={};p.on('pageerror',e=>{errors.push(e.message);console.log(e.stack)});try{await p.goto('file:///'+path.resolve(__dirname,'../index.html').replaceAll('\\','/'));await p.waitForFunction(()=>window.CHILL?.actors.length===8&&CHILL.actors.every(a=>a.key==='mita'?a.hasAsset:a.smooth23));await p.evaluate(()=>{CHILL.reset();CHILL.setPaused(true);const c=CHILL.cafe;c.nextShop22=c.nextLeisure21=c.socialNext23=1e9;c.routine.plan=()=>{};c.clock14=550;c.townActions19.next=1e9;c.arcadeNext=CHILL.actors.map(()=>1e9);c.bagIdle=CHILL.actors.map(()=>1e9);for(const a of CHILL.actors){a.timer=a.cafeWait=1e9;a.path=[];a.cafePath=[];a.phase=null;a.state='idle';a.cafeMode=a.arcadeMode=a.bathMode=null;}window.step=s=>{for(let t=0;t<s;t+=.1){c.clock14+=.1;CHILL.advance(.1);CHILL.tick(0);}};c.wallet.balance=100;c.setView('shop');CHILL.tick(0);});
result.frames=await p.evaluate(()=>CHILL.actors.map(a=>({key:a.key,scale:a.scale,sprite:a.sprite.scale.toArray(),frames:a.smooth23&&Object.fromEntries(Object.entries(a.smooth23).map(([k,v])=>[k,v.length]))})));
result.catalog=await p.evaluate(()=>{const c=CHILL.cafe,figs=CHILL_SHOP_FIGURES23;return{count:figs.length,inGacha:figs.some(f=>Object.hasOwn(c.collections.state.gachaStock,f.id)),inUfo:figs.some(f=>Object.hasOwn(c.collections.state.ufoStock,f.id)),moneyBag:!!c.collections.state.bags[7],routes:figs.map((f,i)=>{const t=c.spaces21.targets.find(t=>t.action==='product'+(i+6));return !!c.routes20.route('shop',new THREE.Vector3(128,0,4.2),t.approach);})};});assert.equal(result.catalog.count,8);assert(!result.catalog.inGacha&&!result.catalog.inUfo&&result.catalog.moneyBag);assert(result.catalog.routes.every(Boolean));
await p.evaluate(()=>{const c=CHILL.cafe,a=CHILL.actors[6];a.pos.set(124,0,-1.2);a.room='shop';a.mitaState21={phase:'idle',time:0};c.product21(6);});await p.locator('[data-take21]').click();await p.evaluate(()=>step(15));assert.equal(await p.evaluate(()=>CHILL.cafe.cart21?.stage),'held');await p.evaluate(()=>CHILL.cafe.checkout21());await p.evaluate(()=>step(20));result.purchase=await p.evaluate(()=>{const c=CHILL.cafe,id=c.cart21.id,r=c.buy21();return{r,id,count:c.collections.items('player')[id],stock:c.stock22(id),money:c.wallet.balance};});assert(result.purchase.r.ok&&result.purchase.count===1&&result.purchase.stock===0);await p.locator('#modalClose').click();
result.restock=await p.evaluate(()=>{const c=CHILL.cafe,id=CHILL_SHOP_FIGURES23[0].id,old=c.wallet.balance,r=c.restock22(id);return{r,delta:old-c.wallet.balance,stock:c.stock22(id)};});assert(result.restock.r.ok&&result.restock.delta===1&&result.restock.stock===1);
result.npc=await p.evaluate(()=>{const c=CHILL.cafe,a=CHILL.actors[7],id=c.products21()[13].id;const start=c.startShopping22(a,13),stages=new Set();for(let i=0;i<2400;i++){if(a.shopVisit22)stages.add(a.shopVisit22.phase);step(.1);if(!a.shopVisit22)break;}return{start,stages:[...stages],finished:!a.shopVisit22,room:a.room,item:c.collections.items(7)[id]};});console.log('NPC',result.npc);assert(result.npc.start&&result.npc.finished&&result.npc.item===1);
result.bath=await p.evaluate(()=>{const c=CHILL.cafe,a=CHILL.actors[7];a.pos.copy(c.homeDoor);a.room='home';a.state='idle';a.phase=null;a.cafeMode=null;a.timer=a.cafeWait=1e9;const start=c.bath.visit(a),stages=new Set();let parkedBeforeSoak=false,picked=false;for(let i=0;i<2400;i++){if(a.bathMode)stages.add(a.bathMode);if(['enter','soak'].includes(a.bathMode)&&a.propPark23)parkedBeforeSoak=true;if(a.propSequence23?.kind==='pick')picked=true;step(.1);if(!a.bathMode&&!a.propSequence23&&!a.propPark23)break;}return{start,stages:[...stages],parkedBeforeSoak,picked,complete:!a.bathMode&&!a.propPark23,pos:a.pos.toArray()};});console.log('BATH',result.bath);assert(result.bath.start&&result.bath.complete&&result.bath.picked&&result.bath.parkedBeforeSoak);
result.social=await p.evaluate(()=>{const c=CHILL.cafe,a=CHILL.actors[4],m=CHILL.actors[7];for(const x of [a,m]){x.room='home';x.path=[];x.cafePath=[];x.phase=null;x.cafeMode=null;x.timer=x.cafeWait=1e9;}a.pos.set(-.7,0,2.5);m.pos.set(.1,0,2.5);c.clock14=550;c.socialCount23=0;const started=c.startSocial23(),lines=[];for(let i=0;i<4;i++){lines.push(c.social23?.lines[c.social23?.index]);step(3.9);}return{started,lines,ended:!c.social23};});assert(result.social.started&&result.social.ended&&result.social.lines.length===4);
result.practice=await p.evaluate(()=>{const c=CHILL.cafe,a=CHILL.actors[4];c.setView('town');c.clock14=550;const started=c.townActions19.start(a);step(7);return{started,practice:c.townActions19.active?.plan.practice23,frame:c.townActions19.active?.frame};});assert(result.practice.started&&result.practice.practice);
await p.screenshot({path:__dirname+'/practice.png'});result.errors=errors;assert.deepEqual(errors,[]);fs.writeFileSync(__dirname+'/behavior-results.json',JSON.stringify(result,null,2));console.log('PASS',result);}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});

