const fs=require('fs'),assert=require('assert'),{chromium}=require('C:/Users/CB-Me/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true,args:['--allow-file-access-from-files']}),p=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true}),errors=[];p.on('pageerror',e=>{errors.push(e.message);console.log('PAGEERROR',e.message)});await p.goto('file:///C:/Users/CB-Me/Documents/GitHub/MOB-DENDEN/MOB_CHILL_LIFE.html');await p.waitForFunction(()=>window.CHILL?.actors.filter(a=>a.addedResident).every(a=>a.motion18Ready));await p.evaluate(()=>{CHILL.setPaused(true);CHILL.cafe.routine.lastPlan=1e9;CHILL.cafe.routine.plan=()=>{};});
const result=await p.evaluate(()=>{const c=CHILL.cafe,all=CHILL.actors.filter(a=>a.addedResident),out={};for(const a of all){const bounds=a.motion18.bounds;out[a.key]={frames:a.motion18.frames.length,boundsSafe:bounds.every(([x,y,w,h])=>x>=8&&y>=8&&x+w<=248&&y+h<=248),bath:a.bathReady,meal:a.mealReady,directions:{}};for(const [name,v]of Object.entries({front:[0,0,1],back:[0,0,-1],left:[-1,0,0],right:[1,0,0]})){const camera=CHILL.camera;camera.updateMatrixWorld();let h=new THREE.Vector3(...v).applyQuaternion(camera.quaternion);h.y=0;out[a.key].directions[name]=c.selectMotion18(a,h).group;}}
return out;});for(const a of Object.values(result)){assert.equal(a.frames,32);assert(a.boundsSafe);assert(a.bath&&a.meal);for(const [k,v]of Object.entries(a.directions))assert.equal(k,v);}
// Export exactly the runtime-isolated canvases for visual review, without synthesizing new poses.
for(const key of ['tetsu','nekokoo']){const url=await p.evaluate(key=>{const a=CHILL.actors.find(a=>a.key===key),canvas=document.createElement('canvas');canvas.width=2048;canvas.height=1024;const ctx=canvas.getContext('2d');a.motion18.frames.forEach((t,i)=>ctx.drawImage(t.image,(i%8)*256,Math.floor(i/8)*256));return canvas.toDataURL();},key);fs.writeFileSync(__dirname+'/'+key+'-runtime.png',Buffer.from(url.split(',')[1],'base64'));}
const setup=async()=>p.evaluate(()=>{CHILL.reset();CHILL.setPaused(true);const c=CHILL.cafe;c.routine.plan=()=>{};c.arcadeNext=CHILL.actors.map(()=>1e9);for(const a of CHILL.actors){a.timer=a.cafeWait=1e9;a.state='idle';a.phase=null;a.path=[];a.cafePath=[];a.npcPose='idle';a.npcTime=0;a.npcOutdoor=a.npcWalking=a.routineRest=false;}c.routine.state={v:1,days:{},meta:{},ownerMeal:null};});
const step=async(seconds)=>p.evaluate(seconds=>{for(let t=0;t<seconds;t+=.2){CHILL.cafe.clock14+=.2;CHILL.advance(.2);}CHILL.tick(0);},seconds);
await setup();assert(await p.evaluate(()=>CHILL.cafe.bath.visit(CHILL.actors[4])));assert(await p.evaluate(()=>CHILL.cafe.bath.visit(CHILL.actors[5])));let seen=new Set();for(let i=0;i<80;i++){await step(2);const modes=await p.evaluate(()=>CHILL.actors.slice(4).map(a=>({key:a.key,mode:a.bathMode,state:a.motionState18,slot:a.bathSlot,pos:a.pos.toArray()})));for(const a of modes)if(a.mode==='soak'){seen.add(a.key);assert.equal(a.state,'bath');await p.evaluate(()=>CHILL.cafe.setView('bath'));await p.screenshot({path:__dirname+'/'+a.key+'-bath.png'});}if(seen.size===2&&modes.every(a=>!a.mode))break;}
assert.deepEqual([...seen].sort(),['nekokoo','tetsu']);const returned=await p.evaluate(()=>({m:CHILL.actors.slice(4).map(a=>[a.key,a.bathMode,a.room]),slots:CHILL.cafe.bath.reservations}));assert(returned.m.every(a=>!a[1]));assert.equal(returned.m[0][2],'home');assert.equal(returned.m[1][2],'bath');assert(returned.slots.every(v=>v===null));result.bathRoundTrip=returned;
await setup();assert(await p.evaluate(()=>{const b=CHILL.cafe.bath;b.reservations=[0,1,2,3];return !b.visit(CHILL.actors[4])&&!b.visit(CHILL.actors[5])}));result.fullBathSafe=true;
await setup();await p.evaluate(()=>{CHILL.cafe.bath.visit(CHILL.actors[4]);CHILL.cafe.bath.visit(CHILL.actors[5]);CHILL.kitchen.inventory.egg=42;CHILL.save();});await p.reload();await p.waitForFunction(()=>window.CHILL?.actors[5]?.motion18Ready);await p.evaluate(()=>{CHILL.setPaused(true);CHILL.cafe.routine.plan=()=>{};});const reload=await p.evaluate(()=>({egg:CHILL.kitchen.inventory.egg,unique:new Set(CHILL.cafe.bath.reservations.filter(x=>x!==null)).size,actors:CHILL.actors.slice(4).map(a=>[a.key,a.bathMode,a.room])}));assert.equal(reload.egg,42);assert.equal(reload.unique,2);assert(reload.actors.every(a=>['entryWait','enter','soak'].includes(a[1])&&a[2]==='bath'));result.reload=reload;
await setup();const meal=await p.evaluate(()=>{let c=CHILL.cafe,a=CHILL.actors[4];a.room='cafe';a.cafeMode='eating';a.cafeSeat=0;a.pos.copy(c.tables[0].seat);a.pos.y=.49;a.mealKind='soup';c.seats[0]=4;let frames=[];for(const t of [.2,1,1.6,3,31.5]){a.cafeTimer=t;c.renderExtraActor(a);frames.push(a.motionFrame18);}a.cafeMode='satisfied';c.renderExtraActor(a);const joy=a.motionState18==='joy';c.setView('cafe');a.cafeMode='eating';a.cafeTimer=1;c.afterRender();return{frames,joy,bakedFood:false,foodVisible:c.dishes[0].visible,extraFood:c.bites[0].visible};});assert.deepEqual(meal.frames,[8,9,10,11,12]);assert(meal.joy);assert(meal.foodVisible&&!meal.extraFood);await p.screenshot({path:__dirname+'/tetsu-meal.png'});result.meal=meal;
await setup();await p.evaluate(()=>{let c=CHILL.cafe;c.setView('bath');c.routine.state.ownerMeal={kind:'omelet',time:1,consumed:true};c.renderExtraActor(CHILL.actors[5]);c.afterRender();});assert.equal(await p.evaluate(()=>CHILL.actors[5].motionFrame18),9);await p.screenshot({path:__dirname+'/nekokoo-meal.png'});result.ownerMealBody=true;assert.deepEqual(errors,[]);result.errors=errors;fs.writeFileSync(__dirname+'/results.json',JSON.stringify(result,null,2));await browser.close();console.log('PASS',result);})().catch(e=>{console.error(e);process.exit(1)});
