/* ふたりの、ひだまり。 Local-only, standalone 3D diorama. */
(()=>{'use strict';
const $=s=>document.querySelector(s),TAU=Math.PI*2,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const scene=new THREE.Scene();scene.background=new THREE.Color('#eae4d8');
let renderer;try{renderer=new THREE.WebGLRenderer({antialias:true,alpha:false})}catch(e){document.body.innerHTML='<div style="max-width:440px;margin:15vh auto;padding:30px"><h1>3D表示を準備できませんでした</h1><p>WebGL対応のChrome・Edge・SafariでHTMLを開いてください。端末やブラウザのハードウェアアクセラレーション設定をご確認ください。</p></div>';return;}renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.setClearColor('#eae4d8');$('#world').appendChild(renderer.domElement);
const camera=new THREE.PerspectiveCamera(36,1,.1,100);let az=.72,el=.75,zoom=1,view=0;
const ambient=new THREE.HemisphereLight(0xfff9dd,0x859397,2.3);scene.add(ambient);const sun=new THREE.DirectionalLight(0xffe7b9,3);sun.position.set(-3,9,5);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-9,right:9,top:9,bottom:-9,near:.1,far:30});sun.shadow.bias=-.001;scene.add(sun);
const warm=new THREE.PointLight(0xffbf6b,12,12,2);warm.position.set(-4,2.5,1);scene.add(warm);
const mat=(c)=>new THREE.MeshStandardMaterial({color:c,roughness:.85});const mats={wood:mat('#b88858'),oak:mat('#dfb780'),cream:mat('#f5edda'),green:mat('#7d9472'),dark:mat('#53634f'),pink:mat('#d6a193'),brass:mat('#b89960'),white:mat('#ffffed')};
function box(x,y,z,w,h,d,m,r=0){let o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),typeof m==='string'?mat(m):m);o.position.set(x,y,z);o.rotation.y=r;o.castShadow=true;o.receiveShadow=true;scene.add(o);return o}
function cyl(x,y,z,rt,rb,h,m,n=24){let o=new THREE.Mesh(new THREE.CylinderGeometry(rt,rb,h,n),typeof m==='string'?mat(m):m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;scene.add(o);return o}
const obstacles=[];function obstacle(x,z,w,d){obstacles.push({x,z,w:w+.38,d:d+.38})}
box(0,-.26,0,10.7,.5,8.7,mats.cream);for(let z=-4;z<4;z+=.4)for(let x=-5;x<5;x+=2){box(x+1,0.005,z+.2,1.98,.04,.385,(Math.round(z*10+x)%3===0)?'#d6b286':'#dfbe92')}
// Two real cutaway walls; the open front keeps residents readable.
box(0,1.55,-4.12,10.4,3.1,.16,'#dedfcd');box(-5.12,1.55,0,.16,3.1,8.4,'#e7e5d5');box(0,.13,-4,10.1,.22,.1,mats.white);box(-5,.13,0,.1,.22,8,mats.white);
box(-2.3,2.02,-4,3.2,1.75,.13,mats.oak);box(-2.3,2.02,-3.91,2.96,1.52,.1,'#b4d6d1');for(let x of [-3.75,-2.3,-.85])box(x,2.02,-3.81,.065,1.56,.12,mats.white);box(-2.3,2.02,-3.81,3.05,.06,.12,mats.white);box(-2.3,1.12,-3.75,3.5,.12,.5,mats.cream);
for(let x of [-4.05,-.55]){box(x,2.05,-3.74,.36,2.1,.13,'#f4eee0');for(let i=0;i<4;i++)box(x-.15+i*.1,2.05,-3.65,.035,2.08,.03,'#e2dcca')}
// Built-in reading shelf.
box(3.65,1.2,-3.65,2.15,2.35,.55,mats.oak);for(let y of [.3,1,1.7,2.35])box(3.65,y,-3.3,2.15,.09,.65,mats.cream);for(let j=0;j<3;j++)for(let i=0;i<7;i++)box(2.8+i*.23,.52+j*.69,-3.35,.14,.36+(i%3)*.07,.32,['#8f9c83','#c98e7d','#e9d2a5','#97b8b5'][i%4]);obstacle(3.65,-3.6,2.2,.65);
// Sofa, cushions, rug and low table.
box(-3.82,.48,.1,1.4,.65,2.6,mats.green);box(-4.43,.96,.1,.28,1.2,2.7,mats.green);for(let z of [-1.15,1.35])box(-3.8,.8,z,1.55,.9,.22,mats.green);for(let z of [-.5,.48])box(-3.7,.87,z,1.12,.22,.86,'#a5b294');box(-4,.99,-.65,.27,.5,.52,'#e8d0a5',.1);box(-4,.99,.5,.27,.5,.52,mats.pink,-.1);obstacle(-3.85,.1,1.65,2.75);
box(-.7,.04,.65,4.05,.035,3.85,'#ded3b9');for(let z of [-1.2,2.5])box(-.7,.063,z,3.98,.01,.055,'#bcae8c');for(let x=-2.6;x<1.2;x+=.17)for(let z of [-1.3,2.65])box(x,.04,z,.03,.02,.22,'#d5c9ae');
cyl(-1.3,.54,.35,.75,.75,.12,mats.oak);for(let x of [-1.65,-.95])for(let z of [0,.7])box(x,.27,z,.09,.52,.09,mats.wood);box(-1.35,.635,.25,.48,.08,.32,'#79968c',.2);cyl(-1.05,.67,.55,.1,.075,.16,mats.white);obstacle(-1.3,.35,1.45,1.45);
// Bed and dining corner.
box(3.45,.33,1.7,2.05,.5,3.15,mats.oak);box(3.45,.64,1.7,1.92,.28,3.02,mats.cream);box(3.45,.82,2.2,1.96,.12,1.95,'#b7c7b0');for(let x of [3,3.9])box(x,.86,.54,.75,.19,.55,mats.white);box(3.45,.84,.05,2.1,1.1,.15,mats.oak);obstacle(3.45,1.7,2.05,3.15);
cyl(1.3,.88,-2.25,.79,.79,.11,mats.oak);cyl(1.3,.44,-2.25,.13,.35,.85,mats.cream);obstacle(1.3,-2.25,1.6,1.6);for(let x of [.55,1.95]){box(x,1,-2.25,.23,.03,.25,mats.white);cyl(x,1.1,-2.25,.1,.08,.17,mats.pink)}
box(.85,.42,-.95,.7,.1,.65,mats.green);for(let x of [.58,1.12])for(let z of [-1.15,-.75])box(x,.22,z,.06,.4,.06,mats.wood);
obstacle(.85,-.95,.7,.65);
// Plants and small details.
function plant(x,z,s=1){cyl(x,.25*s,z,.26*s,.18*s,.5*s,'#c29270');for(let i=0;i<7;i++){let a=i*2.4;let leaf=new THREE.Mesh(new THREE.SphereGeometry(.18*s,8,8),mats.green);leaf.scale.set(.65,2,.65);leaf.position.set(x+Math.cos(a)*.19*s,.6*s+i*.07*s,z+Math.sin(a)*.19*s);leaf.rotation.z=Math.cos(a)*.6;scene.add(leaf)}}plant(-4.4,-2.7,1.4);plant(4.4,-2.6,.85);obstacle(-4.4,-2.7,.7,.7);
box(-4.7,.8,2.8,.48,1.5,.5,mats.oak);cyl(-4.7,1.7,2.8,.45,.25,.55,mats.cream);obstacle(-4.7,2.8,.7,.7);
box(4.95,1.8,-1.9,.08,.8,1.0,mats.oak); // decorative end detail
box(.3,2.3,-3.99,.8,.8,.07,mats.oak);box(.3,2.3,-3.94,.64,.64,.04,'#eee4c9');cyl(.3,2.3,-3.85,.1,.1,.03,mats.pink).rotation.x=Math.PI/2;
box(1.4,.3,3.36,1.2,.52,.65,mats.wood);box(1.4,.59,3.36,1.23,.08,.68,mats.cream);for(let x of [1.03,1.77]){let s=cyl(x,.39,3.715,.16,.16,.02,mats.dark);s.rotation.x=Math.PI/2}obstacle(1.4,3.36,1.25,.7);
// Foot shadows and pixel art planes. Development placeholders are never presented as final artwork.
function placeholder(id){let c=document.createElement('canvas');c.width=32;c.height=40;let p=c.getContext('2d');p.fillStyle=id?'#eaa6bc':'#d9bc79';p.fillRect(7,8,18,22);p.fillRect(4,16,4,12);p.fillRect(24,16,4,12);p.fillRect(8,29,6,9);p.fillRect(19,29,6,9);p.fillStyle='#586657';p.fillRect(9,13,5,5);p.fillRect(18,13,5,5);p.fillStyle='#fff';p.fillRect(10,14,2,2);p.fillRect(19,14,2,2);p.fillStyle='#fff6da';p.font='6px monospace';p.fillText('DEV',10,26);return c}
function texFrom(c){const t=new THREE.CanvasTexture(c);t.magFilter=THREE.NearestFilter;t.minFilter=THREE.NearestFilter;t.colorSpace=THREE.SRGBColorSpace;return t}
const actors=[{id:0,key:'denden',name:'モブデンデン',x:-1.4,z:2,speed:1.05},{id:1,key:'pink',name:'モブピンク',x:1.4,z:.3,speed:1.3}];
let finalCount=0;actors.forEach(a=>{a.mesh=new THREE.Sprite(new THREE.SpriteMaterial({map:texFrom(placeholder(a.id)),transparent:true,alphaTest:.05,depthWrite:false}));a.mesh.scale.set(1.05,1.4,1);a.mesh.center.set(.5,0);scene.add(a.mesh);a.shadow=new THREE.Mesh(new THREE.CircleGeometry(.3,24),new THREE.MeshBasicMaterial({color:0x4e5842,transparent:true,opacity:.18,depthWrite:false}));a.shadow.rotation.x=-Math.PI/2;scene.add(a.shadow);a.bubble=document.createElement('div');a.bubble.className='bubble';$('#labels').appendChild(a.bubble);a.fx=document.createElement('div');a.fx.className='bubble effect';$('#labels').appendChild(a.fx);Object.assign(a,{state:'idle',action:'walk',timer:1+a.id*2,path:[],done:{},cooldowns:{},speech:0,forced:false});loadCharacter(a,(window.CHARACTER_ASSETS||{})[a.key])});
function loadCharacter(a,asset){a.textures={};if(asset&&typeof asset==='object'){for(const [pose,url]of Object.entries(asset))loadAsset(a,url,false,pose)}else loadAsset(a,asset||'assets/'+a.key+'.png',false,'idle')}
function loadAsset(a,url,local,pose='idle'){new THREE.TextureLoader().load(url,t=>{t.magFilter=t.minFilter=THREE.NearestFilter;t.colorSpace=THREE.SRGBColorSpace;a.textures=a.textures||{};a.textures[pose]=t;if(pose==='idle')a.mesh.material.map=t;a.mesh.center.set(.5,local?.08:.078125);a.mesh.material.needsUpdate=true;a.hasAsset=true;a.spriteHeight=local?1.4:3.2;a.mesh.scale.set(a.spriteHeight*t.image.width/t.image.height,a.spriteHeight,1);finalCount=actors.filter(b=>b.hasAsset).length;$('#notice').textContent=finalCount===2?(local?'ローカルで読み込んだキャラクター画像を表示中':''): '開発プレビュー · 正式キャラクター素材の組み込み待ち';$('#notice').hidden=finalCount===2&&!local},undefined,()=>{});}
const actions={walk:{name:'おさんぽ',icon:'↝',duration:3,fx:'',targets:[]},sit:{name:'ソファでひと休み',icon:'♧',duration:10,fx:'…',targets:[[-2.75,.55]],seat:true},nap:{name:'おひるね',icon:'☾',duration:15,fx:'z z Z',targets:[[2.12,1.6]],seat:true},eat:{name:'おやつとお茶',icon:'☕',duration:9,fx:'☕',targets:[[1.75,-1.05]]},read:{name:'本を読む',icon:'▤',duration:12,fx:'▤',targets:[[3.55,-2.65]]},window:{name:'窓をながめる',icon:'☀',duration:8,fx:'☁',targets:[[-2.3,-3.1]]},clean:{name:'おそうじ',icon:'✧',duration:10,fx:'✧',targets:[[.15,1.75]]},plant:{name:'植物のお世話',icon:'♧',duration:9,fx:'💧',targets:[[-3.5,-2.6]]},dance:{name:'音楽とダンス',icon:'♫',duration:10,fx:'♪ ♫',targets:[[.2,2.75]]},chat:{name:'ふたりでおしゃべり',icon:'♡',duration:10,fx:'♡',targets:[[.2,.35]]}};
const reservations=new Map();let history=[],minutes=9*60,elapsed=0,speed=1,paused=false,selected=0,sound=false,saveElapsed=0,frame=0;
const messages={walk:['いい日だゾ！','探検であります！'],sit:['ほぅ〜！ ふかふか。','僕もひと息であります。'],nap:['すやすや…だゾ。','少し休むであります…'],eat:['おいしいんだゾ！','お茶の時間であります！'],read:['ほぅ〜！ なるほど。','僕、続きが気になるであります。'],window:['雲がパンみたいだゾ。','いい景色であります！'],clean:['ぴかぴかだゾ！','僕にお任せであります！'],plant:['おおきくなるんだゾ。','元気に育つであります！'],dance:['ほぅ〜！ 踊るんだゾ！','僕もノリノリであります！'],chat:['いっしょだと楽しいゾ！','僕も楽しいであります！']};
function speak(a,s,d=4){a.bubble.innerHTML='<span class="name">'+a.name+'</span>'+s;a.speech=d}
function log(a,s){history.unshift({at:timeString(),text:a.name+' · '+s});history=history.slice(0,60);renderHistory()}
function timeString(){let m=Math.floor(minutes)%1440;return String(Math.floor(m/60)).padStart(2,'0')+':'+String(m%60).padStart(2,'0')}
function valid(x,z){return x>=-4.55&&x<=4.55&&z>=-3.55&&z<=3.65&&!obstacles.some(o=>Math.abs(x-o.x)<o.w/2&&Math.abs(z-o.z)<o.d/2)}
const step=.25;function node(x,z){return [Math.round((x+4.5)/step),Math.round((z+3.5)/step)]}function coord(i,j){return [i*step-4.5,j*step-3.5]}
function route(x,z,tx,tz){let start=node(x,z),end=node(tx,tz),key=n=>n.join(','),open=[start],came=new Map(),cost=new Map([[key(start),0]]);let ek=key(end),limit=3000;while(open.length&&limit--){open.sort((a,b)=>(cost.get(key(a))+Math.abs(a[0]-end[0])+Math.abs(a[1]-end[1]))-(cost.get(key(b))+Math.abs(b[0]-end[0])+Math.abs(b[1]-end[1])));let cur=open.shift(),ck=key(cur);if(ck===ek){let p=[];while(ck!==key(start)){p.unshift(coord(...cur));cur=came.get(ck);ck=key(cur)}return p}for(let [dx,dz]of [[1,0],[-1,0],[0,1],[0,-1]]){let n=[cur[0]+dx,cur[1]+dz],[wx,wz]=coord(...n),nk=key(n);if(!valid(wx,wz))continue;let g=cost.get(ck)+1;if(!cost.has(nk)||g<cost.get(nk)){cost.set(nk,g);came.set(nk,cur);if(!open.some(t=>key(t)===nk))open.push(n)}}}return null}
function release(a){if(reservations.get(a.action)===a.id)reservations.delete(a.action);if(a.partner!==undefined){const b=actors[a.partner];if(b.state==='social'){b.state='idle';b.timer=2;b.partner=undefined}a.partner=undefined}}
function start(a,key,forced=false){if(!actions[key])return false;let owner=reservations.get(key);if(key!=='walk'&&owner!==undefined&&owner!==a.id){if(forced)speak(a,'今は使っているみたい。少しあとで！');return false}let target=actions[key].targets[0];if(key==='walk'){let choices=[];for(let i=0;i<40;i++){let x=Math.round((-4+Math.random()*8)/step)*step,z=Math.round((-3+Math.random()*6)/step)*step;if(valid(x,z))choices.push([x,z])}target=choices[Math.floor(Math.random()*choices.length)];if(!target)return false}let p=route(a.x,a.z,...target);if(!p)return false;release(a);a.action=key;a.path=p;a.state='moving';a.forced=forced;a.wait=0;a.timer=0;if(key!=='walk')reservations.set(key,a.id);return true}
function choose(a){
// Every available action stays eligible. Preferences change frequency, never remove an action.
let preferences=a.id?['walk','clean','plant','dance','chat','eat','read','window','sit','nap']:['walk','sit','nap','eat','read','window','plant','dance','chat','clean'];
let available=preferences.filter(k=>!reservations.has(k)&&(!a.cooldowns[k]||elapsed>a.cooldowns[k]));
if(!available.length)available=['walk'];
let alternatives=available.filter(k=>k!==a.action);if(alternatives.length)available=alternatives;
let importance=[2.6,2.2,2,1.8,1.6,1.4,1.2,1.1,1,.9],weights=available.map(k=>importance[preferences.indexOf(k)]);
let draw=Math.random()*weights.reduce((sum,w)=>sum+w,0),key=available[available.length-1];
for(let i=0;i<available.length;i++){draw-=weights[i];if(draw<0){key=available[i];break}}
if(!start(a,key))a.timer=1;
}
function arrive(a){a.state='acting';a.timer=actions[a.action].duration;a.total=a.timer;a.done[a.action]=(a.done[a.action]||0)+1;speak(a,messages[a.action][a.id]);log(a,actions[a.action].name);tone(a.id?660:440);if(a.action==='chat'){let b=actors[1-a.id];if(b.state==='idle'||(b.state==='moving'&&b.action==='walk')){release(b);let p=route(b.x,b.z,.95,.35);if(p){b.path=p;b.state='joining';b.partner=a.id;a.partner=b.id}}else{setTimeout(()=>{if(!paused&&a.state==='acting'&&a.action==='chat')speak(b,b.id?'聞こえているであります！':'ほぅ〜！ いいねだゾ！')},800)}}}
function updateActor(a,dt){a.speech=Math.max(0,a.speech-dt);if(a.state==='idle'){a.timer-=dt;if(a.timer<=0)choose(a)}else if(a.state==='moving'||a.state==='joining'){if(a.path.length){let [tx,tz]=a.path[0],dx=tx-a.x,dz=tz-a.z,d=Math.hypot(dx,dz),n=Math.min(d,dt*a.speed);a.x+=dx/(d||1)*n;a.z+=dz/(d||1)*n;a.facing=dx<0?-1:1;if(d<.045)a.path.shift()}else if(a.state==='joining'){a.state='social';a.timer=8;speak(a,messages.chat[a.id]);a.done.chat=(a.done.chat||0)+1;log(a,'ふたりでおしゃべり')}else arrive(a)}else{a.timer-=dt;if(a.timer<=0){release(a);a.cooldowns[a.action]=elapsed+25;a.state='idle';a.timer=1+Math.random()*2;a.forced=false}}
let act=a.state==='acting',t=elapsed*5,bob=(a.state==='moving'||a.state==='joining')?Math.abs(Math.sin(t*1.5))*.055:0,y=.055;
if(act&&a.action==='sit'){y=.5;bob=Math.sin(t*.25)*.01}if(act&&a.action==='nap'){y=.22;a.mesh.material.rotation=Math.sin(t*.12)*.03+.65}else a.mesh.material.rotation=act&&a.action==='dance'?Math.sin(t*1.8)*.16:act&&a.action==='plant'?-.14:0;
let sway=act&&a.action==='dance'?Math.sin(t)*.16:act&&a.action==='clean'?Math.sin(t*.7)*.25:0;
let pose=a.state==='moving'||a.state==='joining'?(Math.floor(elapsed*7)%2?'walk':'walk2'):act?({nap:'sleep',window:'windowlook',plant:'garden'}[a.action]||a.action):a.state==='social'?'chat':'idle';let texture=a.textures?.[pose]||a.textures?.walk&&pose==='walk2'&&a.textures.walk||a.textures?.idle;if(texture&&a.mesh.material.map!==texture){a.mesh.material.map=texture;a.mesh.scale.x=(a.spriteHeight||1.4)*texture.image.width/texture.image.height}if(pose==='sleep'&&a.textures?.sleep)a.mesh.material.rotation=0;let settle=act?Math.min(1,(a.total-a.timer)*1.5,a.timer*1.5):0;let furnitureX=act&&a.action==='sit'?-.7*settle:act&&a.action==='nap'?.65*settle:0;if(act&&a.action==='nap')y=.055+.825*settle;if(act&&a.action==='sit')y=.055+.445*settle;
a.mesh.position.set(a.x+sway+furnitureX,y+bob+(act&&a.action==='dance'?Math.abs(Math.sin(t*1.8))*.16:0),a.z);a.shadow.position.set(a.x,.07,a.z);a.shadow.scale.setScalar(act&&a.action==='nap'?.8:1);a.fx.textContent=act?actions[a.action].fx:a.state==='social'?'♡':'';
// Dedicated action props give every behavior a distinct visual performance.
updateProps(a,act,t);$('#status'+a.id).textContent=a.state==='moving'?actions[a.action].name+'へ':a.state==='social'?'ふたりでおしゃべり':a.state==='acting'?actions[a.action].name:'のんびり考え中';}
function makeProps(a){a.props={};let book=box(0,0,0,.42,.3,.07,'#698e81');a.props.read=book;let cup=cyl(0,0,0,.09,.07,.18,mats.cream);a.props.eat=cup;let broom=box(0,0,0,.035,.9,.035,mats.wood);let head=box(0,0,0,.3,.12,.1,'#d0b472');scene.remove(head);broom.add(head);head.position.set(0,-.4,0);a.props.clean=broom;let can=cyl(0,0,0,.12,.12,.22,'#91b5b0');a.props.plant=can;Object.values(a.props).forEach(p=>p.visible=false)}actors.forEach(makeProps);
function updateProps(a,act,t){for(let [k,p]of Object.entries(a.props)){p.visible=act&&a.action===k&&!a.textures?.[k==='plant'?'garden':k];if(!p.visible)continue;p.position.set(a.x+.32,.65,a.z+.3);p.rotation.y=az;p.rotation.z=k==='clean'?Math.sin(t)*.35:k==='plant'?-.5:k==='eat'?Math.sin(t*.6)*.25:0;if(k==='clean')p.position.y=.5;if(k==='eat')p.position.y=.7+Math.max(0,Math.sin(t*.6))*.2}}
function tone(f){if(!sound)return;try{let ctx=window.audioCtx||(window.audioCtx=new(window.AudioContext||window.webkitAudioContext)());let o=ctx.createOscillator(),g=ctx.createGain();o.type='sine';o.frequency.setValueAtTime(f,ctx.currentTime);g.gain.setValueAtTime(.018,ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+.2);o.connect(g).connect(ctx.destination);o.start();o.stop(ctx.currentTime+.22)}catch{}}
function renderHistory(){$('#history').innerHTML=history.length?history.map(h=>'<p><time>'+h.at+'</time>'+h.text+'</p>').join(''):'<p>ふたりの時間は、ここから。</p>'}
function layout(){let w=innerWidth,h=innerHeight;renderer.setSize(w,h);camera.aspect=w/h;const target=new THREE.Vector3(0,.55,0),dist=(w/h<.8?39/(w/h/.55):20.5)*zoom;camera.position.set(Math.sin(az)*Math.cos(el)*dist,Math.sin(el)*dist,Math.cos(az)*Math.cos(el)*dist);camera.lookAt(target);camera.updateProjectionMatrix()}
function light(){let h=(minutes/60)%24,night=h<6||h>=19;ambient.intensity=night?1.15:2.3;sun.intensity=night?.25:3;warm.intensity=night?30:7;scene.background.set(night?'#b7bfc0':'#eae4d8');$('#clock').textContent=(night?'☾ ':'☀ ')+timeString()}
function labels(){actors.forEach(a=>{let v=a.mesh.position.clone();v.y+=1.35;v.project(camera);a.bubble.style.left=(v.x*.5+.5)*innerWidth+'px';a.bubble.style.top=(-v.y*.5+.5)*innerHeight+'px';a.bubble.style.opacity=a.speech>0?1:0;a.fx.style.left=(v.x*.5+.5)*innerWidth+18+'px';a.fx.style.top=(-v.y*.5+.5)*innerHeight-16+'px';a.fx.style.opacity=a.speech>0?0:1})}
function tick(dt){if(!paused){dt=Math.min(dt,.25)*speed;while(dt>0){let s=Math.min(dt,1/30);elapsed+=s;minutes=(minutes+s*.65)%1440;actors.forEach(a=>updateActor(a,s));dt-=s}saveElapsed+=.016*speed;if(saveElapsed>20){save();saveElapsed=0}}light();labels();renderer.render(scene,camera)}let last=performance.now();function loop(now){tick((now-last)/1000);last=now;frame=requestAnimationFrame(loop)}
function showPanel(id){selected=id;$('#selectedName').textContent=actors[id].name;$('#personality').textContent=id?'きちんと、やさしく。おそうじと植物が好きな働きもの。':'のんびり、好奇心いっぱい。おやつと昼寝、本が好き。';$('#actions').innerHTML=Object.entries(actions).map(([k,v])=>'<button data-action="'+k+'">'+v.icon+' '+v.name+'</button>').join('');$('#panel').hidden=false;$('#journal').hidden=true}
document.querySelectorAll('.resident').forEach(b=>b.onclick=()=>showPanel(+b.dataset.id));$('#actions').onclick=e=>{let b=e.target.closest('[data-action]');if(b){if(start(actors[selected],b.dataset.action,true)){speak(actors[selected],selected?'了解であります！':'やってみるんだゾ！');$('#panel').hidden=true}}};$('#closePanel').onclick=()=>$('#panel').hidden=true;$('#closeJournal').onclick=()=>$('#journal').hidden=true;$('#diary').onclick=()=>{$('#journal').hidden=!$('#journal').hidden;$('#panel').hidden=true;renderHistory()};$('#pause').onclick=()=>{paused=!paused;$('#pause').textContent=paused?'▶':'Ⅱ';$('#pause').title=paused?'再開':'一時停止'};$('#speed').onclick=()=>{speed=speed===1?2:speed===2?4:1;$('#speed').textContent=speed+'×'};$('#camera').onclick=()=>{view=(view+1)%3;az=[.72,.2,1.12][view];el=[.75,.92,.65][view];zoom=1;layout()};$('#time').onclick=()=>{minutes=minutes<720?16*60:minutes<1140?21*60:9*60;light();save()};$('#sound').onclick=()=>{sound=!sound;$('#sound').textContent='音 '+(sound?'ON':'OFF');tone(660)};
function help(){ $('#modalBody').innerHTML='<p>ふたりは自分で行き先を決めて暮らします。下の名前か部屋のキャラクターをタップすると、10種類の行動にお誘いできます。</p><p>ドラッグ：部屋を回転<br>ホイール／2本指ピンチ：拡大・縮小<br>Ⅱ：一時停止　1×：速度切替<br>視点：おすすめの3つの眺め<br>時間帯：朝・夕・夜を切替</p><p>思い出と達成した行動はこのブラウザに自動保存します。音は任意ON、やさしい合成音です。画像読込は端末内だけで処理します。</p><p>モブデンデンとモブピンクは、武器を持たない12ポーズずつのドット絵で暮らします。</p><p>確認版：正式画像組込後のブラウザ実画面は確認待ちです。</p>';$('#modal').showModal()}
$('#help').onclick=help;$('#modalClose').onclick=()=>$('#modal').close();$('#settings').onclick=()=>{$('#modalBody').innerHTML='<p>記録はこの端末のブラウザ内に保存されます。</p><button id="saveNow">いま保存</button><button id="reset" class="danger">記録を初期化</button><p id="saveMessage"></p>';$('#modal').showModal();$('#saveNow').onclick=()=>{$('#saveMessage').textContent=save()?'保存しました。':'保存できません。このブラウザの保存設定をご確認ください。'};$('#reset').onclick=()=>{if(confirm('思い出と行動記録を初期化しますか？')){try{localStorage.removeItem('hidamari-v1')}catch{}history=[];minutes=540;elapsed=0;reservations.clear();actors.forEach((a,i)=>{Object.assign(a,{x:i?1.4:-1.4,z:i?.3:2,state:'idle',timer:1+i,path:[],done:{},cooldowns:{},partner:undefined});a.speech=0});renderHistory();save();$('#modal').close()}}};
$('#import').onchange=e=>{let f=e.target.files[0];if(!f)return;const reader=new FileReader();reader.onload=()=>loadAsset(actors[selected],reader.result,true);reader.readAsDataURL(f)};
function save(){try{localStorage.setItem('hidamari-v1',JSON.stringify({v:1,minutes,history,actors:actors.map(a=>({x:a.x,z:a.z,done:a.done}))}));return true}catch{return false}}
function restore(){try{let s=JSON.parse(localStorage.getItem('hidamari-v1'));if(!s||s.v!==1)return;minutes=Number.isFinite(s.minutes)?s.minutes:540;history=Array.isArray(s.history)?s.history.filter(h=>typeof h.text==='string'&&typeof h.at==='string').slice(0,60):[];s.actors?.forEach((v,i)=>{let a=actors[i];if(a&&Number.isFinite(v.x)&&Number.isFinite(v.z)&&valid(v.x,v.z)){a.x=v.x;a.z=v.z}if(a&&v.done&&typeof v.done==='object')a.done=v.done})}catch{}}
// Pointer gestures distinguish taps from orbiting and work without long-press selection.
let pointers=new Map(),down=null,pinch=0;const canvas=renderer.domElement;canvas.oncontextmenu=e=>e.preventDefault();canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});down={x:e.clientX,y:e.clientY,moved:false};if(pointers.size===2){let p=[...pointers.values()];pinch=Math.hypot(p[0].x-p[1].x,p[0].y-p[1].y);down.moved=true}});canvas.addEventListener('pointermove',e=>{let p=pointers.get(e.pointerId);if(!p)return;let dx=e.clientX-p.x,dy=e.clientY-p.y;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(down&&Math.hypot(e.clientX-down.x,e.clientY-down.y)>5)down.moved=true;if(pointers.size===2){let ps=[...pointers.values()],d=Math.hypot(ps[0].x-ps[1].x,ps[0].y-ps[1].y);zoom=clamp(zoom*pinch/(d||1),.65,1.35);pinch=d}else{az=clamp(az-dx*.005,-.15,1.4);el=clamp(el+dy*.004,.4,1.15)}layout()});canvas.addEventListener('pointerup',e=>{pointers.delete(e.pointerId);if(down&&!down.moved){let ray=new THREE.Raycaster();ray.setFromCamera(new THREE.Vector2(e.clientX/innerWidth*2-1,1-e.clientY/innerHeight*2),camera);let hit=ray.intersectObjects(actors.map(a=>a.mesh));if(hit.length){let a=actors.find(a=>a.mesh===hit[0].object);showPanel(a.id);speak(a,a.id?'僕を呼んだであります？':'なあに？ だゾ！')}}if(!pointers.size)down=null});canvas.addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);down=null});canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=clamp(zoom+e.deltaY*.001,.65,1.35);layout()},{passive:false});window.addEventListener('resize',layout);document.addEventListener('visibilitychange',()=>{last=performance.now();if(document.hidden)save()});window.addEventListener('pagehide',save);
restore();layout();light();requestAnimationFrame(loop);
window.HIDAMARI={actors,actions,reservations,obstacles,start,route,valid,tick,save,restore,get state(){return{elapsed,minutes,paused,speed,history}},setPause(v){paused=v},setSpeed(v){speed=v},advance(seconds,dt=1/30){for(let t=0;t<seconds;t+=dt){let rem=Math.min(dt,seconds-t);while(rem>0){let ss=Math.min(rem,1/30);elapsed+=ss;minutes=(minutes+ss*.65)%1440;actors.forEach(a=>updateActor(a,ss));rem-=ss}}},snapshot(){return actors.map(a=>({name:a.name,x:a.x,z:a.z,state:a.state,action:a.action,done:a.done,path:a.path.length}))}};
})();
