/* Headless logic checks only. WebGLRenderer/DOM are stubs, not browser visual QA. */
const fs=require('fs'),vm=require('vm'),assert=require('assert');
const THREE0=require('./vendor/three.min.js');const pending=[];const nodes=new Map();
function element(){return {style:{},textContent:'',innerHTML:'',hidden:false,dataset:{},children:[],appendChild(x){this.children.push(x)},addEventListener(){},setPointerCapture(){},showModal(){},close(){},getContext(){return {fillRect(){},fillText(){}}}}}
const doc={body:element(),hidden:false,querySelector(s){if(!nodes.has(s))nodes.set(s,element());return nodes.get(s)},querySelectorAll(){return []},createElement:element,addEventListener(){}};
class Renderer{constructor(){this.domElement=element();this.shadowMap={}}setPixelRatio(){}setClearColor(){}setSize(){}render(){} }
class Loader{load(url,ok){const b=Buffer.from(url.split(',')[1],'base64');assert.equal(b.toString('hex',0,8),'89504e470d0a1a0a');let image={width:b.readUInt32BE(16),height:b.readUInt32BE(20)};pending.push(()=>ok(new THREE0.Texture(image)))}}
const memory=new Map();const initialSeed=Number(process.env.QA_SEED||47219);let seed=initialSeed;const math=Object.create(Math);math.random=()=>{seed=(1664525*seed+1013904223)>>>0;return seed/4294967296};
const ctx={THREE:{...THREE0,WebGLRenderer:Renderer,TextureLoader:Loader},document:doc,console:{warn(){},log(){}},devicePixelRatio:1,innerWidth:390,innerHeight:844,Math:math,performance:{now:()=>0},requestAnimationFrame:()=>0,setTimeout:()=>0,localStorage:{getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v),removeItem:k=>memory.delete(k)},addEventListener(){},FileReader:function(){},confirm:()=>true};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(fs.readFileSync('./assets/characters.js','utf8'),ctx);vm.runInContext(fs.readFileSync('./game.js','utf8'),ctx);pending.forEach(f=>f());const g=ctx.HIDAMARI;
function reset(){g.reservations.clear();g.actors.forEach((a,i)=>Object.assign(a,{x:i?1.4:-1.4,z:i?.3:2,state:'idle',timer:9999,path:[],done:{},cooldowns:{},partner:undefined,speech:0}));}
const result={type:'logic-only; DOM and renderer stubbed; no visual or WebGL verification',seed:initialSeed,assets:g.actors.map(a=>({key:a.key,poseCount:Object.keys(a.textures).length,height:a.mesh.scale.y,center:a.mesh.center.toArray()})),actions:[]};
g.setPause(true);
for(let id=0;id<2;id++)for(let key of Object.keys(g.actions)){reset();let a=g.actors[id];let ok=g.start(a,key,true),invalid=0;for(let i=0;i<240&&a.state!=='acting';i++){g.advance(.25);if(!g.valid(a.x,a.z))invalid++}let pose={nap:'sleep',window:'windowlook',plant:'garden',walk:'walk'}[key]||key;result.actions.push({actor:a.key,action:key,started:ok,reached:a.state==='acting',validFloorPath:invalid===0,dedicatedTexture:a.mesh.material.map===a.textures[pose]||(key==='walk'&&a.mesh.material.map===a.textures.walk2),propsHidden:Object.values(a.props).every(p=>!p.visible)});assert(ok&&a.state==='acting'&&invalid===0,JSON.stringify(result.actions[result.actions.length-1]))}
reset();result.reservation={first:g.start(g.actors[0],'eat'),second:g.start(g.actors[1],'eat')};assert(result.reservation.first&&!result.reservation.second);
reset();g.actors.forEach(a=>a.timer=0);let invalid=0,conflicts=0;for(let i=0;i<14400;i++){g.advance(.25);g.actors.forEach(a=>{if(!g.valid(a.x,a.z))invalid++});const [a,b]=g.actors;if(a.action===b.action&&!['walk','chat'].includes(a.action)&&['moving','acting'].includes(a.state)&&['moving','acting'].includes(b.state))conflicts++}result.autonomousOneHour=JSON.parse(JSON.stringify(g.snapshot()));result.autonomousAllActions=g.actors.every(a=>Object.keys(g.actions).every(k=>a.done[k]>0));result.floorIntrusions=invalid;result.furnitureConflicts=conflicts;assert(!invalid&&!conflicts&&result.autonomousAllActions);result.finite=g.actors.every(a=>Number.isFinite(a.x)&&Number.isFinite(a.z));
g.save();let saved=memory.get('hidamari-v1');g.actors.forEach(a=>a.done={});g.restore();result.saveRestore=JSON.stringify(g.actors.map(a=>a.done))===JSON.stringify(JSON.parse(saved).actors.map(a=>a.done));let before=JSON.stringify(g.snapshot());g.tick(.25);result.pauseUnchanged=before===JSON.stringify(g.snapshot());g.setPause(false);let elapsed=g.state.elapsed;for(let i=0;i<200;i++)g.tick(.25);result.lowFpsElapsed=g.state.elapsed-elapsed;result.lowFpsAdvances=result.lowFpsElapsed>49.99;fs.writeFileSync(process.env.QA_OUT||'qa-final-logic.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));
